### ISSUE TITLE
v3 - Image thumbnails are not PrismicImageType

### ISSUE THREAD

**Issue by angeloashmore** [angeloashmore/gatsby-source-prismic#100]
Image thumbnails are not `PrismicImageType`. The types are currently inferred, meaning the resolver for PrismicImageType cannot return `localFile` data.

The fix should happen here: https://github.com/angeloashmore/gatsby-source-prismic/blob/2a265e10935b6633bae60059e8c91101d8341d57/src/generateTypeDefsForCustomType.js#L55-L85

**Comment by me4502** [comment]
Is there any update on this?

**Comment by evolkmann** [comment]
For anybody needing this functionality, you can use the following workaround. In your `gatsby-node.js` you can override the type:

```js
exports.createSchemaCustomization = ({ actions }) => {
    const { createTypes } = actions
    const typeDefs = `
      type PrismicImageType implements Node {
        thumbnail: PrismicImageType
      }
    `
    createTypes(typeDefs)
}

```

**Comment by angeloashmore** [comment]
@evolkmann Thanks for the workaround!

Note to self: PrismicImageType may need to be generated like PrismicLinkType by including an aggregate list of thumbnail names as fields.

**Comment by angeloashmore** [comment]
Thanks for everyone's patience on this. Image thumbnail support should be working in the latest `v3.0.0-beta.12` release.

Thumbnails are listed under the `thumbnails` field within image fields.

See the migration guide for more details: https://github.com/angeloashmore/gatsby-source-prismic/blob/b01979be609376e299d90094a8bb2808e2c05a33/docs/migrating-from-v2-to-v3.md#namespacing-image-thumbnails

**Comment by angeloashmore** [comment]
Closing this but please reply if you are still experiencing issues with this. Thanks!
