### ISSUE TITLE
v3 - Preview PrismicLinkType `document` field is undefined.

### ISSUE THREAD

**Issue by asyarb** [angeloashmore/gatsby-source-prismic#101]
Previewed Prismic docs with PrismicLinkType fields have undefined `document` keys in the normalized result. 

Was able to temporarily resolve by adding a placeholder value for the `document` key in the returned `Proxy`, but unsure why this even fixes the issue.

**Temporary Fix: (live in 3.0.0-alpha.3)**

https://github.com/angeloashmore/gatsby-source-prismic/blob/9d8ed26b20d9625a5bf52953a0eb9b127c50bd9a/src/normalizers/browser.js#L63-L84

This shouldn't be necessary since `nodeStore` and the `linkedDocId` seem to both be correct, but for some reason our `proxyHandler` isn't doing what we expect.

**Comment by max8hine** [comment]
Seems I have the same error

`gatsby develop` break when using `elemMatch` in GraphQL filter.

**TypeError: Cannot read property 'key' of undefined** 

in

**[gatsby-source-prismic]/dist/gatsby-node.js:280:33**


![image](https://user-images.githubusercontent.com/15165714/64141170-30591100-ce5b-11e9-9c5c-4450327ceae2.png)

Env:
"gatsby-source-prismic": "^3.0.0-alpha.0",
"gatsby": "^2.15",
"react": "^16.8.0",

**Comment by angeloashmore** [comment]
Hi @max8hine, thanks for reporting this issue. Could you share your schema? I'm wondering what your `tags` field looks like.

Also, could you try with the latest version: `v3.0.0-beta.10`? I don't believe this portion of the code has been touched for a while, but it would be nice to rule out an old version being the issue. Thanks!

**Comment by max8hine** [comment]
Hi @angeloashmore, Thank you for responding here.

The link of [posts_tags.json](https://github.com/batchnz/gatsby-starter-prismic/blob/update-gatsby-source-prismic/src/schemas/posts_tags.json)

GraphiQL will break the `gatsby develop` process with the filter on in above screenshot.
If the filter did not contain `elemMatch` operator, the GraphiQL works well. 

Also, We upgrade to `v3.0.0-beta.10`, the error persist。

**Comment by Jezfx** [comment]
Having the same issue as @michaeljblum upgrading to V3 for preview support and running into: `TypeError: Cannot read property 'key' of undefined, in [gatsby-source-prismic]/dist/gatsby-node.js:279:33.` — still not been able to find a fix, or even work around

**Comment by max8hine** [comment]
> I have the same exact error as @max8hine: TypeError: Cannot read property 'key' of undefined, in
> [gatsby-source-prismic]/dist/gatsby-node.js:279:33.
> 
> Attempting to migrate to v3 for preview support, but even after fixing all my queries and adding schemas and everything, I'm still getting hard errors, and this one, in particular, breaking the build.
> 
> Max, did you find a way of navigating this issue?

Sorry, I haven't, I've paused the upgrading process to v3 😢

**Comment by angeloashmore** [comment]
This temporary patch was removed in `v3.0.0` and seems to be working as expected now.
