### ISSUE TITLE
mergePrismicPreviewData merges repeatable fields incorrectly

### ISSUE THREAD

**Issue by good-idea** [angeloashmore/gatsby-source-prismic#106]
When previewing a page with a sub-document that has repeatable fields, `mergePrismicPreviewData` merges the two arrays incorrectly when the number of those fields has changed. For example:

Original Document:
  - title: `'My Book'`
  - genres: `['autobiography', 'sci-fi']`

Updated Document:
  - title: `'My Book'`
  - genred: `['sci-fi']`

Merged Document:
  - title: `'My Book'`
  - genres: `['sci-fi', 'sci-fi']`

While the page query fetches `allPrismicBooks`.

(I'd be happy to provide some examples of actual prismic data if that's helpful.)

This is just how lodash's `merge` works:

`_.merge(['1', '2', '3'], ['2','3']) // => ['2', '3', '3']`

I suppose a solution would be completely replacing the 'My Book' document instead of merging it in 'over' itself. I gave this a shot in a fork but wasn't able to figure out right away.

**Comment by asyarb** [comment]
Thanks for trying the plugin! 

You're absolutely right, `merge` does handle arrays in the way you describe. I agree that the best way to handle this is to just replace the document instead of merging it over itself. Looks like lodash's `mergeWith` function would be perfect for this:

```js
const mergeCopyArrays = (obj, src) => {
  if (isArray(obj)) return src
}

const _mergeStaticData = (staticData, previewData) => {
  const previewKey = compose(
    head,
    keys,
  )(previewData)

  if (!has(previewKey, staticData))
    return _traversalMerge(staticData, previewData, previewKey)

  return mergeWith(mergeCopyArrays, staticData, previewData)
}
```

@angeloashmore and I should be able to review and merge these changes later today.

**Comment by angeloashmore** [comment]
@asyarb Yeah, that approach looks good. Replacing the whole document wouldn't work if your GraphQL query contains non-Prismic stuff (think: aliased fields, transformer child nodes), so limiting it to just replacing arrays should solve that.

**Comment by angeloashmore** [comment]
@good-idea Sorry, forgot to revisit this issue! The fix mentioned above is in `v3.0.0-beta.0`. Could you give it a try and let us know if the issue is resolved?

**Comment by Fl0rianFischer** [comment]
@angeloashmore I'm not sure if I'm doing something wrong but on `v3.0.0-beta.4` it seems like arrays are not merged at all but the merged result is just the published document and not the saved one. Can anyone confirm?

**Comment by angeloashmore** [comment]
Hi @Fl0rianFischer, I should have time to devote to the plugin today. I'll take a look and make sure our tests check for the array merging (really it's just a replacement, not a merge).

You *should* see your preview data replace any arrays.
