### ISSUE TITLE
Doesn't work with private API access setting

### ISSUE THREAD

**Issue by DaleWebb** [angeloashmore/gatsby-source-prismic#11]
When the API access under "Repository Security" in settings has been changed to "private".  There is a 401 response from Prismic, because the access token isn't passed

**Comment by angeloashmore** [comment]
Hey @DaleWebb, I should have time to look at this in a few days. In the mean time, let me know if you find a fix. Thanks! 👍

**Comment by DaleWebb** [comment]
I have a fix, I can push it tomorrow if you like?

**Comment by angeloashmore** [comment]
Yup, sounds good. If you submit a PR I can take a look at it.

**Comment by samirfors** [comment]
I kind of needed this feature now, so I just added the PR for it.

**Comment by angeloashmore** [comment]
Thanks, don't know how I missed that. 🙄 

Just published `v0.1.2` with the fix: .
