### ISSUE TITLE
Image download issue

### ISSUE THREAD

**Issue by RobinHerzog** [angeloashmore/gatsby-source-prismic#114]
I have a strong internet connection.

I don't know what to do, to fix that.

Downloaded never end.

Version: 2

May this help: https://github.com/gatsbyjs/gatsby/issues/14173#issuecomment-500702399 ?

<img width="937" alt="Capture d’écran 2019-07-07 à 22 03 07" src="https://user-images.githubusercontent.com/4397570/60773253-1e7d1b00-a103-11e9-8a2b-ebfaa87d94ef.png">

**Comment by RobinHerzog** [comment]
Add GATSBY_CONCURRENT_DOWNLOAD before gatsby develop

GATSBY_CONCURRENT_DOWNLOAD=1 gatsby develop

**Comment by giacomoalonzi** [comment]
@RobinHerzog I tried but the problem is still here. Any Hint?
