### ISSUE TITLE
Preview share link

### ISSUE THREAD

**Issue by apdrsn** [angeloashmore/gatsby-source-prismic#117]
Hi :) and thank you for making this plugin.

I got it to work showing previews on my site using version 3.0.0-beta.4, however I can't seem to get it to work with Prismic feature, share preview link.

The link that is being copied is just the "original" url, so no preview available.

Has anyone else experienced that?

**Comment by angeloashmore** [comment]
Closing this out as `v3` has been in open beta for a while now and solves this issue. Please give it a try if you haven't yet!
