### ISSUE TITLE
Beta V4, empty hook

### ISSUE THREAD

**Issue by RobinHerzog** [angeloashmore/gatsby-source-prismic#120]
Hi,
I installed all last package.

On the v3 I had data from the hooks. Since the v4, no data is returned from the hooks.

**Comment by Ehesp** [comment]
There is no v4?

**Comment by RobinHerzog** [comment]
https://github.com/angeloashmore/gatsby-source-prismic/tree/v3.0.0-beta.4

**Comment by angeloashmore** [comment]
@RobinHerzog We still need to update the README to reflect some recent changes, but it might be missing options in the hook.

`repositoryName` is now a required parameter in the hook. This should throw an error when using the hook. Can you also check the console to see if an error is printing there?

Your hook should have at least the following:

```js
const { previewData, path, isPreview } = usePrismicPreview({
  repositoryName: 'repository_name'
})
```
