### ISSUE TITLE
Rich Text field returns on array for plain text objects instead of html.

### ISSUE THREAD

**Issue by zerostyle** [angeloashmore/gatsby-source-prismic#127]
I can't seem to get Rich Text to output `html` in my queries. Instead I only have the option as `text`, and it renders the text in an array.

Here is my Rich Text field in Prismic:
```
"copyright" : {
  "type" : "StructuredText",
  "config" : {
    "multi" : "paragraph, preformatted, strong, em, hyperlink",
    "allowTargetBlank" : true,
    "label" : "Copyright"
  }
}
```

This what I get in return:
``` 
"copyright": [
  {
    "text": "© 2019.",
    "type": "paragraph"
  },
  {
    "text": "All rights reserved.",
    "type": "paragraph"
  }
 ]
```

The strange thing is that this is not happening every time. I have been able to get `html` text with the exact same setup in other places in the cms.

**Comment by angeloashmore** [comment]
Hi @zerostyle, which version of `gatsby-source-prismic` are you using?

**Comment by zerostyle** [comment]
I'm using `3.0.0-beta.4`.

**Comment by angeloashmore** [comment]
This might be a result of not updating your custom type schema in your project. Gatsby may be inferring the type since the schema isn't telling the source plugin what kind of field "copyright" is.

Could you update your `.json` file and check again?

**Comment by angeloashmore** [comment]
Somewhat related: https://github.com/angeloashmore/gatsby-source-prismic/issues/109

We could potentially have a system that automatically tells you if it suspects the schema is out of date. This can be done by checking if page data contains fields not in the schema.

**Comment by zerostyle** [comment]
I double-checked my schema the `.json` file the schema is up to date. Is there anything to check?

**Comment by angeloashmore** [comment]
Can you run `gatsby develop --verbose` and look for somewhere that says:

```
verbose gatsby-source-prismic - writing out type paths to: [file path here]
```

That file path contains the types of all fields. Can you post that file here? Or at least the part that contains your `copyright` field?

**Comment by zerostyle** [comment]
I figured this out, and it was missing from the schema. Thanks for your help.

**Comment by angeloashmore** [comment]
Awesome! Glad to hear it's working now. 🤙
