### ISSUE TITLE
Some links does not contain url.

### ISSUE THREAD

**Issue by mathiasha** [angeloashmore/gatsby-source-prismic#129]
On my page I have a have a link. I have added this to the link resolver:

```
linkResolver: () => doc => {
  if (doc.lang === 'da-dk') {
    if (doc.type === 'post') return `/artikler/${doc.uid}`;

    return `/${doc.uid}`;
  }

  if (doc.lang === 'en-gb') {
    if (doc.type === 'post') return `/en/articles/${doc.uid}`;

    return `/en/${doc.uid}`;
  }

  return `/${doc.uid}`;
},
```
This works correctly when accessing the `url` property on the link.
However I also have a Navigation type, that has the global navigation of my site. The navigation type consists of slices with links, but they do not have the `url` property on the link. 

Does anyone know why that is the case?

I am running version 3.0.0-beta.4 of the gatsby-source-prismic module.

**Comment by mathiasha** [comment]
Turns out i had forgotten to provide a schema to the module. 
I have added it now, but for some reason this query returns an empty array on `body`.

```
prismicMainNavigation {
  lang
  data {
    body {
      ... on PrismicMainNavigationBodyMenuItem {
        primary {
          navigation_item_text
          navigation_item_link {
            uid
            url
          }
        }
      }
    }
    cta_text_1
    cta_text_2
    navigation_name
  }
}
```

I know there is content in Prismic, so i am not sure why it returns an empty array on `body`. The other fields on the item do have values.

**Comment by angeloashmore** [comment]
Hi @mathiasha, you could try clearing your Gatsby cache.

This command will delete your `.cache` and `public` folder.
```sh
gatsby clean
```

Your query looks correct. If `body` is an empty array, it means Gatsby thinks your document has no data in `body`, which we know should be incorrect since Prismic has data.
