### ISSUE TITLE
Public and src aren't synchronized

### ISSUE THREAD

**Issue by mikedotJS** [angeloashmore/gatsby-source-prismic#13]
Hey,

What is compiled and published on npm isn't synchronized with the current source on GitHub.

For example the fetch.js on npm doesnt use `accessToken` variable :

// fetch.js - on npm
L93 `return _prismicJavascript2.default.getApi(apiEndpoint);`

// fetch.js - on GitHub
L8 `const client = await Prismic.getApi(apiEndpoint, { accessToken })`

It causes a 401 error when i try to connect to my Prismic API.

**Comment by angeloashmore** [comment]
Just pushed `v0.1.3`. Could you update project and test it out?

I think I may have forgotten to rebuild on the last publish. I added a `prepublish` script to prevent that in the future.

Thanks 👍

**Comment by mikedotJS** [comment]
Hey, sorry for the late,

It's all good !

Thank you !

**Comment by angeloashmore** [comment]
No problem. Thanks for opening the issue!
