### ISSUE TITLE
V2: Expected JSON to be a GraphQL nullable type.

### ISSUE THREAD

**Issue by jordyvanraaij** [angeloashmore/gatsby-source-prismic#131]
Since yesterday I'm not able to successfully execute a Gatsby build on Netlify anymore:

```
10:41:08 AM: success open and validate gatsby-configs — 0.013
10:41:09 AM: error Expected JSON to be a GraphQL nullable type.
10:41:09 AM: Error in "/opt/build/repo/node_modules/gatsby-source-prismic/gatsby-node.js": Expected JSON to be a GraphQL nullable type.
10:41:09 AM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
10:41:09 AM: 
10:41:09 AM:   Error: Expected JSON to be a GraphQL nullable type.
```

I'm using gatsby-source-prismic@2.3.0-alpha.3. Locally it does build successfully but on Netlify it doesn't. Anyone ran into the same issue?

**Comment by angeloashmore** [comment]
I haven't come across that exact error, but it could be a result of an old cache. First thing I would try is rebuilding on Netlify with a clean cache.

![image](https://user-images.githubusercontent.com/8601064/63969857-86364f00-ca3e-11e9-83c7-824d59a0109b.png)

If that doesn't work…

If you stick to **v2**: Could you try using `2.3.0-alpha.6`? I know the versions are a bit messy right now, but we are planning to publish `v3` soon which will clean up the versions.

If you want to try out **v3**: This shouldn't be an issue. If you come across this on V3 as well, could you report back?

Thanks for your help in diagnosing this!
