### ISSUE TITLE
V3: Previewing processed images

### ISSUE THREAD

**Issue by jordyvanraaij** [angeloashmore/gatsby-source-prismic#132]
It's currently not possible to preview images that are being processed by the `gatsby-plugin-sharp` plugin. Is it possible to add support? Or do you guys have alternative solutions?

**Comment by angeloashmore** [comment]
Hi @jordyvanraaij, correct, the preview feature is unable to provide the same gatsby-image we get from the Gatsby data. The preview feature works 100% in the browser where `gatsby-plugin-sharp` cannot run.

We have some ideas of how we can support this, but in the meantime, please see this for an explanation on how to work with images in previews: https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/docs/previews.md#images

**Idea 1**: Create a "fake" `gatsby-image` object for `fluid` and `fixed`. The images would continue to use the Prismic URLs (i.e. they would not be resized), but `gatsby-image` would be able to consume and display the image as if it weren't a prevew.

**Idea 2**: Use Prismic's upcoming Imgix support to provide `gatsby-image` on the fly. This would also have the benefit of using the Imgix images in your normal site, eliminating the need to download and process images on the server. This could reduce build times significantly.

**Comment by jordyvanraaij** [comment]
Perfect, thank you for the explanation! I will try to work with the custom image component for know.
