### ISSUE TITLE
V3: Image alt tags not handled by Schema?

### ISSUE THREAD

**Issue by OllieJT** [angeloashmore/gatsby-source-prismic#134]
Version: ^3.0.0-beta.10

If I don't use schemas I get errors for querying fields that have not been used yet. Recently I have begun getting similar errors on all my image fields ALT tags despite using the schema.

Expected result: Query images and their alt tags even if no image for this field has an alt tag yet.

Actual result: If an alt tag does not exist for this field on this query the build fails. Example error below

_I have temporarily 'fixed' this by not querying alt tags for less used fields._

```
 ERROR  Failed to compile with 1 errors                                        12:38:23 PM
⠀
 error  in ./src/templates/prismic_client.js
⠀
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/olliejt/Documents/GitHub/VBI/visualsbyimpulse/src/templates/prismic_client.js
  59:13  error  Cannot query field "alt" on type "PrismicStaffDataAvatarSmall"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./.cache/sync-requires.js 2:487-582
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
⠀
✖ ｢wdm｣:
ERROR in ./src/templates/prismic_client.js
Module Error (from ./node_modules/eslint-loader/index.js):
```

**Comment by angeloashmore** [comment]
Closing this out as it doesn't seem to be an active issue. Please let me know if this continues to be an issue!
