### ISSUE TITLE
Gatsby localfile on graphql image field

### ISSUE THREAD

**Issue by trickydisco78** [angeloashmore/gatsby-source-prismic#135]
I have installed

```  
"gatsby-source-prismic": "^2.3.0-alpha.3",
    "gatsby-transformer-sharp": "^2.2.6",
 "gatsby-plugin-sharp": "^2.2.12",
    "gatsby-source-filesystem": "^2.1.20",
```

for some reason when i query a prismic image field i don't have the localFile node where i can use local childimage sharp stuff

I'm doing this for local files using plugin-filesystem and it works fine. How do i get this extra node so i can start using gatsby image?

**Comment by trickydisco78** [comment]
Yep. tried deleting .cache, public and reinstalling node_modules
It's weird as childImageSharp works on my local files

**Comment by stoutlabs** [comment]
I was having the same issue, and then I updated the `shouldNormalizeImage` function in the config options within `gatsby-config.js` to force it to return `true`.  e.g.:

```js
shouldNormalizeImage: ({ node, key, value }) => true 
```

(Note: the comments instructions above that line mention that it returns true by default, but perhaps it doesn't?)

**Comment by angeloashmore** [comment]
Based on other issues, it sounds like default options are not being set properly. `v3-beta.9` had some changes to the way plugin options were validated which affected default options. Thanks for reporting, I'll push out a fix.

**Comment by angeloashmore** [comment]
@trickydisco78 @stoutlabs Could both of you try out `v3.0.0-beta.11`? This should restore default options, including `shouldNormalizeImage = () => true`.

**Comment by stoutlabs** [comment]
Hi Angelo! I'm still getting errors unless I add in `return true` to `shouldNormalizeImage()` over here. (I updated to `3.0.0-beta.11`, nuked my `node_modules`, and ran `gatsby clean`  before running.)

```
index.js:73 Uncaught TypeError: Cannot read property 'src' of undefined
    at getImageSrcKey (index.js:73)
    at inImageCache (index.js:87)
    at new Image (index.js:307)
   ...
```

If I add in `return true` everything runs perfectly.

**Comment by angeloashmore** [comment]
@stoutlabs I know this was a while ago, but are you still experiencing this with the latest beta version, `v3.0.0-beta.14`?

**Comment by stoutlabs** [comment]
Hey @angeloashmore! I haven't tried the latest version, but I will make a point of upgrading later tonight or tomorrow. I'll let you know ASAP!

**Comment by stoutlabs** [comment]
Works great for me now, @angeloashmore! 🎉

**Comment by angeloashmore** [comment]
Cleaning up old issues. Please open a new issue if this is still present. Thanks!
