### ISSUE TITLE
v3 – no nodes for alternative languages after update to beta.10 

### ISSUE THREAD

**Issue by kossowski** [angeloashmore/gatsby-source-prismic#136]
## Version: 3.0.0-beta.10

I've updated the beta from **v.7** to latest **v.10** and there are no nodes for each language anymore. The query shows the `alternate_languages`, but there is just one node with all the content of the base language. 

### The new query looks like this:
```
{
  "data": {
    "allPrismicHomepage": {
      "edges": [
        {
          "node": {
            "lang": "de-de",
            "alternate_languages": [
              {
                "lang": "en-gb",
                "id": "XVPpgBEAACEAkI5p"
              }
            ],
            "id": "dbe6d0cb-aad5-555e-b482-e01703f51ea6"
          }
        }
      ],
      "totalCount": 1
    }
  }
}
```

### The old v.7 query was like this: 
```

{
  "data": {
    "allPrismicHomepage": {
      "edges": [
        {
          "node": {
            "lang": "de-de",
            "alternate_languages": [
              {
                "lang": "en-gb",
                "id": "XVPpgBEAACEAkI5p"
              }
            ],
            "id": "dbe6d0cb-aad5-555e-b482-e01703f51ea6"
          }
        },
        {
          "node": {
            "lang": "en-gb",
            "alternate_languages": [
              {
                "lang": "de-de",
                "id": "XQJBBxIAACAssngC"
              }
            ],
            "id": "f5835f9f-02dc-5e8c-8a11-a8fb99c24d98"
          }
        }
      ],
      "totalCount": 2
    }
  }
}
```
My problem is that I create pages for each node with different `lang` values and this doesn't work anymore. 
Is this a bug or is there a updated workflow to catch alternate languages to create pages?

**Comment by kossowski** [comment]
I fixed it by adding the `lang: '*'` value in the gatsby-config file. Closed.

**Comment by angeloashmore** [comment]
@kossowski Thanks, that sounds like the `lang: '*'` option isn't being set by default. Going to keep this open as a reminder to fix.

**Comment by angeloashmore** [comment]
@kossowski Could you try out `v3.0.0-beta.11` *without* the `lang` option? The default `lang: '*'` should be in place now.

**Comment by kossowski** [comment]
@angeloashmore It works for me, thank you!
