### ISSUE TITLE
UNHANDLED REJECTION Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "sub-categories" does not.

### ISSUE THREAD

**Issue by mduecker** [angeloashmore/gatsby-source-prismic#138]
The plugin doesn't seem to allow hyphens in API field IDs.

The following definition within my custom type causes an error:
```
    "sub-categories": {
      "type": "Group",
      "config": {
        "fields": {
          "sub-category": {
            "type": "Link",
            "config": {
              "select": "document",
              "customtypes": ["content_sub-category"],
              "label": "Sub-Category"
            }
          }
        },
        "label": "Sub-Categories"
      }
   }
```
>UNHANDLED REJECTION Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "sub-categories" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "sub-category" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "sub-categories" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "sub-category" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___link_type" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___isBroken" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___url" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___target" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___id" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___type" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___tags" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___lang" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___slug" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___uid" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___raw" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___name" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___kind" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___size" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___height" does not.
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "data___sub-categories___sub-category___width" does not.

**Comment by angeloashmore** [comment]
Hi @mduecker, correct, hyphens in API IDs are not supported since GraphQL fields must match `/^[_a-zA-Z][_a-zA-Z0-9]$/` (letters, underscores, numbers).

We could automatically convert IDs to snakecase but there may be implications with conflicting fields. For example, `my-field` and `my_field` would both become `my_field`, resulting in a conflict.

My best recommendation is to not use dashes in your IDs and stick to the `/^[_a-zA-Z][_a-zA-Z0-9]$/` regex.

**Comment by mduecker** [comment]
@angeloashmore  
Thank you.

It would be good to have this included in the documentation.

**Comment by angeloashmore** [comment]
No problem. I agree, we should add this to the documentation.

I'm going to leave this open as a reminder to do so. Thanks!

**Comment by angeloashmore** [comment]
@mduecker Added to the README here: https://github.com/angeloashmore/gatsby-source-prismic/tree/0be79841508c599eee8074b2db423d935b917168#graphql-valid-field-names

Thanks for bringing this up!
