### ISSUE TITLE
Cannot seem to properly pull data from Prismic

### ISSUE THREAD

**Issue by camsloanftc** [angeloashmore/gatsby-source-prismic#14]
I just updated to the latest version (0.1.3).

I get the following console output when I try to link my Prismic account using the plugin and run gatsby develop:

```
success delete html files from previous builds — 0.007 s
success open and validate gatsby-config.js — 0.005 s
success copy gatsby files — 0.022 s
⠁ Starting to fetch data from Prismic
⠁ source and transform nodesFetch Prismic data: 515.548ms
success source and transform nodes — 0.545 s
error Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "400" does not.


  Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "400" does not.
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.reduce
  
  - Array.forEach
```

**Comment by angeloashmore** [comment]
This looks to be a limitation of GraphQL. See: https://github.com/gatsbyjs/gatsby-starter-blog/issues/30

Do you have any Prismic documents named "400"?
Do you have any fields named "400" in your Prismic documents?

Wondering if it's an issue with this plugin or Gatsby/GraphQL.

**Comment by camsloanftc** [comment]
I don't have any Prismic documents called 400. My guess is that 400 is the error code being sent back from the server and GraphQL/Gatsby is attempting to read it as a key.

**Comment by camsloanftc** [comment]
I started up a new Prismic repo to test on and it appears to work with no issues.

I then went through my old Prismic repo (which was also a test account) and deleted posts and content types one by one, attempting to build the site each time. Then after deleting a few archived posts, it began working. It was strange. I have been trying to reproduce the issue on the new account but with no luck.

I think this was possibly a strange quirk with the way one of the schemas was built on that account, because that is the stage that it was getting stopped at in the gatsby develop script. It could also have something to do with the way a specific post was named.

Regardless, I think it is safe to say this issue can be closed. If I manage to recreate the issue, I will flag again and hopefully with more details.

**Comment by angeloashmore** [comment]
Ok, sounds like a plan. Sorry, I haven’t had time to investigate this, but let me know if it’s still an issue. :+1

**Comment by ryami333** [comment]
I still (sometimes) get the same error:
```
error Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6" does not.


  Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6" does not.
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.forEach
  

error Command failed with exit code 1.
```

I can't seem to reproduce it consistently, sometimes it happens, sometimes it doesn't.

**Comment by angeloashmore** [comment]
Ok, I'm going to reopen this issue as a reminder to revisit it. Sounds like @camsloanftc's thought is most likely correct — that prismic is returning that as an error (or some other unexpected return value), which then gets processed by the plugin and Gatsby.

I'll try to reproduce and see if we can come up with a solution.

**Comment by ryami333** [comment]
What is actually generating the "Names must match..." error? I've been digging around the source and dependencies and I can't find it yet.

**Comment by angeloashmore** [comment]
I think I linked to the wrong thing last time. 😄 

See this line in the `graphql` source
https://github.com/graphql/graphql-js/blob/6e7d51d6c8fb9ed66d93510fa49477a05dd751af/src/utilities/assertValidName.js#L56

I haven't looked where that function is called and what it is called with, but when Gatsby is creating the nodes (i.e. DocumentNodes for this plugin), a parameter is passed that fails that test.

**Comment by ryami333** [comment]
I have managed to narrow down the scope a tiny bit - it only fails on second or subsequent builds (ie. before gatsby has generated a `.cache` directory).

**Comment by thetre97** [comment]
I found I got this error when I created a responsive view on an image - e.g I created a 80px by 80px view, which then gave this error in Gatsby - `Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "80" does not.`.

**Comment by angeloashmore** [comment]
Cleaning up old issues. Please open a new issue if this is still present. Thanks!
