### ISSUE TITLE
V3: Unknown field 'html'

### ISSUE THREAD

**Issue by franksmithv** [angeloashmore/gatsby-source-prismic#140]
After upgrading to V3 all graphQL nodes with rich text fields are missing 'html' and 'raw' fields. Any ideas on why those fields wouldn't get created with the node?

Unknown field 'html' on type

"gatsby": "^2.15.28"
"react": "^16.10.0"
"gatsby-source-prismic": "^3.0.0-beta.11" (also had same issue on beta.9)

**Comment by angeloashmore** [comment]
Hi @franksmithv, did you provide schemas to the plugin? V3 needs to know the types of all fields in order to automatically transform Rich Text fields to HTML.

Here's the relevant section of the v2 to v3 migration guide: https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/docs/migrating-from-v2-to-v3.md#provide-custom-type-schemas

**Comment by franksmithv** [comment]
Hello @angeloashmore, I did provide all of the schemas for the custom types in the site. I made sure to follow the upgrade guide to update everything needed. Originally I was getting query issues with the slices but after resolving those, all of my previous queries on rich text fields can't find html, or raw fields. Which I would assume means the HTML serializer is not running during the creation of the nodes. Right now they are just arrays of the elements in the rich text fields.

**Comment by franksmithv** [comment]
It looks like I forgot to add 2 of my schemas to the config which looks like it has resolved the issues I was having.

**Comment by angeloashmore** [comment]
Glad you got it working! I have yet to write up a proper roadmap, but improving the developer experience is planned. It would be nice for the plugin to tell you when it detects a missing or outdated schema to avoid issues such as this.
