### ISSUE TITLE
How to debug the build process? Getting stuck on "write out type paths"

### ISSUE THREAD

**Issue by mduecker** [angeloashmore/gatsby-source-prismic#143]
I have a larger number of Prismic documents with different types. It happens quiet frequently that my build process (started with `gatsby develop`) gets stuck on this step for a document:

```
verbose gatsby-source-prismic - creating node
⠋ source and transform nodes
⠏ gatsby-source-prismic - create nodes
⠏ gatsby-source-prismic - write out type paths
```

I would like to dig deeper and see what's going on. How can I debug the process?

**Comment by angeloashmore** [comment]
Hi @mduecker, this is likely related to `gatsby-source-filesystem`. Images/media from Prismic are downloaded to your local computer via `gatsby-source-filesystem`, but there is currently a bug with concurrent downloads.

See this issue for more information: https://github.com/gatsbyjs/gatsby/issues/14173

Until that is resolved, you can set the `GATSBY_CONCURRENT_DOWNLOAD` environment variable to something like `10` (default: `200`).

Here are the official Gatsby docs on setting environment variables: https://www.gatsbyjs.org/docs/environment-variables/#server-side-nodejs

**Comment by angeloashmore** [comment]
Closing this but feel free to reply if this is still an issue. Thanks!
