### ISSUE TITLE
Conflict with Gatsby-source-prismic-graphql

### ISSUE THREAD

**Issue by michaeljblum** [angeloashmore/gatsby-source-prismic#146]
I was working with gatsby-source-prismic-graphql in my project at first, but then switched to gatsby-source-prismic, whereupon the latter was broken - I was unable to query (and I was using the correct syntax - checked against another project where I had only gatsby-source-prismic installed and it was working fine).

Annoying problem, unsure if it's known. But probably something to be remedied as these two packages will probably be installed in succession by people trying out various methods of sourcing from Prismic.

**Comment by angeloashmore** [comment]
Hi @michaeljblum, could you provide more details about the error?
