### ISSUE TITLE
Unable to query allPrismicProject by tags

### ISSUE THREAD

**Issue by michaeljblum** [angeloashmore/gatsby-source-prismic#149]
According to Prismic documentation and in the Prismic GraphQL playground, you're able to query all items of a given content type by "tags". Like this (note I'm changing the syntax slightly from the gatsby-source-prismic allPrismicProject to generic allProjects):

```
query {
  allProjects (tags:"Machine Learning") {
    edges {
      node {
        title
      }
    }
  }
}
```
I am no longer able to do this with using gatsby-source-prismic however. It throws an error (unknown argument "tags" on field allPrismicProject of type "query").

Has anyone managed to get around this and query by specific tag?

_(Edit: I'll also note that you **CAN** filter tags when querying just a single item, so prismicProject (tags : ...) works fine but allPrismicProject (tags: ...) does not. Any chance this feature could be added? It exists in the standard version accessible in Prismic's graphQL playground)_

**Comment by angeloashmore** [comment]
Hi @michaeljblum, you can filter by tags using something like this:

```graphql
query {
  allPrismicProjects(filter: { tags: { in: 'Machine Learning' } }) {
    nodes {
      # Your node fields here
    }
  }
}
```

Note that the GraphQL interface provided within Gatsby is *not* the same as Prismic's GraphQL API. This plugin downloads all content from Prismic and creates a Gatsby-specific GraphQL interface for better developer ergonomics (IMO of course).

I would recommend exploring the GraphiQL browser within your Gatsby development environment to learn the different filters and arguments.

Let me know if you run into other issues! 👍

**Comment by michaeljblum** [comment]
Thanks so much, this works perfect! I am aware that the Prismic GraphQL api and the one I'm working with in Gatsby are not the same, and have been primarily working with the one you link to in local host, but was just referencing the Prismic environment to double check that it ever was possible at all to filter allContentType by tag in the first place.

**Comment by michaeljblum** [comment]
Pretty sure this isn't a problem with gatsby-source-prismic, so feel free to ignore if it's just my own inexperience with deeply nested data structures in JS, but I'm trying to get data out of a content relation field in one of my content types. I have the query set up exactly as you suggest in the readme, and am ostensibly querying the data perfectly fine, but I'm unable to access it in Javascript. Just too deeply nested in a couple levels of arrays of objects. 

Is there a helper function commonly used in this scenario (vanilla JS or Lodash), or a method in graphql that makes this process easier?

**Comment by michaeljblum** [comment]
One more question along similar lines - I'm currently unable to query for "similar" documents like this:

```
   query{
   allBlog_posts(similar:{ documentId:"W45YDyEAAD42GS9s", max:30 }){
   totalCount
   edges{
   node{
   title
   main_image
   }
   }
   }
   }
```
(Taken from this Prismic docs on [querying similar documents](https://prismic.io/docs/graphql/query-the-api/query-similar-documents).)

How might one accomplish this using gatsby-source-prismic? Thanks so much for your help

**Comment by angeloashmore** [comment]
Hey @michaeljblum, glad to hear it's working!

I saw your previous comment about mapping over linked documents but didn't get a chance to respond earlier.

I typically do something like this:

```jsx
const projects = data.myPrismicDocument.data.projects.map(x => x.document[0])

<ul>
  {projects.map(project => (
    <li>
      <h2>Name: {project.data.title.text}</h2>
      <p>UID: {project.uid}</p>
    </li>
  ))}
</ul>
```

If you try out the V3 beta, you can remove the `[0]`. That was a bit of a necessary hack before Gatsby allowed modifying the internal schema.
