### ISSUE TITLE
Querying Similar Documents with gatsby-source-prismic

### ISSUE THREAD

**Issue by michaeljblum** [angeloashmore/gatsby-source-prismic#150]
One more question along similar lines as my last question regarding querying allPrismicProject by tag — I'm currently unable to query for "similar" documents like this:

```
   query{
   allBlog_posts(similar: { documentId: "W45YDyEAAD42GS9s", max: 30 }){
   totalCount
   edges{
   node{
   title
   main_image
   }
   }
   }
   }
```

(Taken from this Prismic docs on [querying similar documents](https://prismic.io/docs/graphql/query-the-api/query-similar-documents).)

How might one accomplish this using gatsby-source-prismic? Thanks so much for your help

**Comment by angeloashmore** [comment]
Interesting, I didn't realize Prismic provided a way to find similar documents. There currently is no built-in method to querying similar nodes within the Gatsby plugin.

On a per-project basis, this could be accomplished in `gatsby-node`. One possible approach is to create a search index using something like Lunr and performing a search against it.

This plugin is targeted toward providing a search index for the browser, but you could use it in Node as well: https://github.com/angeloashmore/gatsby-plugin-local-search

**Comment by michaeljblum** [comment]
Hmm... I'll definitely look into gatsby-plugin-local-search. 

Since it doesn't seem like I can use the "similar: ..." filtering, what I'd like to do is the following:

I have "post" custom type. Inside of my "posts", I have a reference to a group of "category" custom types. I'm querying my "post" custom type in my template file to create pages for all of my posts just fine. But what I'd like to do is query my "post", find which "category" it belongs to, and then find all the OTHER posts that ALSO have share any of those categories.

Is this something that the gatsby-plugin-local search would work well for, or am I overlooking a far easier method of achieving this? Thank you so much for your guidance!

(What I'm struggling with is that my "categories" themselves don't contain reference to project, only my projects contain reference to categories.)

**Comment by michaeljblum** [comment]
I thought I might ask here, also, since this might moreso be something Prismic is responsible for, not so much this plugin, but do you know if it's possible to use inline images inside of Rich Text with gatsby-image? I'm sourcing ordinary images from Prismic and using them with gatsby-image just fine (localFile.childImageSharp... etc). But am finding it impossible to do the same with inline images from Rich Text...

**Comment by tiste** [comment]
Hello @angeloashmore. Thanks again for the work you provide to us.

Is there any way to use that kind of query (e.g. similar) from `gatsby-source-prismic`?
I don't really get the difference between the graphql generated from this lib, and the graphql documentation from Prismic. For instance, how can I do "where" queries?

Thanks.
