### ISSUE TITLE
Could not find a declaration file for module 'gatsby-source-prismic'. implicitly has an 'any' type.

### ISSUE THREAD

**Issue by chapster11** [angeloashmore/gatsby-source-prismic#151]
When importing methods from **gatsby-source-prismic** i'm getting the below types warning. 
`import { usePrismicPreview } from 'gatsby-source-prismic';`

> Could not find a declaration file for module 'gatsby-source-prismic'. '/myProject/node_modules/gatsby-source-prismic/index.cjs.js' implicitly has an 'any' type.
>   Try `npm install @types/gatsby-source-prismic` if it exists or add a new declaration (.d.ts) file containing `declare module 'gatsby-source-prismic';`ts(7016)

Ive tried doing the npm install of the @type but then I get this error. 

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fgatsby-source-prismic: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/myProject/clearme-client/yarn-error.log".
```
@angeloashmore might want to add this file to the prod build of V3. Hope this helps in your beta testing. 

1. When do you think this plugin will be out of Beta ? 
2. What version do you think is the safest to use live right now ?

I'm currently using.
 `"gatsby-source-prismic": "^3.0.0-beta.11"`
for testing but haven't pushed it live but would like to move ahead. 

Took me a while to get all the schemas working but loving them once I did. Love the fact you solved the dummy content issue that has been around for a long time with Prismic and Gatsby. Nice work!!!

**Comment by chapster11** [comment]
Thanks @angeloashmore, Yes thats what I thought. I'd love to help but I don't think i'd feel comfortable doing typescript declaration files. In saying that, I'll take a look at some examples out there.

Sounds great i'll go ahead and plan to use 3.0.0-beta.11 and update as needed. 

I found a bug today that was already reported a month ago by @jaredloson
[#139](https://github.com/angeloashmore/gatsby-source-prismic/issues/139)
jaredloson already outlined a fix that does in fact work. Basically what is needed is a check for node object before its used. See ticket for example from jaredloson.

[#139](https://github.com/angeloashmore/gatsby-source-prismic/issues/139) is the last bug holding us up from been able to fully test Preview and release our project using V3.

**Comment by angeloashmore** [comment]
The plugin has been rewritten in TypeScript as of `v3.0.0` so you should have types now.
