### ISSUE TITLE
V3 - Error when a field name has a hyphen

### ISSUE THREAD

**Issue by hazem3500** [angeloashmore/gatsby-source-prismic#153]
**3.0.0-beta.11**

when running `gatsby develop`

`Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "details-title" does not.`

**Comment by angeloashmore** [comment]
Hi @hazem3500, this is a GraphQL limitation. Field names must match that regex.

See this issue for more details: https://github.com/angeloashmore/gatsby-source-prismic/issues/138#issuecomment-533342560

This section of the README describes the limitation as well: https://github.com/angeloashmore/gatsby-source-prismic/blob/dce953ba3b8cb95f2e1fd7eda1ccf300ffd17f95/README.md#graphql-valid-field-names

Definitely open to suggestions if you have any thoughts on how to approach this differently.
