### ISSUE TITLE
Rich Text Field conflicting data types

### ISSUE THREAD

**Issue by heart-of-code** [angeloashmore/gatsby-source-prismic#154]
Reproduce:
> create a custom repeatable type in Prismic.io
> create a Rich Text Field
> create two instances of the repeatable type
> in one of them: embed an image first followed by text in the rich text field
> in the other: enter text first followed by an image if you want

Expected Result:
> data type is: ``{ html: "some really long string <img src='/with/images/too' />" }``

Actual Result:
> when image is the first thing entered into the rich text field the object is returned as an array
> when text is the first thing entered into the rich text field the object is returned as ``{ html: 'string' }``
> because there are two different data types being returned we receive an error from graphql: ``"There are conflicting field types in your data. GraphQL schema will omit those fields."``

**Comment by rubas** [comment]
Duplicate #53. Fixed in v3.

**Comment by heart-of-code** [comment]
oh, thank you!
