### ISSUE TITLE
Cannot query field "html" on type "PrismicPostDataContent"

### ISSUE THREAD

**Issue by joakimgrr** [angeloashmore/gatsby-source-prismic#163]
gatsby-source-prismic version: 2.3.0-alpha.3
gatsby version: 2.17.4

I have a custom type in Prismic that has a Rich Text Field type.

If in this field I have text and images it works perfectly _unless_ the inserted image is the first thing in the field. So if I have any text before it, it works, otherwise, the build fails with Cannot query field "html" on type "PrismicPostDataContent" - error.

I apologize if there are existing issues, I tried looking for information about the subject, but couldn't.

**Comment by angeloashmore** [comment]
Hi @joakimgrr, no worries, I know it can be difficult to find issues.

This is a known limitation of v2 of the plugin. It tries to determine a field’s type using its contents, but it is not always correct.

V3, on the other hand, uses your custom type schemas from Prismic to assign a type to a field. You will need to provide the JSON version of your schema which can be grabbed from Prismic. V3 is in beta now so I recommend giving it a try if you’re able to.

Migration guide: https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/docs/migrating-from-v2-to-v3.md
V3 docs: https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/README.md
