### ISSUE TITLE
No spans field on Rich Text fields

### ISSUE THREAD

**Issue by antonbehaeghe** [angeloashmore/gatsby-source-prismic#17]

**Comment by angeloashmore** [comment]
Hi @antonbehaeghe, sorry for the late reply. Could you describe the issue?

**Comment by MarijnBrosens** [comment]
I believe i have the same issue: 
When spans gives back an empty array, it's not possible to query it

> data

`
type: "StructuredText"
--value: [
--{
type: "paragraph"
text: "some text"
spans: [ ]
}
]
}
`

> you can do

`
team_content {
              type
              text
            }
`

> you can't do:

`
team_content {
              type
              text
              spans {
                start
                end
                type
              }
            }
`

But this should be possible

**Comment by angeloashmore** [comment]
I finally understand what this issue is. In the Prismic API V2 response, a RichText field contains data like the following:

```json
{
  // ...
  data: {
    myRichTextField: [
    ]
  }
  // ...
}
```

**Comment by angeloashmore** [comment]
I've opened an issue for `prismic-richtext` regarding this: https://github.com/prismicio/prismic-richtext/issues/10

**Comment by arnaudlewis** [comment]
Hi @angeloashmore, So it's more like an issue on Gatsby I guess. It doesn't feel right to just remove data from the API Response. I don't think that should be fix in the prismic library.

**Comment by angeloashmore** [comment]
Closing in favor or #24 (providing HTML and text fields as part of the plugin).
