### ISSUE TITLE
Can't filter by content relationship

### ISSUE THREAD

**Issue by wlei6277** [angeloashmore/gatsby-source-prismic#172]
Hi i'm building a blog and need to have index pages of blogs belonging to specific categories - to enable the user to categorise each blog i've setup a content relationship field on the blog custom type as per the instructions in the link below:

https://user-guides.prismic.io/en/articles/2033431-create-a-custom-tagging-system

My issue is that I can't figure out how to query for the linked blog posts relating to a given category. I can access the parent data of linked categories (e.g. the name of the category and related content) on the blog post object but this isn't what I need, rather I need some way of getting all of the blog posts which have been linked to a given category. That way on each category index page I only need to fetch blog posts relevant to that category (will also help me to paginate the graphql way). 

If I try and filter the blog posts by the nested category uid then my local server crashes with the following error message: '**UNHANDLED REJECTION Cannot read property 'key' of undefined**'

![image](https://user-images.githubusercontent.com/29637222/69936757-d8e74180-152c-11ea-8591-fadf6288d43c.png)

![image](https://user-images.githubusercontent.com/29637222/69936817-0502c280-152d-11ea-86f1-57be2427f764.png)

Any suggestions/ workarounds for this issue would be greatly appreciated. 

Thanks :)

**Comment by BrendanWolfe** [comment]
I am using the v3 beta and am having this problem as well.

- I have two custom types: blog_post and person.
- I have a linked field called author on blog_post to link a person.
- I am able to get the author that is linked to any given blog post just fine.
- **I am unable to get all the blog posts that are linked to any given author though.**

Please let me know if this is something I am doing wrong or if this is a bug and if there are any solutions yet.

Thank You!

**Here is my query:**
```
allPrismicBlogPost( filter: { data: { author: { uid: { eq: $uid } } } } ) {
    edges {
        node {
            uid
            data {
                title {
                    text
                }
                content {
                    html
                }
            }
        }
    }
}
```

**Here is the output:**
```
UNHANDLED REJECTION Cannot read property 'key' of undefined

  TypeError: Cannot read property 'key' of undefined
  
  - gatsby-node.js:275 Object.resolve
    [react-gatsby-prismic]/[gatsby-source-prismic]/dist/gatsby-node.js:275:33
  
  - node-model.js:525 resolveField
    [react-gatsby-prismic]/[gatsby]/dist/schema/node-model.js:525:19
  
  - node-model.js:496 resolveRecursive
    [react-gatsby-prismic]/[gatsby]/dist/schema/node-model.js:496:26
  
  - node-model.js:503 resolveRecursive
    [react-gatsby-prismic]/[gatsby]/dist/schema/node-model.js:503:28
  
  - node-model.js:253 nodeStore.saveResolvedNodes
    [react-gatsby-prismic]/[gatsby]/dist/schema/node-model.js:253:38
  
  - nodes.js:104 Object.exports.saveResolvedNodes
    [react-gatsby-prismic]/[gatsby]/dist/redux/nodes.js:104:32
  
  - node-model.js:251 LocalNodeModel._doResolvePrepareNodesQueue
    [react-gatsby-prismic]/[gatsby]/dist/schema/node-model.js:251:28
  
  - node-model.js:216 process.nextTick
    [react-gatsby-prismic]/[gatsby]/dist/schema/node-model.js:216:22
  
  - next_tick.js:61 process._tickCallback
    internal/process/next_tick.js:61:11
```

**Comment by keepyourreceipt** [comment]
Hey guys, I'm having this same exact issue. 

I have a custom type for blog posts and another custom type for categories. My blog posts relate to a category with a content relationship field in Prismic. All is fine until I try to execute a query that includes a filter on the category relationship field.

That first error (prismic-source-prototype]/[gatsby-source-prismic]/dist/gatsby-node.js:275:33): it looks like the switch is matching to the type of "Link." I'm not sure how this plugin is structured, but I'm wondering if this is expecting a link field instead of a relationship field and is attempting to access something that's not available on the relationship type. Just a thought.

Regardless, I would very much appreciate any help in resolving this issue. Working on my first Gatsby Prismic project and this has been the only real issue so far.

Node: v12.13.0
Yarn: 1.13.0

Package.json file:
"babel-plugin-styled-components": "^1.10.6",
    "dotenv": "^8.2.0",
    "gatsby": "^2.17.11",
    "gatsby-image": "^2.2.31",
    "gatsby-plugin-manifest": "^2.2.27",
    "gatsby-plugin-offline": "^3.0.19",
    "gatsby-plugin-react-helmet": "^3.1.14",
    "gatsby-plugin-sharp": "^2.2.37",
    "gatsby-plugin-styled-components": "^3.1.14",
    "gatsby-source-filesystem": "^2.1.36",
    "gatsby-source-prismic": "^3.0.0-beta.17",
    "gatsby-transformer-sharp": "^2.3.3",
    "graphql-tools": "^4.0.6",
    "prismic-javascript": "^2.1.1",
    "prismic-reactjs": "^1.1.1",
    "prop-types": "^15.7.2",
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
    "react-helmet": "^5.2.1",
    "styled-components": "^4.4.1",
    "typescript": "^3.7.2"

Thanks!

**Comment by mduecker** [comment]
Running into the same problem when trying to filter my articles by category.

We're running
Node: v12.13.0

"gatsby": "2.17.6",
"gatsby-source-prismic": "^3.0.0-beta.17",

**Comment by giacomoalonzi** [comment]
Same here

```graphql
 allPrismicSecondLevelCategories(filter: {data: {category_parent: {id: {eq: $id}}}}) {
       edges {
         node {
           prismicId
           uid
           data {
             name {
               text
             }
             category_parent {
               id
             }
           }
         }
       }
     }
```

things like this aren't working at all :\ 

any help?

**Comment by ikisoft** [comment]
Same issue here. Looks like the filtering just doesn't work in ^3.0.0-beta.19.

**Comment by Sirk** [comment]
Got exactly the same issue here! It's a shame knowing that the whole plugin works wonderfully well. Tried to get a little into this one but didn't manage to fix it 😅.

If anyone else managed a workaround or a fix please let us know 😊

**Comment by Sirk** [comment]
Update here!
I forgot one schema in the `schemas` definitions object in `gatsby-config.js`. And was trying to filter on this type of field. Re-add schema fixes the issue.

If it can help someone!

using `"gatsby-source-prismic": "3.0.0-beta.19"`

**Comment by giacomoalonzi** [comment]
> Update here!
> I forgot one schema in the `schemas` definitions object in `gatsby-config.js`. And was trying to filter on this type of field. Add schema fixes the issue.
> 
> If it can help someone!
> 
> using `"gatsby-source-prismic": "3.0.0-beta.19"`

I have all schemas but it doesn't work anyway! :\

**Comment by angeloashmore** [comment]
Hi everyone, could you try out the latest beta, `v3.0.0-beta.24`?

I did not get a chance to research this issue on the older beta, but I'm able to filter queries by content relationship fields successfully on beta 24.

For example:

```graphql
query {
  allPrismicPage(filter: {data: {parent: {id: {eq: "XeF8nBEAAGfJMISb"}}}}) {
    nodes {
      id
      data {
        parent {
          id
        }
      }
    }
  }
}
```

Result:

```json
{
  "data": {
    "allPrismicPage": {
      "nodes": [
        {
          "id": "578e4e1b-e89c-5a89-9d35-24b7a5e643f6",
          "data": {
            "parent": {
              "id": "XeF8nBEAAGfJMISb"
            }
          }
        },
        {
          "id": "30c0a271-0df4-5cac-a1b7-e93d82daf27d",
          "data": {
            "parent": {
              "id": "XeF8nBEAAGfJMISb"
            }
          }
        },
        {
          "id": "935c7c58-cbd2-50f8-9c60-26982933c0b0",
          "data": {
            "parent": {
              "id": "XeF8nBEAAGfJMISb"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by giacomoalonzi** [comment]
Hi @angeloashmore I just tried to install the b24 but in a query like this:


```
allPrismicSecondLevelCategories(filter: {data: {category_parent: {id: {eq: "XOWwcxAAAL8uEZsw"}}}}) {
      edges {
        node {
          prismicId
          uid
          data {
            name {
              text
            }
            category_parent {
              id
            }
          }
        }
      }
    }
```
I got

```
UNHANDLED REJECTION Cannot read property 'key' of undefined
TypeError: Cannot read property 'key' of undefined
```

On GraphiQl instead, I got:

```
{
  "message": "Failed to fetch",
  "stack": "TypeError: Failed to fetch"
}
```

🤔

**Comment by mduecker** [comment]
> Running into the same problem when trying to filter my articles by category.

@angeloashmore It now works for my use case mentioned above. Thank you very much for the update! :)

**Comment by giacomoalonzi** [comment]
> > Running into the same problem when trying to filter my articles by category.
> 
> @angeloashmore It now works for my use case mentioned above. Thank you very much for the update! 🙂

Sounds good, I'm still having the issue :\

**Comment by giacomoalonzi** [comment]
Good news, I reinstalled all the node_modules and now it works!!!! 🏄‍♀️

**Comment by angeloashmore** [comment]
@giacomoalonzi That's awesome to hear! Thanks for the update.

I'm going to close this issue, but if anyone else is still experiencing this, please post here and we can reopen it.

**Comment by platformalist** [comment]
@angeloashmore This problem seems to have resurrected on Beta 25 for me, but swapping to Beta 24 seemed to resolve it!
