### ISSUE TITLE
v3 - alternate_languages with schema

### ISSUE THREAD

**Issue by rubas** [angeloashmore/gatsby-source-prismic#173]
# Problem 
As soon as I add a custom type scheme from Prismic for a type, I loose the field  `alternate_languages` of that type.

# Details

> In v3, providing custom type schemas to the plugin is required. This tells Gatsby exactly which custom types and fields are available and their types even if they are empty in Prismic.

> 1. Copy the JSON schema from Prismic for each custom type into your project. src/schemas/<custom_type_id>.json is the recommended location.

[Link](https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/docs/migrating-from-v2-to-v3.md#provide-custom-type-schemas)

The default JSON export of a type in the Prismic editor does *not* contain information about  `alternate_languages`.

**Comment by angeloashmore** [comment]
@rubas Could you try out `v3.0.0-beta.19`?

Details are here: https://github.com/angeloashmore/gatsby-source-prismic/pull/181

**Comment by rubas** [comment]
`v3.0.0-beta.19` fixes it. Thank you ❤️

**Comment by grumpyoldman-io** [comment]
although this is closed I am still not seeing the `alternate_languages` on version `^3.0.0-beta.19`. Any idea how I can validate this is not an error on my side?

**Comment by rubas** [comment]
It is `v3.0.0...` not `3.0...`.
