### ISSUE TITLE
Feature request: crop option for GatsbyPrismicImage

### ISSUE THREAD

**Issue by steverandy** [angeloashmore/gatsby-source-prismic#175]
Is it possible to add `crop`, `height`, and `maxHeight` options and pass it to the Imgix urls?

**Comment by rubas** [comment]
Current workaround is to use `image.url`, create your "own" Imgix url (and pass your object to `gatsby-image.Image`).

**Comment by angeloashmore** [comment]
This somewhat supported in `v3.1`. You can provide any valid Imgix URL parameter to a URL, including cropping via `rect`.

`imageImgixParams` and `imagePlaceholderImgixParams` are available as plugin options. The examples listed in the README's sample `gatsby-config.js` are the defaults.

You may also provide `imgixParams` or `placeholderImgixParams` as arguments to an individual image in your query.
