### ISSUE TITLE
maxWidth not working for imgix gatsby-image integration?

### ISSUE THREAD

**Issue by mduecker** [angeloashmore/gatsby-source-prismic#177]
First of all, thank very much for implementing the new Image Optimization with imgix!  🎉

I just upgraded to gatsby-source-prismic v.3.0.0-beta.18 and started using the new imgix transformation like this:
```
        header_img {
          fluid(maxWidth: 1920) {
            ...GatsbyPrismicImageFluid_noBase64
          }
        }
```
Unfortunately it doesn't seem to respect the `maxWidth` option because the resulting srcSet contains urls for widths up to 3840px:
...image.jpg?w=480&fit=max&q=50&auto=compress%2Cformat 480w
...image.jpg?w=960&fit=max&q=50&auto=compress%2Cformat 960w
...image.jpg?w=1920&fit=max&q=50&auto=compress%2Cformat 1920w
...image.jpg?w=2880&fit=max&q=50&auto=compress%2Cformat 2880w
...image.jpg?w=3840&fit=max&q=50&auto=compress%2Cformat 3840w

**Edit:**
I downloaded the 1920w, 2880w and 3840w image and realized they are all 1920px wide and the same size. I guess that solves my question.

**Comment by angeloashmore** [comment]
Hi @mduecker, this is intended behavior for HiDPI displays and mimics the functionality of the official `gatsby-image`-compatible source/transformer plugins.

https://github.com/angeloashmore/gatsby-source-prismic/blob/35cd707bea698beb6cbb92088fe8b8d0691ca360/src/common/getGatsbyImage.js#L10-L12

You can adjust the breakpoints by providing a `srcSetBreakpoints` parameter. See this for details: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/README.md#fluid
