### ISSUE TITLE
v3 - LocalFile, StructuredText, Slices data returning null

### ISSUE THREAD

**Issue by TatsumiSuenaga** [angeloashmore/gatsby-source-prismic#179]
Hey @angeloashmore
Seems like we are getting issues when we upgraded from `2.3.0-alpha.6` to `3.0.0-beta.18`. 
Here are our relevant dependencies:
```
    "gatsby": "^2.5.0",
    "gatsby-image": "^2.0.29",
    "gatsby-plugin-sharp": "^2.0.20",
    "gatsby-source-filesystem": "^2.0.20",
    "gatsby-source-prismic": "^3.0.0-beta.18",
    "gatsby-transformer-sharp": "^2.1.13",
    "react": "^16.8.0",
    "react-dom": "^16.8.0"
``` 
and the gatsby-config.json
```
  {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: '<REPO-NAME>',
        accessToken: `<ACCESS-TOKEN>`,
        linkResolver: () => (post) => `/${post.slug}`,
        htmlSerializer: () => (type, element, content, children) => {},
        schemas: {
          examplePage: require('./src/schemas/example-page.json')
          ...
        },
        lang: '*',
        shouldDownloadImage: () => true
      }
    },
```

When we try the following
```
{
  ...
  imageFieldName {
     localFile {
      childImageSharp {
        fluid(maxWidth: 750, quality: 80) {
          ...GatsbyImageSharpFluid_withWebp
         }
       }
     }
   }
}
```
We see this type error `TypeError: Cannot read property 'childImageSharp' of null` as localFile is null. Also, not only is localFile, our other fields return as null. However, when I check the raw data from GraphQL, we can see that the fields exist (but we still do not see localFile).

We have tried reverting the `gatsby-source-prismic` plugin to various v3 versions and we see the issue. We have also updated the gatsby plugin versions, but we still see the same issue. Finally we've tried `gatsby clean` and deleting and reinstalling `node_modules`

**Comment by TatsumiSuenaga** [comment]
related to #161 
#135

**Comment by angeloashmore** [comment]
Hi @TatsumiSuenaga, thank you for reporting this issue. I'm going to close this one in favor of #161, but please feel free to add to that issue if you have more to share.

If you're able to share a JSON schema of the custom type that is failing, I can test it out.
