### ISSUE TITLE
Specifying fields for slices

### ISSUE THREAD

**Issue by AdamPflug** [angeloashmore/gatsby-source-prismic#18]
Hey, I am trying to figure out how to query for fields in slices so I can handle their structures appropriately depending on the slice type, but I can't figure it out. I think I want to do something like this:

```graphql
{
  allPrismicDocument {
    edges {
      node {
        id
        type
        data {
          title {
            type
            text
          }
          body {
            slice_type
            ... on carousel_section {
              value {
                caption
                photo {
                  url
                } 
              }
            }
            ... on copy_section {
              text
            }
          }
        }
      }
    }
  }
}
```

.. but that's not working. I am not sure if this is a gatsby issue, gatsby-source-prismic issue, or just an area where I don't know what I'm doing with graphql.  Can you help me?

**Comment by angeloashmore** [comment]
Are you able to perform a query like the following?

```graphql
{
  allPrismicDocument {
    edges {
      node {
        id
        data {
          title {
            type
            text
          }
          body {
            slice_type
            primary {
              text {
                type
                text
              }
            }
          }
        }
      }
    }
  }
}
```

Where you have `... on carousel_section`, you should be able to use `primary` to query the fields within. You could setup a GraphQL fragment if you want to keep the list of fields out of the query.

**Comment by angeloashmore** [comment]
Hey @AdamPflug, I'm going to close this for now to keep track of issues. Please re-open or comment if this is still an issue. I'm happy to help if the above reply doesn't work.
