### ISSUE TITLE
v3: [Feature Request] configurable lqip images for lazyloading with Imgix

### ISSUE THREAD

**Issue by rubas** [angeloashmore/gatsby-source-prismic#184]
Imgix is awesome. We should use it more.

# Proposal
Let's make the [default settings](https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/src/common/getGatsbyImage.js#L64) for the  the low quality image placeholder (LQIP) configurable by `gatby-config.json`.

The LQIP  are the first thing a visitors will see. Being able to customize those and reflect your branding is 🦄 .

---

Currently you [reduces](https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/src/common/getGatsbyImage.js#L64) the quality to `20` and add a blur of `15`.

Based on [imgix recommendation](https://blog.imgix.com/2016/06/01/lqip-your-images) we are using this technique on other projects to create super small images, that also *reflect the branding of the site*. 

Compared to just reducing the `quality` to `20`, I see 5x smaller images. Especially the `px`(pixelating) parameters reduces the image size dramatically.

Use their [sandbox](https://sandbox.imgix.com/view?url=https%3A%2F%2Fassets.imgix.net%2Funsplash%2Fjellyfish.jpg%3Fw%3D800%26h%3D400%26fit%3Dcrop%26crop%3Dentropy%26px%3D16%26blur%3D200%26auto%3Dformat) to play around.

We made the following parameter for lqip images configurable in our internal library (different stack).
- blur
- px
- colorquant
- duotone-alpha
- duotone
- ht
- monochrome
- sepia 

[Imgix Docs](https://docs.imgix.com/apis/url/stylize)
```
->integerNode('blur')->min(0)->max(2000)->defaultValue(200)->end()
->integerNode('px')->min(0)->max(2000)->defaultValue(16)->end()
->integerNode('colorquant')->min(2)->max(256)->defaultValue(256)->end()
->integerNode('duotone-alpha')->min(0)->max(100)->defaultValue(100)->end()
->arrayNode('duotone')->children()->scalarNode('color1')->isRequired()->cannotBeEmpty()->end()->scalarNode('color2')->isRequired()->cannotBeEmpty()->end()->end()->end()
->integerNode('ht')->min(0)->max(100)->defaultValue(0)->end()
->scalarNode('monochrome')->end()
->integerNode('sepia')->min(0)->max(100)->defaultValue(0)->end()
```

**Comment by angeloashmore** [comment]
This is part of the just published `v3.1.0`!

`imageImgixParams` and `imagePlaceholderImgixParams` are available as plugin options. The examples listed in the README's sample `gatsby-config.js` are the defaults.

You can override the parameters for all images, or just the placeholders, with any valid Imgix URL parameter.
