### ISSUE TITLE
beta.24 - Error: Unable to find plugin "gatsby-source-prismic"

### ISSUE THREAD

**Issue by mduecker** [angeloashmore/gatsby-source-prismic#189]
Hi Angelo,
thanks for releasing an update today and hopefully fixing the "filter by content relationship" problem.

Unfortunately I'm unable to run my Gatsby site with `v3.0.0-beta.24`

## What I did
`yarn add gatsby-source-prismic@3.0.0-beta.24`
`gatsby develop`

## The problem
Gatsby develop fails immediately with the following error message 
```
UNHANDLED REJECTION Unable to find plugin "gatsby-source-prismic". Perhaps you need to install its package?


  Error: Unable to find plugin "gatsby-source-prismic". Perhaps you need to install its package?
  
  - load.js:109 resolvePlugin
    [ts-gatsby]/[gatsby]/dist/bootstrap/load-plugins/load.js:109:11
  
  - load.js:153 processPlugin
    [ts-gatsby]/[gatsby]/dist/bootstrap/load-plugins/load.js:153:20
  
  - load.js:172 
    [ts-gatsby]/[gatsby]/dist/bootstrap/load-plugins/load.js:172:20
  
  - Array.forEach
  
  - load.js:171 module.exports
    [ts-gatsby]/[gatsby]/dist/bootstrap/load-plugins/load.js:171:20
  
  - index.js:55 module.exports
    [ts-gatsby]/[gatsby]/dist/bootstrap/load-plugins/index.js:55:19
  
  - index.js:167 module.exports
    [ts-gatsby]/[gatsby]/dist/bootstrap/index.js:167:34
  
  - develop.js:401 async module.exports
    [ts-gatsby]/[gatsby]/dist/commands/develop.js:401:7
```

## More Information
 System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 13.2.0 - ~/.nodenv/shims/node
    Yarn: 1.21.0 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nodenv/shims/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.87
    Safari: 13.0.4
  npmPackages:
    gatsby: 2.17.6 => 2.17.6
    gatsby-background-image: ^0.9.10 => 0.9.14
    gatsby-cli: ^2.8.18 => 2.8.29
    gatsby-image: 2.2.30 => 2.2.30
    gatsby-plugin-antd: 2.0.2 => 2.0.2
    gatsby-plugin-canonical-urls: ^2.1.10 => 2.1.20
    gatsby-plugin-exclude: 1.0.2 => 1.0.2
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-google-gtag: ^1.1.11 => 1.1.22
    gatsby-plugin-google-tagmanager: ^2.1.15 => 2.1.25
    gatsby-plugin-hotjar: 1.0.1 => 1.0.1
    gatsby-plugin-hubspot: ^1.3.3 => 1.3.3
    gatsby-plugin-less: 3.0.12 => 3.0.12
    gatsby-plugin-lodash: 3.1.13 => 3.1.13
    gatsby-plugin-manifest: 2.2.25 => 2.2.25
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-react-helmet: 3.1.13 => 3.1.13
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: 1.5.0 => 1.5.0
    gatsby-plugin-sentry: 1.0.1 => 1.0.1
    gatsby-plugin-sharp: 2.2.34 => 2.2.34
    gatsby-plugin-sitemap: 2.2.19 => 2.2.19
    gatsby-plugin-styled-components: 3.1.11 => 3.1.11
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8
    gatsby-source-airtable: 2.0.9 => 2.0.9
    gatsby-source-filesystem: 2.1.35 => 2.1.35
    gatsby-source-prismic: 3.0.0-beta.24 => 3.0.0-beta.24
    gatsby-transformer-json: 2.2.16 => 2.2.16
    gatsby-transformer-sharp: 2.3.1 => 2.3.1
  npmGlobalPackages:
    gatsby-cli: 2.8.16

**Comment by giacomoalonzi** [comment]
🤔 I changed the version inside the package.json and I ran `yarn`. All have worked perfectly

**Comment by angeloashmore** [comment]
@mduecker Could you try reinstalling your dependencies? I am not seeing this happen on my side.

```sh
yarn install --force
```

And if that doesn't work, could you try deleting your `node_modules` folder and reinstall?

Thanks!

**Comment by mduecker** [comment]
Still getting the same error. Neither `yarn install --force` nor deleting `node_modules` helped.

I can try to downgrade my node version

**Comment by mduecker** [comment]
Upgrading gatsby to 2.19.16 solved it for me.

**Comment by angeloashmore** [comment]
@mduecker Thanks for the update. I've been testing on the latest Gatsby version but we'll need to check what the oldest supported version is.

**Comment by amandakievet** [comment]
I'm having this same issue on a project that uses `"gatsby-source-wordpress": "^3.1.66",`. It seems to be working on all my other `gatsby` projects.
