### ISSUE TITLE
Source does not include spans for richtext

### ISSUE THREAD

**Issue by alexanderfountain** [angeloashmore/gatsby-source-prismic#190]
I see this was looked at in the past, but I'm getting the same error now.
https://github.com/angeloashmore/gatsby-source-prismic/issues/17

It looks like the empty spans array are still being removed?

I'm getting a can't map undefined error trying to render richtext field that lives in repeatable field on slice.

**Comment by angeloashmore** [comment]
Hi @alexanderfountain, the underlying Prismic library was updated to accept empty spans as seen in this issue from a while ago: https://github.com/prismicio/prismic-richtext/issues/10

It looks like the change wasn't merged in until September of last year, however.

https://github.com/prismicio/prismic-richtext/commit/8ee1b81846a39c0ce8e2307b9988c43e32d4cbab#diff-b7f4e39ec35851dff3973e58da2a8fd4

Using the `raw` field and its underlying fields are not supported by this plugin and are provided as a last resort if you need the raw data from Prismic. If you use the `v3` beta, this field is a JSON type, meaning you will get exactly what Prismic provides, which should include empty span arrays.

**Comment by angeloashmore** [comment]
I'm going to close this as I recommend upgrading to the v3 beta (which will be published as latest soon) or using the `html` field rather than `raw`.

Please let me know if you need help though!
