### ISSUE TITLE
v3: Cannot query field "width" on type "PrismicEmbedType"

### ISSUE THREAD

**Issue by kieranstartup** [angeloashmore/gatsby-source-prismic#191]
I'm running into issues querying the following fields when using the Embed Type:

```
width
height
video_id
```

I've been able to query for these fields on an Embed Type before, and can successfully query these fields on a project from last year running `3.0.0-beta.10`, however I've just created a new project and I'm running into errors when querying for this.

I've experienced it on a number of projects that I've started this year, and I've tested out a couple of different v3 builds. I just upgraded to `3.0.0-beta.24` to see if it would fix the issue but it hasn't.

Here's my graphql query:

```
{
  prismicHomepage {
    data {
      video_embed {
        embed_url
        width
        height
        video_id
      }
    }
  }
}
```

And here's what my homepage.json schema looks like:

```
{
  "Main": {
    "title": {
      "type": "StructuredText",
      "config": {
        "single": "heading1",
        "label": "Title"
      }
    },
    "video_embed": {
      "type": "Embed",
      "config": {
        "label": "Video Embed"
      }
    }
  }
}
```

I can see the data when I just query for:

```
{
  prismicHomepage {
    dataRaw
  }
}
```

But this doesn't feel like a proper solution. Do you have any ideas on whats causing this issue?

Thanks!

**Comment by angeloashmore** [comment]
Hi @kieranstartup, sorry for the late reply. Inferred GraphQL types were removed and it looks like a few fields were missed for embeds.

Could you try out `v3.0.0-beta.25`? I just pushed an update that includes the missing oEmbed fields such as `width` and `height`.

Thanks!

**Comment by kieranstartup** [comment]
Hey @angeloashmore, I've just updated to `v3.0.0-beta.25` and can confirm everything is working correctly. 

Thanks a lot, I appreciate it!
