### ISSUE TITLE
v3 seems to only access data on the 'main' tab

### ISSUE THREAD

**Issue by jenkshields** [angeloashmore/gatsby-source-prismic#192]
In all my content types, I have the default Main tab along with an SEO tab containing relevant fields. I've copied these schema (including the SEO tab) into the plugin via gatsby-config, but cannot find the SEO fields anywhere in GraphiQL.

In v2 this worked fine - the fields on the SEO tab were included in each node's data field. They are missing from this field in v3.

**Comment by jenkshields** [comment]
Sorry, this is an error on my end - they weren't defined in my interface.

**Comment by angeloashmore** [comment]
Ah sorry, I missed responding to this. Glad you figured it out!
