### ISSUE TITLE
URL decoding done incorrectly

### ISSUE THREAD

**Issue by jhodges10** [angeloashmore/gatsby-source-prismic#194]
My client's added an image with the name "Untitled+3.png" to Prismic and it completely broke my build, because the image that ends up being fetched has the URL decoded - but this character shouldn't be decoded!

**Works:**
https://images.prismic.io/kidsister/c36a15b8-9848-4484-82ad-79a23e66e070_Untitled%2B2.jpg

**Doesn't work:**
https://images.prismic.io/kidsister/c36a15b8-9848-4484-82ad-79a23e66e070_Untitled+2.jpg

**Comment by angeloashmore** [comment]
Hi @jhodges10, which version of the plugin are you using?

**Comment by angeloashmore** [comment]
`v3.0.0-beta.25` was just published that removes URL decoding. Could you give that a try and let me know if you're still experiencing the issue?

Thanks!
