### ISSUE TITLE
Support type "Boolean"

### ISSUE THREAD

**Issue by apdrsn** [angeloashmore/gatsby-source-prismic#198]
Hi :)
And thanks for this very useful plugin.
Do you plan on adding the type "Boolean"?
https://prismic.io/blog/prismic-boolean-fields

Right now when using it I'm getting:

```shell
Error: Cannot get field 'show_as_button' from type 'PrismicGlobalElementsBodyNavigationItemPrimaryType'. Field does not exist.
```
This is how the schema for that type looks like:

```
"show_as_button" : {
  "type" : "Boolean",
  "config" : {
    "placeholder_false" : "Yes",
    "placeholder_true" : "No",
    "default_value" : true,
    "label" : "Show as button"
  }
}
```

**Comment by angeloashmore** [comment]
Hi @apdrsn, `v3.0.0` was just published and includes support for Boolean.

It looks like you might not be on latest version so here's a migration guide: https://github.com/angeloashmore/gatsby-source-prismic/blob/95b85688a58efc5cb5cbf78628b6f43eb6cdaa96/docs/migrating-from-v2-to-v3.md

**Comment by apdrsn** [comment]
Hi @angeloashmore 
I was using 3.0.0-beta.25 – updating now :) Thanks a lot 👍
