### ISSUE TITLE
Get items in draft

### ISSUE THREAD

**Issue by cesarvarela** [angeloashmore/gatsby-source-prismic#203]
Couldn't find this anywhere, is it possible? I want the last version of some types that aren't yet published, for the staging version of a website.

**Comment by angeloashmore** [comment]
Hi @cesarvarela, drafts are currently only supported when using Previews as it uses the preview ref.

Are you wanting the plugin to pull in all published *and* draft documents when you run `gatsby develop`/`gatsby build`?

**Comment by cesarvarela** [comment]
Yep, When I'm developing it would be useful to get draft documents.

**Comment by angeloashmore** [comment]
@cesarvarela This is now part of `v3.1`. 🎉

You can provide a `releaseID` option to your `gatsby-config.js` file.

See: https://github.com/angeloashmore/gatsby-source-prismic#releases
