### ISSUE TITLE
Prismic-specific image fragments don't exist

### ISSUE THREAD

**Issue by ConnorTCM** [angeloashmore/gatsby-source-prismic#204]
https://www.gatsbyjs.org/packages/gatsby-source-prismic/?=primsic#using-imgix-transformed-images

Following the documentation for the recommended _On-the-fly transformed using Imgix_ image processing method, when attempting to use the image fragments such as `...GatsbyPrismicImageFixed_noBase64` I get the following error in the browser:

`The fragment "GatsbyPrismicImageFixed_noBase64" does not exist.`

If I replace the fragment with `...GatsbyImageSharpFluid_noBase64` everything appears to work fine. By using the standard Gatsby image fragment am I losing out on any functionality?

Worth noting that the official Gatsby image fragment documentation includes fragments for other headless CMS's such as Contentful and Sanity but not for Prismic.

**Comment by angeloashmore** [comment]
Hi @ConnorTCM, these fragments *should* exist globally:

- `GatsbyPrismicImageFixed`
- `GatsbyPrismicImageFixed_noBase64`
- `GatsbyPrismicImageFluid`
- `GatsbyPrismicImageFluid_noBase64`

But these will only work for Imgix images, not `gatsby-transformer-sharp` images.

- *Imgix* - You would use the `GatsbyPrismicImage*` fragment on `imageField.fluid` or `imageField.fixed`
- *Sharp* - You would use the `GatsbyImageSharp*` fragment on `imageField.localFile.childImageSharp.fluid` or `imageField.localFile.childImageSharp.fixed`

If the Sharp fragments are working, it sounds like you need to change your query to use the non-localFile field.

Check out this section of the migration guide: https://github.com/angeloashmore/gatsby-source-prismic/blob/882a5a41daac14e1caea039277cb876d97ae8a1c/docs/migrating-from-v2-to-v3.md#replace-local-images-with-imgix-processed-ones

Hope that helps!

**Comment by ConnorTCM** [comment]
Brilliant, thanks @angeloashmore this is helpful. Out of interest, should `imageField.fluid` and `imageField.fixed` be exposed in the GraphiQL interface? The only fields being exposed to me are dimensions, alt, copyright, url, localFile and __typename.

**Comment by ConnorTCM** [comment]
Thanks very much @angeloashmore, this is helpful!
