### ISSUE TITLE
prismic-dom causing issues

### ISSUE THREAD

**Issue by deamme** [angeloashmore/gatsby-source-prismic#212]
My repo https://github.com/deamme/gatsby-starter-prismic-resume worked before but now doesn't and gives `ReferenceError: window is not defined` when running `npm run dev`. 

I'm still using v2 btw.

Any ideas how to fix this?

**Comment by deamme** [comment]
Forgot to use the right API key.. Apparently everything still works.

**Comment by angeloashmore** [comment]
@deamme Glad to hear it's working. Sorry, I didn't get a chance to look into it but please post again if you run into other issues.
