### ISSUE TITLE
gatsby-image images are not building

### ISSUE THREAD

**Issue by chrish-d** [angeloashmore/gatsby-source-prismic#221]
Hey, I have `gatsby-image` working with absolutely fine when it's in a local environment, but as soon as I build/serve then images disappear and only the low-resolution preview is showing.

I've checked the public cache and I can find the folders with the images in, so I know they're building.

From what I can see, the difference between the production and development environments is that in the _production_ environment, there's no `<picture>` tag being added.

Any suggestions would be welcome as I have a deadline looming and unfortunately can't figure this one out...

**Comment by angeloashmore** [comment]
Hi @chrish-d, I see you closed the issue. Were you able to figure it out?

**Comment by chrish-d** [comment]
@angeloashmore I actually meant to open this up on the graphql plugin but landed on this one instead. My mistake! If it can be deleted, that would be fine 😂

**Comment by angeloashmore** [comment]
No worries, good luck!
