### ISSUE TITLE
[RFC] Improving the Prismic Preview developer experience

### ISSUE THREAD

**Issue by angeloashmore** [angeloashmore/gatsby-source-prismic#223]
**Read the full RFC here**: https://gist.github.com/angeloashmore/091eb3765073cecfe1837e4f84ffc0a7

`gatsby-source-prismic` v3 introduced a client-side preview system that integrates with Prismic's REST API via `prismic-javascript`.

The core APIs powering previews is the new `usePrismicPreview` hook and `mergePrismicPreviewData` utility function. Under the hood, `usePrismicPreview` fetches preview data and runs it through the same data transformers used in the source plugin at build-time.

This system provides developers low-level functions to create custom preview systems that work with their existing custom setup. Although powerful, such a system may be more low-level than necessary for most users.

The following RFC presents a higher-level abstraction over `usePrismicPreview` and `mergePrismicPreviewData` primarily through the use of higher-order components.

- Provide a `withPreview` HOC that orchestrates merging preview data from `usePrismicPreview` transparently using `mergePrismicPreviewData`.
- Provide a `withUnpublishedPreview` HOC that orchestrates previewing unpublished documents using the 404 page.
- Provide a `withPreviewResolver` HOC that orchestrates fetching preview data, saving that data to a global store, and redirecting to an appropriate page.
- Provide a global store to store and manage preview data with direct access if needed.
- A clear focus on facilitating data flow and nothing more.

This sets up developers to easily integrate Prismic Previews with gatsby-source-prismic. It also opens the door to external integrations by standardizing the data store.

**Comment by veloce** [comment]
@angeloashmore I've read the RFC. I think this is a great addition in general.

I have just one comment for now: I'm not so sure about wrapping the `withUnpublishedPreview` on the 404 page. The problem in doing that is that in dev mode gatsby bypass this page so your redirect won't work (I tried it). 
I don't know if there is an easy solution to this. Maybe add a route param and more logic to the `withPreviewResolver`? (the logic that actually is documented to check if the path exists). Then instead of wrapping the 404 with the `withUnpublishedPreview`, it would be a dedicated page.

**Comment by gabrielloeb** [comment]
There is [a workaround for the development 404](https://github.com/gatsbyjs/gatsby/issues/16112#issuecomment-515432302).

**Comment by angeloashmore** [comment]
Thanks for the feedback @veloce and @gabrielloeb. The nice thing about using the 404 page is that it shouldn't conflict with the user's other pages.

In general, I'd like to avoid adding non-source-plugin features to a source plugin. Creating a dedicated page with a `*` matcher within the plugin feels like it's moving in the wrong direction.

The nice thing about providing just a `withUnpublishedPreview` HOC is that it can be used any page. So we can recommend users use it on their 404 page **or** their own dedicated page with the `*` matcher.

**Comment by angeloashmore** [comment]
The HOCs have been released as part of `v3.1.0` with a recommendation on using the 404 page.

See: https://github.com/angeloashmore/gatsby-source-prismic/blob/1c8d3e6970ba5c65e3bee9eac63e3dea0b584d9b/docs/previews.md#withUnpublishedPreview

If we decide this causes issues, however, we can update the documentation.
