### ISSUE TITLE
Linked documents in Prismic

### ISSUE THREAD

**Issue by SaintEmbers** [angeloashmore/gatsby-source-prismic#23]
I am having an issue with getting data from linked documents in Prismic. The query is only revealing limited info on the linked document like the id and a slug and not the important data that I need.  If I hard code the options I need in the pagedGet function in fetch.js the data and query fields are available but I am not seeing a way to pass options to that function.  Any help is greatly appreciated. Thanks

**Comment by ppluchon** [comment]
Hello,

I'm facing the same problem… 
Did you find a solution?
Thanks

**Comment by angeloashmore** [comment]
Hey @SaintEmbers, thanks for opening this issue. I'll take a look at this now.

Are you able to use the linked document's ID or slug to get the data that is already in Gatsby?

I'm thinking the best solution is to setup child node links in Gatsby. Thoughts?

**Comment by danmce** [comment]
Same issue - not sure what you mean by 'child node links'?

e.g. I have a linked blog on the home page

home: allPrismicDocument(filter: { type: { eq: "home" } }) {
edges {
 node {
  id
  type
  data {
   ...
   **featured_blog{
    uid
    }**
   }
 }
}

At the moment I have to get all the blogs then use a mapper function to select the blog data I want from this collection based on the featured_blog.uid noted above.

roughly:

let document = mapHomePage(home, blogs)

export const mapHomePage = (home, blogs) => {
 return {
  title: home.data.title,
  blog: blogs.find(b => b.uid === home.data.featured_blog.uid)
 }
}

Seems a little verbose but is this the only way?

**Comment by angeloashmore** [comment]
Closing in favor of #24.
