### ISSUE TITLE
Typename again changed

### ISSUE THREAD

**Issue by RobinHerzog** [angeloashmore/gatsby-source-prismic#235]
Hello,

Why are the typename changed every release? 

I have 40 typename to update each time.

**Comment by angeloashmore** [comment]
Hi @RobinHerzog, that’s not an intentional change. Could you post a list of some of your custom type names so I have a list to test against?

**Comment by RobinHerzog** [comment]
PrismicTemplate1BodyMeta => PrismicTemplate_1BodyMeta

All number has been separated by an underscore.

**Comment by angeloashmore** [comment]
Thanks, stick to `v3.0.2` for now until I publish a fix for that.

**Comment by angeloashmore** [comment]
@RobinHerzog Could you try out `v3.1.1`?

I've added a test to make sure type names remain consistent between releases.
https://github.com/angeloashmore/gatsby-source-prismic/blob/9a916b1dd946e44db9a233e2e534f36b3a942fe0/test/utils.test.ts#L3-L10

**Comment by RobinHerzog** [comment]
Thanks for this update.
It created another issue for all fluid() image function
```
40ea-a0b7-77221cea5a7a_customize-top.svg?auto=compress%2Cformat&fm=json reason: Unexpected token < in JSON at position 0

  26 |           cta_type_2
  27 |           youtube_id
  28 |           hubspot_form_id
  29 |           cta_free_label
  30 |           cta_free_link
  31 |           cta_free_link_v2 {
  32 |             link_type
  33 |           }
  34 |           custom_color
  35 |           hero_image {
> 36 |             fluid(maxWidth: 2000) {
     |             ^
  37 |               ...GatsbyPrismicImageFluid
  38 |               src
  39 |             }
  40 |           }
  41 |         }
  42 |       }
  43 |     }
  44 |   }
  45 | }
```
