### ISSUE TITLE
3.1.1 Image Fluid Error SVG

### ISSUE THREAD

**Issue by RobinHerzog** [angeloashmore/gatsby-source-prismic#236]
Hello,

Thanks for your last update. Unfortunately it created another issue:

It create this issue for all .svg files.

```
invalid json response body at https://images.prismic.io/showcase-dev%2F49f04ea2-c355-40ea-a0b7-77221cea5a7a_customize-top.svg?auto=compress%2Cformat&fm=json reason: Unexpected token < in JSON at position 0

> 36 |             fluid(maxWidth: 2000) {
     |             ^
  37 |               ...GatsbyPrismicImageFluid
  38 |               src
  39 |             }

```
I removed cache and public directory to test.

Thanks

**Comment by angeloashmore** [comment]
@RobinHerzog Could you try `v3.1.2`?

I would recommend using the `GatsbyPrismicImageFluid_noBase64` fragment if you know the image will be an SVG. The resulting placeholder URL will be fairly large if given a detailed SVG like the one in your example.
