### ISSUE TITLE
Remove srcWebp and srcSetWebp from GatsbyPrismicImage

### ISSUE THREAD

**Issue by etabard** [angeloashmore/gatsby-source-prismic#237]
This is not a big deal but including srcWebp and srcSetWebp generated useless html markup and increase page-data size. As imgix auto format webp, would it be possible to remove them and keep it only on _withWebp ?

Thanks a lot !

**Comment by angeloashmore** [comment]
Yes, you're right, those fields should be left out of the non-`_withWebp` fragments.

That brings up the point that if someone were to remove `auto=format`, the WebP fragments wouldn't actually return a WebP URL. The `*Webp` fields in `PrismicImageFixedType` and `PrismicImageFluidType` are just aliases for the non-`Webp` fields. Instead, those fields should forcibly apply `auto=format`. I'll open an issue on `gatsby-plugin-imgix` to track that, but it shouldn't affect most cases.

**Comment by etabard** [comment]
Awesome thanks ! I’m fighting against lighthouse, every byte counts 😅

Le jeu. 4 juin 2020 à 21:21, Angelo Ashmore <notifications@github.com> a
écrit :
