### ISSUE TITLE
Type error with `PrismicImageFixedType` when trying to start development

### ISSUE THREAD

**Issue by advancingu** [angeloashmore/gatsby-source-prismic#238]
When trying to start the `gatsby` development server, I keep getting the following error:
```
$ gatsby develop
success open and validate gatsby-configs - 0.019s
success load plugins - 0.060s
success onPreInit - 0.003s
success initialize cache - 0.012s
success copy gatsby files - 0.021s
success onPreBootstrap - 0.010s
success createSchemaCustomization - 0.004s
success gatsby-source-prismic - create types - 0.007s
success gatsby-source-prismic - fetch documents - 0.974s
success gatsby-source-prismic - create nodes - 0.006s
success gatsby-source-prismic - write out type paths - 0.003s
success source and transform nodes - 1.028s

 ERROR 

Type with name "PrismicImageFixedType" does not exists



  Error: Type with name "PrismicImageFixedType" does not exists
  
  - TypeStorage.js:44 SchemaComposer.get
    [my_project]/[graphql-compose]/lib/TypeStorage.js:44:13
  
  - TypeMapper.js:86 TypeMapper.get
    [my_project]/[graphql-compose]/lib/TypeMapper.js:86:44
  
  - TypeMapper.js:608 TypeMapper.typeFromAST
    [my_project]/[graphql-compose]/lib/TypeMapper.js:608:17
  
  - TypeMapper.js:105 TypeMapper.getWrapped
    [my_project]/[graphql-compose]/lib/TypeMapper.js:105:17
  
  - TypeMapper.js:272 TypeMapper.convertOutputFieldConfig
    [my_project]/[graphql-compose]/lib/TypeMapper.js:272:114
  
  - configAsThunk.js:19 resolveOutputConfigAsThunk
    [my_project]/[graphql-compose]/lib/utils/configAsThunk.js:19:41
  
  - configAsThunk.js:37 
    [my_project]/[graphql-compose]/lib/utils/configAsThunk.js:37:22
  
  - Array.forEach
  
  - configAsThunk.js:36 resolveOutputConfigMapAsThunk
    [my_project]/[graphql-compose]/lib/utils/configAsThunk.js:36:27
  
  - InterfaceTypeComposer.js:165 GraphQLInterfaceType.gqType._fields
    [my_project]/[graphql-compose]/lib/InterfaceTypeComposer.js:165:114
  
  - Array.reduce
  
  - Array.reduce
  

not finished building schema - 0.206s
```

This is from a new project created yesterday. As I am also new to Gatsby, it is hard to debug further. From preliminary research, I assume #230 introduced an issue when it was merged three days ago.

`package.json` dependencies are as follows:
```
  "dependencies": {
    "gatsby": "^2.22.15",
    "gatsby-source-prismic": "^3.1.1",
    "prismic-reactjs": "^1.3.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "devDependencies": {
    "dotenv": "^8.2.0",
    "prettier": "2.0.5"
  },
```

**Comment by mcshakes** [comment]
I am also seeing this when running `npm run develop`. 

![Screen Shot 2020-06-04 at 9 21 50 AM](https://user-images.githubusercontent.com/8164007/83775985-db923300-a644-11ea-92d3-8dc6a9612bd4.png)

Gatsby config has:

```{
      resolve: `gatsby-source-prismic`,
      options: {
        repositoryName: `blogzzz`,
        accessToken: `${process.env.API_KEY}`,
        linkResolver: ({ node, key, value }) => blog_post => `/${blog_post.uid}`,
        schemas: {
          blog_post: require("./src/schemas/blog_post.json")
        }
      },
    }

Let us know if you need more info. And thanks @advancingu for opening the ticket before I did!

**Comment by angeloashmore** [comment]
Thanks for the info @advancingu and @mcshakes. I think this may happen if your repo is not using images.

Please use `v3.0.2` for now until a solution is found. I'll post in here if I have more questions about your setup. Thanks!

**Comment by advancingu** [comment]
@angeloashmore What exactly do you mean with "if your repo is not using images"? That none of the schemas contain an image element?

**Comment by angeloashmore** [comment]
@advancingu Correct, if your schemas do not include any image fields *or* none of your documents have an image. This is just a guess until I have some time to look into this.

**Comment by itsthecheat** [comment]
I'm also having the same issue, though switching to v3.0.2 as suggested works for now. Adding my output below if it's of any help. Thanks!
![Screen Shot 2020-06-16 at 1 24 10 PM](https://user-images.githubusercontent.com/17536124/84808382-9e2f8d00-afd6-11ea-96f2-e095de3cfcc0.png)

**Comment by angeloashmore** [comment]
Thanks for the info @itsthecheat. I haven't had a chance to looking into this yet so thanks for sticking to the previous version for now.

**Comment by Nimlion** [comment]
Unfortunately going to a previous version won't work for me. So if anybody has found a solution please let me know.

**Comment by avcohen** [comment]
Tried reverting to v3.0.2 as suggested but this error is still thrown.

**Comment by marco910** [comment]
I'm using v3.1.4 and getting the same error if my repo is not using images. To solve it if added to one of the types in the repo a "media item", updated the schema in the Gatsby source and now it's working.
Not the best way but it works :)

**Comment by angeloashmore** [comment]
@marco910 Glad you found a temporary solution. Definitely not ideal so I'll dive into this as soon as time allows. Also open to a PR or any diagnostic information anyone can provide.

Thanks!

**Comment by r-saba** [comment]
Having this issue on a brand new project. Adding an image to my custom type in the repo didn't work. Is that what you did to resolve it @marco910 or did I misunderstand?

**Comment by marco910** [comment]
@r-saba I have added the image on the end of a custom type.
Did you update the JSON-schema in Gatsby and restart the dev-server?

**Comment by angeloashmore** [comment]
Thanks for everyone's patience on this. It turned out to be a simple fix of telling Gatsby about the `PrismicImageFixedType` and `PrismicImageFluidType` types before using them.

Please try out `v3.2.1` and let me know if the issue is resolved. Thank you!

**Comment by marco910** [comment]
Has anything in the configuration changed since the update? When I try to start the "gatsby develop" or "gatsby build" I get this error

<img width="994" alt="Bildschirmfoto 2020-07-27 um 13 08 54" src="https://user-images.githubusercontent.com/57726854/88535548-66225d80-d00a-11ea-9d81-400b0bdee1d5.png">

I didn't change anything in my project
