### ISSUE TITLE
RFC: Ideal gatsby-source-prismic functionality

### ISSUE THREAD

**Issue by angeloashmore** [angeloashmore/gatsby-source-prismic#24]
The following list of features would make `gatsby-source-prismic` feature-rich and production usable. Please add any other wanted features and/or comment on the existing list.

**Some features on this list will break compatibility with the current plugin**. Since the plugin is pre-1.0, I will do my best to bump minor versions when breaking changes are published. Once 1.0 is published, traditional semver will be used.

Progress tracked here: #27

## Ideal Features

- Create node types for each content type. This replaces `PrismicDocument` with a type named after the content type, such as `PrismicSharableLink` or `PrismicPage` or `PrismicBlogPost`.

- Create child/parent links between relationship fields.

- Provide `dataString` for all nodes. This allows one to get the raw JSON response from the API as a string (something that can be parsed with `JSON.parse`) (see #20).
  - **Note**: Need to think about this one. Should the `dataString` result be for an individual field, or the whole node? (I think it should be the whole node and be added as a top-level field (i.e. same level as `id`, `data`).

- Provide `html` and `text` fields that run through an HTML serializer function and link resolver function for all RichText fields (see [`prismic-dom`][prismic-dom]).
  - **Note**: HTML parsing is currently done by performing the transformation client-side. This potentially loses the performance benefit of generating it on the server. It also runs into issues when not all fields are returned by GraphQL (see #17).

- Provide `resolvedUrl` field that runs through a link resolver for all Link fields (see [`prismic-dom`][prismic-dom]).

- Provide `gatsby-image` integration.
  - **Note**: By using a local image file, you lose the benefit of using Prismic's CDN. This is a non-issue if your site is hosted on a CDN.

[prismic-dom]: https://github.com/prismicio/prismic-dom

**Comment by angeloashmore** [comment]
@simplesessions Anything else you would add?

**Comment by angeloashmore** [comment]
Just published `v0.2.0@preview` to NPM with the following:

- Create node types for each content type
- Create child/parent links between relationship fields
  - Rather than create parent/child links, the field is replaced with the related document's node
- Provide `dataString` for all nodes
- Provide `html` and `text` fields for all RichText fields

**Comment by angeloashmore** [comment]
Many changes published today are detailed in the new README.

https://github.com/angeloashmore/gatsby-source-prismic/blob/v1/README.md

Published as `v1.0.0-alpha.3@next` to NPM.

**Comment by angeloashmore** [comment]
Added field groups support.

Published as `v1.0.0-alpha.4@next`

**Comment by juliansthl** [comment]
This is amazing, thanks for all your work!

Don't know if it's of any use and certainly tied to my use case, but this is how I integrated gatsby-image for now:

```
// in gatsby-node.js

const { createRemoteFileNode } = require('gatsby-source-filesystem');

const createLocalImageNode = async (props) => {
  const {
    url, store, cache, createNode,
  } = props;
  let remoteFileNode;

  return new Promise(async (resolve, reject) => {
    try {
      remoteFileNode = await createRemoteFileNode({
        url,
        store,
        cache,
        createNode,
      });

      resolve(remoteFileNode.id);
    } catch (e) {
      reject(e);
    }
  });
};


exports.onCreateNode = async (props) => {
  const { node, store, cache } = props;
  const { createNode } = props.boundActionCreators;

  const galleryImages = node.data.gallery.map(async (item, index) => {
      const localImageId = await createLocalImageNode({
        url: item.image.url,
        store,
        cache,
        createNode,
      });

      if (localImageId) {
        node.data.gallery[index].image.image_local___NODE = localImageId;
      }
    });

    await Promise.all(galleryImages);
};
```

**Comment by angeloashmore** [comment]
`gatsby-image` support is live! 🎉 I just published `v1.0.0-alpha.8` to NPM.

The `README` has been updated with instructions, but usage is the same as with other source plugins: https://github.com/angeloashmore/gatsby-source-prismic/tree/3a369afa7aa2b09fc03f2402e54b3ebc86a5129a#image-processing

Please give it a try and let me know if you see any issues.

**Comment by AdamPflug** [comment]
This work is all awesome. I particularly appreciate the improved examples and the much improved stuff for working with slices.

**Comment by angeloashmore** [comment]
`v1.0.0` is published with all noted features. Thanks for the feedback, everyone! 😃
