### ISSUE TITLE
Filtering Document Data on GraphQL in v3

### ISSUE THREAD

**Issue by sparklesam** [angeloashmore/gatsby-source-prismic#244]
Hi @angeloashmore, Thank you very much for maintaining this gatsby plugin. Quick question regarding `v3` the update on `document[0].data` to `document.data`.  I have managed to resolve all the issues upgrading from v2 to v3, except one, How does it affect filtering on GraphQL? 

BEFORE, I was able to filter all post belong to the same category like this

```
query CategoryPage($category: String!) {
  posts: allPrismicPost(
    sort: { fields: [data___date], order: DESC }
    filter: {
      data: {
        categories: { elemMatch: { category: { document: { elemMatch: { data: { name: { eq: $category } } } } } } }
      }
    }
  ) {
```

But now I received the error `"Field "document" is not defined by type PrismicLinkTypeFilterInput."`. On GraphiQL explorer there isn't any option to choose document either. 

![2020-06-26 01_51_26-GraphiQL](https://user-images.githubusercontent.com/10287995/85772624-99de3f00-b74f-11ea-985a-ae14300c7066.png)

Is there any approach I can query this again? 

My v3 Category Template :
https://github.com/sparklesam/todaydojo2019/blob/staging/src/templates/category.jsx

Thanks a lot! 

```
 System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.0
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.5.0 => 2.23.11
    gatsby-image: ^2.3.2 => 2.3.2
    gatsby-plugin-emotion: ^2.0.7 => 2.0.7
    gatsby-plugin-feed: ^2.2.1 => 2.3.27
    gatsby-plugin-google-analytics: ^2.0.19 => 2.1.35
    gatsby-plugin-lodash: ^3.0.5 => 3.1.20
    gatsby-plugin-manifest: ^2.1.1 => 2.2.41
    gatsby-plugin-netlify: ^2.0.16 => 2.1.32
    gatsby-plugin-offline: ^2.1.0 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.22
    gatsby-plugin-sharp: ^2.5.4 => 2.5.4
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.27
    gatsby-plugin-typography: ^2.2.13 => 2.3.22
    gatsby-source-prismic: ^3.0.0 => 3.1.4
    gatsby-transformer-sharp: ^2.4.4 => 2.4.4
```

**Comment by sparklesam** [comment]
If anyone is experiencing similar problems, I have discovered an alternate solution for this matter. I was using [gatsby-starter-prismic](https://www.gatsbyjs.org/starters/LekoArts/gatsby-starter-prismic/) and the category was generated from the array of AllPrismicPost. I have resolved the issue by including a new post type, AllPrismicCategory in the `gatsby-node`'s GraphQL query, passing the uid as context to generate page.

In `gatsby-node.js`;

```
/* GraphQL Query */
const pages = await graphql(`
    {
      allPrismicPost {
        edges {
          node {
            id
            uid
          }
        }
      }
      allPrismicCategory {
        edges {
          node {
            id
            uid
          }
        }
      }
    }
  `);
```

```
/* After Post Generated */
 const categoryList = pages.data.allPrismicCategory.edges;

categoryList.forEach((edge) => {
    createPage({
      path: `/categories/${edge.node.uid}`,
      component: categoryTemplate,
      context: {
        category: edge.node.uid,
      },
    });
  });

```

In Category page template,

```
query CategoryPage($category: String!) {
    page: prismicCategory(uid: { eq: $category }) {
      data {
        name
        description
        keywords
        image {
          fluid {
            ...GatsbyPrismicImageFluid
          }
        }
      }
    }
}
```

**Comment by angeloashmore** [comment]
Hi @sparklesam, glad you were able to find a solution! Filtering/querying by nested relations is tricky with Gatsby's auto-generated GraphQL arguments so I typically approach it similar to how you did in your second comment. I find querying for top-level nodes and working down (e.g. Category => Post) usually works better than working from the bottom-up (e.g. Post => Category).
