### ISSUE TITLE
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

### ISSUE THREAD

**Issue by chapster11** [angeloashmore/gatsby-source-prismic#249]
After upgrading from 3.0.0-beta.14 to 3.1.4 i'm getting this error. 
```
Missing onError handler for invocation 'extracting-queries', error was 'Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
```
I don't have any empty field names "" so not sure where this is coming from all of s sudden. 
Is there an easier way to debug this as the error would seem to be telling me a GraphQL filed name is empty and not able to match the regex check but thats all the message is saying it doesn't tell me what file. 
It doesn't tell me any exact file that might have the error in so its really difficult to debug ? 

Ive seen this in the upgrade docs but still not sure as it doesn't seem like I have an invalid filed as far as empty "". https://github.com/angeloashmore/gatsby-source-prismic/tree/0be79841508c599eee8074b2db423d935b917168#graphql-valid-field-names

**Comment by chapster11** [comment]
Closing this as the docs already discuss this in detail. Malformed graphql names was the issue here. 
Thank you for the great docs for pointing this issue out. 
https://github.com/angeloashmore/gatsby-source-prismic#GraphQL-valid-field-names

**Comment by angeloashmore** [comment]
@chapster11 Glad you found a fix. I've come across the same issue where using Prismic's labels feature on rich text fields adds an empty `""` field.

This is something that can be automatically detected and printed to the console. I'll keep this in mind when we do those improvements. 👍

**Comment by riceboyler** [comment]
@angeloashmore Just wondering, what is the workaround for the labels on rich text fields? Would it be as simple as updating the JSON to put something in the ""?

**Comment by angeloashmore** [comment]
Hi @riceboyler, sorry, I haven't come across this issue in a while so I can't remember the actual error that appears. If you project is showing that now, do you mind posting a screenshot or copy of the output?

To resolve the issue until the plugin can handle it automatically, you can reformat the `labels` field manually. If I remember correctly, the `labels` field turns into something like this:

```json
{
  "": {
    "my-label": "my-label"
  }
}
```

You should be able to change it to:

```json
{
  "labels": ["my-label"]
}
```

**Comment by andreydrozd-smfe** [comment]
I started migrating from the Prismic fork of the original plugin (@prismicio/gatsby-source-prismic-graphql) to this one on a project I inherited and came across this issue. Below is my error output.

```
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
    at assertValidSchema (/Users/andrey.drozd/Development/main-site/node_modules/graphql/type/validate.js:73:11)
    at validate (/Users/andrey.drozd/Development/main-site/node_modules/graphql/validation/validate.js:54:35)
    at extractOperations (/Users/andrey.drozd/Development/main-site/node_modules/gatsby/src/query/query-compiler.js:212:20)
    at processQueries (/Users/andrey.drozd/Development/main-site/node_modules/gatsby/src/query/query-compiler.js:171:45)
    at compile (/Users/andrey.drozd/Development/main-site/node_modules/gatsby/src/query/query-compiler.js:82:19)
    at updateStateAndRunQueries (/Users/andrey.drozd/Development/main-site/node_modules/gatsby/src/query/query-watcher.ts:220:40)
    at extractQueries (/Users/andrey.drozd/Development/main-site/node_modules/gatsby/src/services/extract-queries.ts:18:3)'
⢀ extract queries from components
```

It is indeed from labels on Rich Text Fields. I confirmed this by digging into the node_modules and console logging around some of the code from the stacktrace. 

Did Prismic change its API for labels and that's why this is an issue for older projects? Because I have something like the below:
```
"text_block": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, preformatted, heading1, heading2, heading3, heading4, heading5, heading6, strong, em, hyperlink, image, embed, list-item, o-list-item, o-list-item",
                  "label": "Text block",
                  "labels": {
                    "": [
                      {
                        "name": "color-red"
                      }
                    ]
                  }
                }
              },
```

but it should be as @angeloashmore states above. Below is an example from Prismic docs on labels (https://user-guides.prismic.io/en/articles/1943308-add-custom-styles-to-rich-text)
```
"page-body": {
  "type": "StructuredText",
  "config": {
    "label": "Page Body",
    "placeholder": "Enter your text...",
    "labels": ["right-align", "center-align"]
  }
}
```
