### ISSUE TITLE
withPreview in prod 

### ISSUE THREAD

**Issue by fredshevek** [angeloashmore/gatsby-source-prismic#256]
Hi, 

I'm trying to understand to proper usage of preview functionality. 

Is it safe to have components with `withPreview` wrapped in production branch? I mean is there any possibility of a regular user seeing a saved but unpublished data accidentally?

My understanding is the only path to see preview data is to click the preview button from within Prismic?

While trying to setup the preview functionality, I initially set the `PreviewStoreProvider` and wrapped my component with `withPreview` and then refreshed the page. I was expecting to see my saved data on Prismic. Which didn't happen.
I then created the preview page with `withPreviewResolver` and got it working with clicking preview from Prismic. 

So this tells me it's kinda ok to leave `withPreview` HOCs on production?

**Comment by angeloashmore** [comment]
Hi @fredshevek,

Yes, `withPreview` and the other preview-related higher order components are safe to use in production. Fetching preview data from Prismic requires a special token that can only be obtained by clicking the Preview button in the Prismic interface. If you share that token/link, however, then it is true that anyone could view it. In other words, treat that token like a secret.

Your findings with `withPreviewResolver` and `PreviewStoreProvider` are also correct. Both need to be setup in order for the preview system to work. The flow basically works like this:

1. Click the preview button in Prismic.
2. Prismic opens a new window/tab to your preview resolver page (usually `https://your-website.com/preview`).
3. Your site's `/preview` page must have `withPreviewResolver`, which will see the preview token from Prismic and fetch the previewed document, including unpublished changes.
4. `withPreviewResolver` will determine the previewed document's URL and redirect to that page.
5. Upon landing on the document's page, which must be wrapped in the `withPreview` HOC, `withPreview` will see there was a previewed document fetched and will merge that with your non-preview data.

**A simple visual representation of this flow**:

```
                                ----------- This page will fetch your preview data,
                                |           save it to a global store, then redirect
                                |           to /your-document-page.
                                |           Must have `withPreviewResolver` to save the data.
                                v
Prismic Preview Button  ->  /preview  -> /your-document-page
                                                  ^
                                                  |
                                                  -------- This page will see data for /your-document-page
                                                           saved in the global store and merge it with your
                                                           non-preview data.
                                                           Must have `withPreview` to merge the data.
```

Hope that helps!

If you haven't already, I would recommend setting your API access level to "Private API" if your content is only intended to be used for building your site. See here for instructions: [Generating an access token](https://user-guides.prismic.io/en/articles/1036153-generating-an-access-token#:~:text=If%20you%20do%20not%20have,access%20token%20for%20any%20request.)

**Comment by fredshevek** [comment]
Thanks a lot @angeloashmore !!

**Comment by Floriferous** [comment]
@angeloashmore What about adding this awesome diagram you made to the README? It made everything clean in my mind about how previews actually work :)
