### ISSUE TITLE
Could not find plugin context for repository: "undefined". Check that a gatsby-source-plugin instance exists for that repository.

### ISSUE THREAD

**Issue by chapster11** [angeloashmore/gatsby-source-prismic#272]
I'm getting an error "Could not find plugin context for repository:" after having preview V3 working for months now.
Trying to figure out what this might be happening. 

This is the full error: 
### Uncaught Error: Could not find plugin context for repository: "undefined". Check that a gatsby-source-plugin instance exists for that repository.

Plugins are all at or above the recommend versions according to https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/migrating-from-v2-to-v3.md

"gatsby-source-prismic": "^3.2.1"
"gatsby": "2.24.13"
"react": "^16.13.1",
"react-dom": "^16.13.1",

I'm using usePrismicPreview directly as I have custom pathResolver. Everything used to work for all this but all of a sudden it has stopped working with the above error. 
Ive checked my repositoryName and accessToken and they all match whats on Prismic settings. 

```

  const { previewData, path } = usePrismicPreview(location, {
    repositoryName,
    accessToken, 
    pathResolver: () => doc => pathMapper(doc, mapper)
});
```

**Comment by chapster11** [comment]
I'm seeing from the code base usePrismicPreview only accepts an object now. Not sure if this was always the case ?

**Comment by angeloashmore** [comment]
Hi @chapster11, is it working for you now by removing the `location` argument from `usePrismicPreview`?

You are correct, `usePrismicPreview` changed from accepting `location` and `options` to just `options`. Sorry, this was an oversight on my part and should have been reserved for the next major version since it is a breaking change.

**Comment by chapster11** [comment]
@angeloashmore angeloashmore yes that did the trick. All good it was an easy find when I looked through the source code :)
Sounds good and thanks for following up, I appreciate it greatly!

**Comment by chapster11** [comment]
Has anything changed in the mergePrismicPreviewData({ staticData, previewData }); ? because merges are no longer working for me.

**Comment by chapster11** [comment]
Looks like mergePrismicPreviewData has also changed as my merging is now not working. 
Based on the code base I see there is a new strategy prop added. I tried changing this to the two options rootReplaceOrInsert || traverseAndReplace, but its still not merging the preview data with the static data for me. 

Below is what I'm using. Just added strategy, otherwise it worked before. 
```
  const mergedData = mergePrismicPreviewData({
    staticData,
    previewData,
    strategy: 'traverseAndReplace',
  });
```
