### ISSUE TITLE
Question: Are there any examples?

### ISSUE THREAD

**Issue by jodiedoubleday** [angeloashmore/gatsby-source-prismic#280]
Are there any examples out there of how to use this plugin to generate pages from Prismic using templates and with previews working?

While the docs are quite comprehensive, I worry I'm going down a rabbit hole of doing things a particular way and getting so far in, that if it's wrong it's hard to turn around.

Any examples will help, any open-source projects people know that use this plugin?

**Comment by j-mcgregor** [comment]
Same, some working examples would be gret

**Comment by potatowave** [comment]
Question about previews.  Should I be running previews in their own environment?

For example I have a live server and a staging server,  would I also create a preview server?

**Comment by jodiedoubleday** [comment]
For anyone finding this issue, the best basic example I've found is - https://github.com/rootion/gatsby-prismic-preview
big thanks for @rootion for creating it.
Hopefully, once I've worked out some of the kinks I'll write up a blog post and create a working example.

I'll keep this issue open in case anyone has any other examples available

**Comment by jodiedoubleday** [comment]
> Question about previews. Should I be running previews in their own environment?
> 
> For example I have a live server and a staging server, would I also create a preview server?

I think this is personal preference, I have previews working on my live site,

**Comment by MarcMcIntosh** [comment]
There's an example here https://github.com/prismicio/gatsby-multi-language-site
and some documentation here https://prismic.io/docs/technologies/multi-language-website-example-with-gatsby
