### ISSUE TITLE
API - identical elements, different responses (title nested in array)

### ISSUE THREAD

**Issue by Hahlh** [angeloashmore/gatsby-source-prismic#285]
Good day!

I opened [a thread in the Prismic forum](https://community.prismic.io/t/api-identical-elements-different-responses-title-nested-in-array/2524) already and we came to the conclusion, that it is likely related to the plugin and that we therefore best continue the discussion here. I will use the same description for the issue, with a few infos added:

---------------------------------------

I have identical "title" elements set up in different custom types:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/45669613/98080500-cd577580-1e75-11eb-99bb-6a238d7fcf44.png">
<img width="811" alt="image(1)" src="https://user-images.githubusercontent.com/45669613/98080512-d34d5680-1e75-11eb-94a4-8aab70f5b427.png">

<img width="1311" alt="image(2)" src="https://user-images.githubusercontent.com/45669613/98080530-dba59180-1e75-11eb-84c9-6af3a553a3cc.png">

Those are queried using GraphQL and Gatsby (gatsby-source-prismic).

The funny thing is, that those identical elements and queries lead to different results. The response has the title's text in once case (External Article, TestType) nested in an array and in another not (Blog Post):

<img width="1311" alt="image(2)" src="https://user-images.githubusercontent.com/45669613/98080530-dba59180-1e75-11eb-84c9-6af3a553a3cc.png">

<img width="1089" alt="image(3)" src="https://user-images.githubusercontent.com/45669613/98080565-e6602680-1e75-11eb-9161-f1351135fb68.png">

I double checked the schemas and looked for any differences in the types.

Here as confirmation the two type schemas side by side:
<img width="1521" alt="image(4)" src="https://user-images.githubusercontent.com/45669613/98080660-10b1e400-1e76-11eb-84ed-0beacd4e6e38.png">

This could of course also be an issue of the source plugin and I have checked the repo for similar issues without any results.

What am I missing?

----------------------

Apparently the default behavior should be an object and not an object nested in an array, which is especially curious as I also get an array when I create new test types, that contain nothing but a title:

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/45669613/98081346-38557c00-1e77-11eb-8c12-7da945fd0670.png">

This has to be somehow related to my project, but how can it be, that I am already able to detect those differences in the GraphQL Playground and that I at the same time have a type that seems to be functioning normally?

Are there any other things on my side that could differ between those two cases besides the JSON schemas?

I will next try to recreate the functioning type and see whether I get the same results. If so it could be related to the content of the type itself in Prismic.

Thank you for your time and thank you for the great plugin!

**Comment by Hahlh** [comment]
I created an identical type to BlogPost and still get different responses:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/45669613/98083523-c5e69b00-1e7a-11eb-8c0d-fe4f08c520a4.png">

The JSON schemas of those two types side-by-side:
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/45669613/98083685-034b2880-1e7b-11eb-925d-2d7df8e41c30.png">
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/45669613/98083780-2544ab00-1e7b-11eb-99ed-8a862dd66ff4.png">

**Comment by Hahlh** [comment]
I am also having this issue, but it doesn't seem to have any effect on the site whatsoever. Could this be related?
<img width="634" alt="image" src="https://user-images.githubusercontent.com/45669613/98667133-4cedb480-234e-11eb-8a36-10aead7ab6db.png">

Full:
`ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.base64`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.base64`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.base64`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.src`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.src`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.src`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.srcSet`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.srcSet`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.srcSet`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.srcWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.srcWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.srcWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.srcSetWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.srcSetWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.srcSetWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.sizes`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.sizes`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.sizes`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.width`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.width`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.width`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.height`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFixedType.height`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFixedType.height`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.base64`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.base64`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFluidType.base64`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.src`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.src`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFluidType.src`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.srcSet`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.srcSet`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFluidType.srcSet`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.srcWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.srcWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFluidType.srcWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.srcSetWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.srcSetWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFluidType.srcSetWebp`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.sizes`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.sizes`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFluidType.sizes`.


 ERROR 

Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFluidType.aspectRatio`.


 ERROR 

Field extension arguments must be provided as an object. Received "SORTABLE" on `PrismicImageFluidType.aspectRatio`.


 ERROR 

Field extension arguments must be provided as an object. Received "true" on `PrismicImageFluidType.aspectRatio`.`

**Comment by angeloashmore** [comment]
Hi @Hahlh,

The last issue seems to be described here as well: https://github.com/angeloashmore/gatsby-source-prismic/issues/274

Regarding the `title` field issue, can you show me your plugin config in `gatsby-config.js`?

**Comment by Hahlh** [comment]
Hey @angeloashmore !

Thank you for your answer.

And there we got the solution already. :tada: 

I forgot to add the new schemas to the gatsby-config.js altogether:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/45669613/98737299-4ee36200-23a6-11eb-866a-0e72d6077928.png">

After having added the testtype schema into the config, I can confirm that I now receive the expected response in GraphQL playground:
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/45669613/98737540-a08bec80-23a6-11eb-852a-fa0d8fea0132.png">

I will update the thread in the Prismic forum. 

Thank you for pointing me in the right direction! :slightly_smiling_face: 

This issue can be closed, if you don't need any additional information from me.

**Comment by angeloashmore** [comment]
Awesome, thanks for reporting back! At some point in the future, I plan to have the plugin print helpful messages like missing schemas to avoid issues like these.
