### ISSUE TITLE
Question: schemas

### ISSUE THREAD

**Issue by necheporenko** [angeloashmore/gatsby-source-prismic#287]
Is there a way to automatically generate the schemas? fetch all schemas?

I can't believe I need to copy the JSON schema from the admin panel (Prismic) and manually create the `./src/schemas/someschema.json` file and then I should remember to update this file if I change it in the admin panel.

**Comment by angeloashmore** [comment]
Unfortunately, there isn't a way to automatically fetch the schemas at this point. Prismic does not provide that data as part of the API.

I have brought this up with their team so they are aware of the request. Until such a feature is made available, you will need to copy/paste the JSON schemas from the Prismic UI into your project.

**Comment by necheporenko** [comment]
Hi, @angeloashmore,
Ok, got it. Thanks for your reply.
