### ISSUE TITLE
Rich Text Link Resolver issues

### ISSUE THREAD

**Issue by jodiedoubleday** [angeloashmore/gatsby-source-prismic#288]
When using Link Resolver, my previews work great but links that are contained in Rich Text fields are behaving strangely. I wonder if anyone could shed some light on what I'm doing wrong.

I'm getting the output...
```
<a href="doc => {
  if (doc.uid === 'index') {
    return `/`
  }

  return `/${doc.uid}`
}">find out more</a>
```

My link resolver is set as..

```
const linkResolver = ({ node, key, value }) => doc => {
  if (doc.uid === 'index') {
    return `/`
  }
  return `/${doc.uid}`
}

module.exports = linkResolver
```

and in my gatsby config, I have...

```
const prismicLinkResolver = require('./src/utils/resolver')
```
and

```
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: 'my-repo',
        schemas: {
          page: require('./src/schemas/page.json'),
        },
        lang: '*',
        prismicToolbar: true,
        linkResolver: () => prismicLinkResolver,
        shouldDownloadImage: ({ node, key, value }) => {
          return true
        },
      },
    }
```

**Comment by angeloashmore** [comment]
Hi @jodiedoubleday, it looks like you have one too many levels of functions.

Your link resolver is correct; it should be a function that returns a function, the first with `node, key, value` as arguments, and the second with the Prismic document.

In your `gatsby-config.js`, you should be passing that function directly, not as another function.

```diff
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: 'my-repo',
        schemas: {
          page: require('./src/schemas/page.json'),
        },
        lang: '*',
        prismicToolbar: true,
-       linkResolver: () => prismicLinkResolver,
+       linkResolver: prismicLinkResolver,
        shouldDownloadImage: ({ node, key, value }) => {
          return true
        },
      },
    }
```

Hope that helps. I'll close this for now but feel free to reply if it's not working after that change.

**Comment by jodiedoubleday** [comment]
This is perfect thanks @angeloashmore
