### ISSUE TITLE
allPrismicPage doesn't exist

### ISSUE THREAD

**Issue by jrandallw** [angeloashmore/gatsby-source-prismic#290]
I'm in the process of migrating my site from `gatsby-source-prismic-graphql` to this plugin. So far so good. However, I'm not getting `allPrismicPages` in my GraphiQL, so I can't dynamically set the page templates from the `uid` of my pages, using the `gatsby-node.js` example from the README. What do I need to set in my repo or the plugin to be able to access that data?

**Comment by jodiedoubleday** [comment]
I'm in the process of migrating over as well and I'm only a few steps ahead of you it seems.

Make sure you have...
I have the following in my gatsby-node.js file...
```
const path = require('path')

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  const pages = await graphql(`
    {
      allPrismicPage {
        edges {
          node {
            id
            uid
            lang
          }
        }
      }
    }
  `)

  pages.data.allPrismicPage.edges.forEach(edge => {
      createPage({
        path: `/`,
        component: path.resolve('./src/templates/page.jsx'),
        context: {
          id: edge.node.id,
        },
      })
  })
}
```

also make sure you have your schema referenced in your gatsby config (and of course the file exists)
```
        schemas: {
          page: require('./src/schemas/page.json'),
        },
```

Hopefully that helps. If you have an example repo i'd be happy to take a look.

**Comment by jrandallw** [comment]
Thank you, I'm tracking with it now. `allPrismicPage` isn't a default to reference all Prismic pages, yes? That's just the reference you used in the documentation, and I'm just confused? That being said, is there a way to dynamically set page templates for all my pages with different types?

**Comment by jodiedoubleday** [comment]
allPrismicPage is a reference to a schema type if Page in Prismic.
if you had a Blogpost type the code you would need to add to your gatsby-node.js

```
const path = require('path')

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  const pages = await graphql(`
    {
      allPrismicPage {
        edges {
          node {
            id
            uid
            lang
          }
        }
      }
allPrismicBlogpost {
        edges {
          node {
            id
            uid
            lang
          }
        }
      }
    }
  `)

  pages.data.allPrismicPage.edges.forEach(edge => {
      createPage({
        path: `/${edge.node.uid}`,
        component: path.resolve('./src/templates/page.jsx'),
        context: {
          id: edge.node.id,
        },
      })
  }),
  pages.data.allPrismicBlogpost.edges.forEach(edge => {
      createPage({
        path: `/blodpost/${edge.node.uid}`,
        component: path.resolve('./src/templates/blogpost.jsx'),
        context: {
          id: edge.node.id,
        },
      })
  })
}```

**Comment by jrandallw** [comment]
Great, makes sense. Thank you!
