### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by jodiedoubleday** [angeloashmore/gatsby-source-prismic#296]
I get a warning message when running the build...
```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://reactjs.org/link/warning-keys for more information.
    at script
```

I've give me no indication of where the error is, I've got keys on all my maps.
I wonder if anyone else has the issue or knows how to fix, I'm wondering if its something to do with for my foreach around the CreatePage.

I know this is a long shot.

**Comment by jameskirkby** [comment]
I've seen this when I have Prismic previews enabled (`prismicToolbar` set to `true` in my config)
