### ISSUE TITLE
All data in graphiQL is empty

### ISSUE THREAD

**Issue by Floriferous** [angeloashmore/gatsby-source-prismic#300]
Hello there,

I'm migrating from `@prismicio/gatsby-source-prismic-graphql`, and I believe I've got this plugin setup right, but there is no data in graphiQL?

All the types are available in the left navbar, including slices, but everything I query is empty. There's no error whatsoever either?

Here's my configuration:

```js
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: process.env.PRISMIC_REPO,
        accessToken: process.env.PRISMIC_API_KEY,
        linkResolver: ({ node, key, value }) => linkResolver,
        htmlSerializer: ({ node, key, value }) => htmlSerializer,
        lang: 'fr',
        schemas: {
          page: require('./src/schemas/page.json'),
          post: require('./src/schemas/post.json'),
        },
        shouldDownloadImage: () => true,
      },
    },
```

Not sure what else to try, I've obviously cleaned the cache, reinstalled node modules.

**Comment by steoneill** [comment]
For `lang` have you tried `fr-fr`? I think your issue might be there as there is support for `ca-fr` etc!

**Comment by Floriferous** [comment]
yeah, that was it.. 🤦‍♂️
