### ISSUE TITLE
Is there a way to detect if someones in preview mode?

### ISSUE THREAD

**Issue by jodiedoubleday** [angeloashmore/gatsby-source-prismic#306]
I'm thinking of displaying warning messages which a user doesn't add an ALT tag to images (think red border around the images etc) but I want this to only appear when a website is in preview 'mode' so that real users can't see the glaring red box when live.

Is there a variable, hook or anything which tell me in in a preview state?

**Comment by angeloashmore** [comment]
Hey @jodiedoubleday, that's a good idea. Right now, the `withPreview` HOC does not pass a `isPreview` prop down to the page. This will be provided in the next version of the plugin exactly for cases like you described.

In the mean time, you should be able to use the `usePreviewStore` hook in your component to read into the root-level state. Something like the following should work:

```js
import { usePrismicStore } from 'gatsby-source-prismic'

const MyPage = ({ data }) => {
  const [prismicPreviewState] = usePrismicStore()
  const isPreview = prismicPreviewState.enabled

  return (
    <div>
      <img
        src={data.prismicPage.data.image.url}
        className={isPreview ? 'red-outline' : undefined}
      />
    </div>
  )
}

export default withPreview(MyPage, {
  // your options
})
```

**Comment by jodiedoubleday** [comment]
Thanks @angeloashmore this looks great. and looking forward to V4 the roadmap looks great!
