### ISSUE TITLE
Can I use hooks?

### ISSUE THREAD

**Issue by cbasJS** [angeloashmore/gatsby-source-prismic#311]
Is possible use hooks for sourcing data? I mean, how can I do it?

If this is supporting, which is the best way for doing?

**Comment by Hahlh** [comment]
This should be relevant to your question:
[Querying Data in Components with the useStaticQuery Hook
](https://www.gatsbyjs.com/docs/how-to/querying-data/use-static-query/
)

**Comment by angeloashmore** [comment]
Thanks @Hahlh!

This plugin works like many other Gatsby source plugins so general guides on `useStaticQuery` apply. You can query your data from Prismic using page queries ([details here](https://www.gatsbyjs.com/docs/how-to/querying-data/page-query/)) or the `useStaticQuery` hook within your components ([details here](https://www.gatsbyjs.com/docs/how-to/querying-data/use-static-query/)).

I'm going to close this issue, but feel free to ask follow up questions @cbasJS.
