### ISSUE TITLE
TypeError: Cannot read property 'link_type' of null

### ISSUE THREAD

**Issue by jodiedoubleday** [angeloashmore/gatsby-source-prismic#312]
When running I'm getting the following error...

<img width="880" alt="Screenshot 2021-01-31 at 20 37 26" src="https://user-images.githubusercontent.com/778942/106397281-732e6800-6404-11eb-8df4-f7d792957827.png">

I've had a look at a few old Github issues, but most of the answers/fixes were for v2. I wondered if anyone else has come across the same issue with the current v3 version and if so how did they resolve it?

(Appreciate you are probably spending all your time on v4 right now.)

**Comment by angeloashmore** [comment]
Thanks for the report @jodiedoubleday. An additional check was added to the plugin in `v3.3.2` which doesn't take into account when a link field is `null`.

This line needs to first check that `field` is non-nullable:

https://github.com/angeloashmore/gatsby-source-prismic/blob/430493173e83ec058b2e9b1e70b05ae6df67b1c5/src/environment.node.ts#L114

I'll try to push out a fix ASAP. 👍

**Comment by angeloashmore** [comment]
A fix has been published in `v3.3.3`.

@jodiedoubleday Could you give it a try and let me know if the error is fixed? I added a test for this case which ended up revealing the error in a few other places in addition to the one mentioned above.

**Comment by jodiedoubleday** [comment]
@angeloashmore thanks for your super quick reply. I've given it a test and it works great, thanks.
