### ISSUE TITLE
Unpublished document preview showing 404 and not rendering React in production

### ISSUE THREAD

**Issue by crcollver** [angeloashmore/gatsby-source-prismic#314]
For the last few months I've had previews working with Netlify hosting without any issue.  However, within the last week, previewing unpublished pages brings me to the 404 page with a console error saying React was not rendered.  Usually I wasn't even getting a stack trace, but I did manage this one screenshot.
![Screenshot 2021-02-04 175258](https://user-images.githubusercontent.com/30027166/106978854-f7892f80-6711-11eb-99e9-43151c403dfa.png)

The weird thing about this is that my local gatsby build works just fine and it previews the unpublished documents correctly.  I've tried deploying with multiple versions of Gatsby and this plugin to Netlify with no luck.

/package.json that created the above screenshot
```
"dependencies": {
    "gatsby": "2.25.0",
    "gatsby-image": "^2.4.5",
    "gatsby-plugin-catch-links": "^2.3.5",
    "gatsby-plugin-google-analytics": "^2.3.13",
    "gatsby-plugin-manifest": "^2.4.6",
    "gatsby-plugin-postcss": "^2.3.2",
    "gatsby-plugin-react-helmet": "^3.3.9",
    "gatsby-plugin-sharp": "^2.6.9",
    "gatsby-plugin-sitemap": "^2.4.14",
    "gatsby-source-filesystem": "^2.3.8",
    "gatsby-source-prismic": "3.2.1",
    "gatsby-transformer-sharp": "^2.5.3",
    "prismic-reactjs": "^1.3.1",
    "react": "^16.12.0",
    "react-datepicker": "^3.1.3",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0",
    "react-html-renderer": "^0.3.2",
    "tailwindcss": "^1.4.6",
    "typeface-nixie-one": "0.0.72",
    "typeface-roboto-slab": "^1.1.4"
}
```

I found a similar error message in an issue on the Gatsby repo, but it seemed unrelated to the issue I'm having now.  

My preview setup in my project is exactly the same as the documentation for this plugin describes.  Like I said, I've had success with the preview feature for the past few months so it almost seems like a recent auto Netlify build caused it.

Maybe others are experiencing this, too and can offer some guidance!

Thanks!

**Comment by crcollver** [comment]
For some strange reason clearing my Chrome cache seemed to have solved this issue.  However, this doesn't seem to really fit with the console that was happening.  Regardless, everything is working as intended now.  I wish I could give more insight!

**Comment by angeloashmore** [comment]
Hey @crcollver, thanks for the follow up. That's a strange error that appears to be Gatsby or maybe even Webpack related.

Just in case you didn't try this, you could also try running `gatsby clean` to clear Gatsby's `.cache` and `public` directories. This will force Gatsby to rebuild everything from scratch.

Glad everything is working again though!
