### ISSUE TITLE
Cannot launch localhost when migrating from gatsby-source-prismic-graphql to this plugin

### ISSUE THREAD

**Issue by andreydrozd-smfe** [angeloashmore/gatsby-source-prismic#319]
I'm trying to migrate from the Prismic fork of gatsby-source-prismic-graphql to this plugin, and the struggle is real. The official migration guide (https://prismic.io/docs/technologies/migrate-to-the-recommended-plugin-gatsby) is lacking. I came across issue 249 and thankfully I was able to fix it with help from comments on the issue.

Now, I'm trying to get localhost to launch in order to refactor my GraphQL queries by using localhost:8000/__graphql . Understandably I get a lot of unknown type errors when I run `gatsby develop` because of the difference in schemas between the two plugins. However, the project keeps building and seems to be successful until the last second when the server shuts down because it can't find a file in the .cache directory. Below is the output of the end of `gatsby develop`. 

```
success write out requires - 0.006s
success run static queries - 0.112s - 2/2 17.91/s
success run page queries - 0.034s - 3/3 87.62/s
⢀ Building development bundleWarning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://fb.me/react-warning-keys for more information.
    in link
    in HTML
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in script
    in HTML
success Generating image thumbnails - 24.258s - 6/6 0.25/s
⠀
You can now view main-site in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 40.350s
error ENOENT: no such file or directory, open '/Users/username/Development/main-site/.cache/json/_.json'


  Error: ENOENT: no such file or directory, open '/Users/username/Development/main-site/.cache/json/_.json'

error Command failed with exit code 1.
```

What am I doing wrong here? I run `gatsby clean` right before running `gatsby develop`. Below is my plugin config.

```
const linkResolver = require('./src/utils/linkResolver');
  ...
 options: {
        repositoryName: process.env.PRISMIC_REPOSITORY,
        accessToken: process.env.PRISMIC_ACCESS_TOKEN,
        linkResolver,
        schemas: {
          contracts_page: require('./schemas/contracts_page.json'),
          dictionary_terms: require('./schemas/dictionary_terms.json'),
          event: require('./schemas/event.json')
          ...
        },
        lang: '*',
        prismicToolbar: true,
      },
```

**Comment by andreydrozd-smfe** [comment]
I got localhost running. It turns out I had to make one of my page queries adhere to this plugin's schema in order for the project to build successfully, along with adding a gatsby-node createPages export, which was not necessary in the old plugin.

I hope this helps any future migrants as Prismic's migration guide is incomplete and the README on this plugin could use an update.

**Comment by angeloashmore** [comment]
Hi @andreydrozd-smfe, thanks for taking the time to document this. If you encounter any other issues while migrating, noting them down here would be very helpful in updating the documentation for future developers.

Development on the next major version of the plugin is in progress which will involve a documentation refresh. Now would be a great time to integrate anything you feel is missing.
