### ISSUE TITLE
Content Slices returned out of order

### ISSUE THREAD

**Issue by simplesessions** [angeloashmore/gatsby-source-prismic#32]
When working with slices, the different slices seem to be grouped by slice type instead of the order in which they're specified in Prismic.

Using 1.0.0-alpha7, everything seems to be in order.

<img width="476" alt="screen shot 2018-05-15 at 11 44 44 am" src="https://user-images.githubusercontent.com/217550/40085282-a242e766-5835-11e8-8299-5d05f78c5798.png">

Post 1.0.0-alpha7

<img width="471" alt="screen shot 2018-05-15 at 11 43 39 am" src="https://user-images.githubusercontent.com/217550/40085296-ab4b740e-5835-11e8-8b1f-442767afb418.png">

**Comment by angeloashmore** [comment]
I wonder if it’s related to the async processing. I think using `parallel` or `series` instead of `Promise.all` and `map` or `forEach` could help here.

**Comment by simplesessions** [comment]
@angeloashmore Been trying this out the past couple days with various content, and `v1.0.0-alpha.10` works beautifully. Thanks!
