### ISSUE TITLE
Problem with GatsbyPrismicImageFixed in preview mode

### ISSUE THREAD

**Issue by mopixels** [angeloashmore/gatsby-source-prismic#321]
Hey, 

I'm having an issue in Prismic preview mode with images that are queried with  `...GatsbyPrismicImageFixed`. All of those images in preview have default width of 400px, no matter what width or height I declare in query I always get 400px. Everything seems to be fine with fluid images.

Here's an example of my query: 
```
fixed(width: 160, height: 80) {
 ...GatsbyPrismicImageFixed
}
```

I'm using ` "gatsby-source-prismic": "3.2.1",`. I tried to update to the newest version, but It doesn't solve the issue.

My Imgix params: 
```
imageImgixParams: {
 auto: 'compress,format',
 fit: 'max',
 q: 75
}
```
I also tried playing around with `fit` param, but no luck there.

This issue exists only in preview mode, but still it would be nice if my teammates could preview how pictures look before publishing :)

**Comment by angeloashmore** [comment]
Hi @mopixels, thanks for the detailed explaination.

This is a limitation of the preview functionality, unfortunately. The `fixed(width: 160, height: 80)` parameters are provided in the GraphQL query, which is used during development and build-time, but is unavailable in production during previews.

As a result, we need to use default values for the parameters which is `width: 400`.

Are you able to circumvent this using CSS on the displayed image by forcing it to always render at `160w` even when the image is larger?

**Comment by mopixels** [comment]
@angeloashmore thanks for your suggestion. Looks like I found a workaround. I noticed that Gatsby-image object has dimensions parameter, so for fixed images I set width and height manually like this:
```
style={
 fixed && { maxWidth: dimensions.width, maxHeight: dimensions.height}
}
```
I still get `width: 400px;` but `max-width: 160px;` stops image from blowing out of container. Images appear to be a bit blurry, but since it's a preview mode it doesn't really matter :) 

I haven't tested this extensively, but it seems to be working.

**Comment by angeloashmore** [comment]
Great, glad to hear you found a workaround! In the future, it might be possible for the plugin to save those width/height parameters and make them available during previews. I'll add it to the list of feature requests.

I'm going to close this issue as everything seems to be working as expected, but I'll like this issue to the request.
