### ISSUE TITLE
Struggling to get data from relationship field within a group. Any help??

### ISSUE THREAD

**Issue by jackkemmish** [angeloashmore/gatsby-source-prismic#323]
Hi there,

I am just starting out using this source plugin for a project I am working on and was wondering if someone could help with an issue I have to do with content relationships and groups.

I have created a singleton template, for this example, called Work List. Within this Work List template I have a group where I use a content relationship field to link a repeatable Work Page template. The query is getting the related Work Page URL, but returns null when querying the document's content; for example I am just trying to get the display title for now. It shows the Work Page templates fields in the graphql explorer on the left, but when querying, it says `"document": null`.

**This is my Work List template:**
`{
  "Main": {
    "display_title": {
      "type": "StructuredText",
      "config": {
        "single": "heading1",
        "label": "display_title"
      }
    },
    "work_list_group": {
      "type": "Group",
      "config": {
        "fields": {
          "work_list_page": {
            "type": "Link",
            "config": {
              "select": "document",
              "customtypes": [
                "work_page"
              ],
              "label": "Work page"
            }
          }
        },
        "label": "Work"
      }
    }
  }
}`

**This is my Work Page template**
`{
  "Main": {
    "display_title": {
      "type": "StructuredText",
      "config": {
        "single": "heading1",
        "label": "display_title"
      }
    },
    "uid": {
      "type": "UID",
      "config": {
        "label": "uid"
      }
    },
    "body": {
      "type": "Slices",
      "fieldset": "Slice zone",
      "config": {
        "labels": {
          "headline_with_button": [],
          "full_width_image": [],
          "info_with_image": [],
          "text_info": [],
          "email_signup": []
        },
        "choices": {
          "headline_with_button": {
            "type": "Slice",
            "fieldset": "Headline with button",
            "description": "Headline & description with button",
            "icon": "library_books",
            "display": "list",
            "non-repeat": {
              "headline": {
                "type": "StructuredText",
                "config": {
                  "single": "heading1, heading2",
                  "label": "headline"
                }
              },
              "description": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, strong, em, hyperlink, list-item, o-list-item",
                  "allowTargetBlank": true,
                  "label": "description"
                }
              },
              "button": {
                "type": "Image",
                "config": {
                  "constraint": {
                    "width": 235,
                    "height": 75
                  },
                  "thumbnails": [],
                  "label": "button"
                }
              }
            },
            "repeat": {}
          },
          "full_width_image": {
            "type": "Slice",
            "fieldset": "Full width image",
            "description": "Full page width featured image",
            "icon": "image",
            "display": "list",
            "non-repeat": {
              "background_image_position": {
                "type": "Select",
                "config": {
                  "options": [
                    "Left",
                    "Right"
                  ],
                  "label": "background_image_position"
                }
              },
              "image": {
                "type": "Image",
                "config": {
                  "constraint": {
                    "width": 1080,
                    "height": 580
                  },
                  "thumbnails": [],
                  "label": "image"
                }
              }
            },
            "repeat": {}
          },
          "info_with_image": {
            "type": "Slice",
            "fieldset": "Info with image",
            "description": "Text section with featured image",
            "icon": "art_track",
            "display": "list",
            "non-repeat": {
              "featured_image": {
                "type": "Image",
                "config": {
                  "constraint": {
                    "width": 600,
                    "height": 690
                  },
                  "thumbnails": [
                    {
                      "name": "tablet",
                      "width": 800,
                      "height": 400
                    },
                    {
                      "name": "mobile",
                      "width": 400,
                      "height": 300
                    }
                  ],
                  "label": "featured_image"
                }
              },
              "section_title": {
                "type": "StructuredText",
                "config": {
                  "single": "heading1, heading2",
                  "label": "section_title"
                }
              },
              "text": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, heading3, strong, em, hyperlink, list-item, o-list-item",
                  "allowTargetBlank": true,
                  "label": "text"
                }
              }
            },
            "repeat": {}
          },
          "text_info": {
            "type": "Slice",
            "fieldset": "Text info",
            "description": "2 column text section",
            "icon": "subject",
            "display": "list",
            "non-repeat": {
              "section_title": {
                "type": "StructuredText",
                "config": {
                  "single": "heading1, heading2",
                  "label": "section_title"
                }
              },
              "left_column_text": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, heading3, strong, em, hyperlink, list-item, o-list-item",
                  "allowTargetBlank": true,
                  "label": "left_column_text"
                }
              },
              "right_column_text": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, heading3, strong, em, hyperlink, list-item, o-list-item",
                  "allowTargetBlank": true,
                  "label": "right_column_text"
                }
              }
            },
            "repeat": {}
          },
          "email_signup": {
            "type": "Slice",
            "fieldset": "Email signup",
            "description": "Email signup form",
            "icon": "email",
            "display": "list",
            "non-repeat": {
              "section_title": {
                "type": "StructuredText",
                "config": {
                  "single": "heading1, heading2",
                  "label": "section_title"
                }
              },
              "description": {
                "type": "StructuredText",
                "config": {
                  "multi": "paragraph, strong, em, hyperlink, list-item, o-list-item",
                  "allowTargetBlank": true,
                  "label": "description"
                }
              },
              "input_label": {
                "type": "StructuredText",
                "config": {
                  "single": "paragraph",
                  "label": "input_label"
                }
              },
              "input_placeholder": {
                "type": "StructuredText",
                "config": {
                  "single": "paragraph",
                  "label": "input_placeholder"
                }
              },
              "button_text": {
                "type": "StructuredText",
                "config": {
                  "single": "paragraph",
                  "label": "button_text"
                }
              }
            },
            "repeat": {}
          }
        }
      }
    }
  },
  "Home carousel": {
    "home_carousel_title": {
      "type": "StructuredText",
      "config": {
        "single": "heading2",
        "label": "Home carousel title"
      }
    },
    "home_carousel_image": {
      "type": "Image",
      "config": {
        "constraint": {},
        "thumbnails": [],
        "label": "Home carousel image"
      }
    },
    "home_carousel_video": {
      "type": "Embed",
      "config": {
        "label": "Home carousel video"
      }
    }
  }
}`

**The query I am trying in GraphQl playground**
`query workListQuery {
  prismicWorkList {
      work_list_group {
        work_list_page {
          url
          document {
            ... on PrismicWorkPage {
              id
              uid
              data {
                display_title {
                  text
                }
              }
            }
          }
        }
      }
    }
  }
}`

Sorry for the long message here, trying to provide as much detail.

Any help would be greatly appreciated!

Thanks,

Jack

**Comment by angeloashmore** [comment]
Hi @jackkemmish, no worries about the long message. More detail is always helpful!

Everything with your queries looks normal. Could you check the following?

1. Use the latest version of `gatsby-source-prismic`. There was a bug in a previous version where the `document` field would be null even if the field had a value. `v3.3.3` fixes it.

2. The `schemas` object in `gatsby-config` must use the exact API IDs of your custom types. If you name your custom type `work-list`, it must appear as `work-list` in the object, not `workList` or `work_list`. You can check your custom type API IDs in the Prismic custom types dashboard.

   <img width="593" alt="Screen Shot 2021-03-03 at 9 28 50 AM" src="https://user-images.githubusercontent.com/8601064/109861050-f826c000-7c02-11eb-8b78-5d1993dc9ac2.png">

3. Ensure your custom type JSON files are up to date with the latest version in Prismic.

4. If things are still not working at this point, run `gatsby clean` to clear Gatsby's caches and try again.

Let me know if you're still running into issues after checking those and we can try to debug it further.

**Comment by jackkemmish** [comment]
Hi Angelo,

Thanks for the response!

I updated the package like you advised and all is working now. Silly me.

Thanks again.

Jack

**Comment by angeloashmore** [comment]
Awesome, glad it was an easy fix!
