### ISSUE TITLE
`wrapRootElement` is not a known API

### ISSUE THREAD

**Issue by cjost1988** [angeloashmore/gatsby-source-prismic#326]
Hi,

I try to get the nice preview functionality to work, but sadly I am failing.
I've added the `wrapRootElement` API in both `gatsby-ssr.js` and `gatsby-browser.js` but when I build it's giving me following error:

```
 ERROR #11329 

Your plugins must export known APIs from their gatsby-browser.js.

See https://www.gatsbyjs.org/docs/browser-apis/ for the list of Gatsby browser APIs.

- Your local gatsby-browser.js is using the API "export default wrapRootElement" which is not a known API.

Some of the following may help fix the error(s):

- Rename "export default wrapRootElement" -> "wrapRootElement"
```
and
```
 ERROR #11329 

Your plugins must export known APIs from their gatsby-ssr.js.

See https://www.gatsbyjs.org/docs/ssr-apis/ for the list of Gatsby ssr APIs.

- Your local gatsby-ssr.js is using the API "export default wrapRootElement" which is not a known API.

Some of the following may help fix the error(s):

- Rename "export default wrapRootElement" -> "wrapRootElement"
```

I am using:
- gatsby@3.0.4
- gatsby-source-prismic@3.3.4

Any ideas?
I checked the documentation of gatsby and its stating that this API should exist :D 

Cheers,
Chris

**Comment by angeloashmore** [comment]
Hi @cjost1988, thanks for providing all of the details.

It looks like your `wrapRootElement` API is exporting as the default export (`export default wrapRootElement`), but it should actually only be a named export.

Can you check that your `gatsby-browser.js` and `gatsby-ssr.js` files do not contain `export default wrapRootElement`? Also, can you check that `wrapRootElement` is exported using `export const`?

```diff
  export const wrapRootElement = () => (
    /** contents of wrapRootElement here **/
  )

- export default wrapRootElement
```

**Comment by cjost1988** [comment]
Hi @angeloashmore,

> thanks for providing all of the details.
Not thanks for that, it's my task to provide you with all information so you can help me as easy as possible. But thanks for the credits ;)

> It looks like your wrapRootElement API is exporting as the default export (export default wrapRootElement),
You're 100% right, I've changed it and the error is gone.
But please update the documentation according to this since the documentation on https://prismic.io/docs/technologies/previews-hocs-gatsby is currently stating that it's the default export. But I could have asked myself why it should be a default export anyways :D 

Cheers,
Chris

**Comment by a-trost** [comment]
Thanks, @cjost1988 , we're changing the documentation to remove that bug. I appreciate you pointing it out!
