### ISSUE TITLE
Gatsby v3 upgrade

### ISSUE THREAD

**Issue by andreydrozd-smfe** [angeloashmore/gatsby-source-prismic#328]
Has anyone tried upgrading to Gatsby 3 yet? It seems like there's some some miscommunication between the plugin and Gatsby because a production build works, but local development partially works - only the GraphiQL endpoint works. 

More details about the issue [here](https://github.com/gatsbyjs/gatsby/issues/30147#issuecomment-799675410).

**Comment by Coffee-Up** [comment]
I have the same issue, starting from a fresh `gatsby new` doesn't work.
[npm_lg.txt](https://github.com/angeloashmore/gatsby-source-prismic/files/6144268/npm_lg.txt)

**Comment by a-trost** [comment]
Hey @Coffee-Up, did you try this bit from the logs?

```
75 error Fix the upstream dependency conflict, or retry
75 error this command with --force, or --legacy-peer-deps
75 error to accept an incorrect (and potentially broken) dependency resolution.
```

With React v17 this issue seems to be somewhat common. If you haven't already, could you try to run `npm i gatsby-source-prismic --legacy-peer-deps`

**Comment by Coffee-Up** [comment]
Thank you for the answer, i have swiched with yarn and it works now. I will not use your command as it may broke something.

**Comment by andreydrozd-smfe** [comment]
I tried again with Gatsby 3.1 and it worked this time. Just some manageable missing deps errors remained.
