### ISSUE TITLE
Custom URLs and Link Resolver

### ISSUE THREAD

**Issue by jodiedoubleday** [angeloashmore/gatsby-source-prismic#330]
I want to add a field in Prismic called `slug` or `directory`. This allows content editors to move pages into certain directories on the site.
Building the site with Gatsby Node all the pages are working and in their correct directories but unfortunately, any links to those pages aren't from inside rich text or other pages don't work.

This is down the Link Resolver only recognising certain attributes - https://prismic.io/docs/technologies/link-resolver-javascript#accessible-attributes

My question is has anyone found a way of making this work? and what was your solution?

**Comment by madeleineostoja** [comment]
I also need this, after using @angeloashmore's suggestion of turning my client's whole site into a single page template (to get around sharing slices), I now need a way of creating structure which I've done with a similar `folder` field to you. Issue is the link resolver is now broken. Reaaally hope this isn't a dead end because I just spent a day convincing my client to go with this approach and refactoring my site 😅

**Comment by madeleineostoja** [comment]
One option is using tags for the folder/slug, but that's pretty messy since it muddies up user data (tags are already used a fair bit in my particular project, as actual tags on projects etc)

**Comment by angeloashmore** [comment]
Hey @jodiedoubleday and @madeleineostoja,

This is what the `fetchLinks` plugin option is for. It allows you to add fields to linked documents. In a general view, Prismic's `fetchLinks` feature is for including additional data when using the REST API. In the case of Gatsby's GraphQL API, we don't need it for that. But we do need to use it to provide linked data to our Link Resolvers.

For example, you could have a Page custom type has a `parent` field that is a content relation field to other Page documents. The link resolver may look something like this:

```js
const linkResolver = (doc) => '/' + [doc.parent?.uid, doc.uid].filter(Boolean).join('/')
```

And the `fetchLinks` plugin option would look like this:

```js
{
  options: {
    fetchLinks: ['page.parent']
  }
}
```

The actual link resolver logic would be specific to your project. But you can see there that you have access to the `doc.parent` field.

**Comment by angeloashmore** [comment]
Also note that outside of RichText fields, you can query the `url` field on documents to get their full URL as resolved by your Link Resolver.

I'm going to close this issue as everything should be working as expected, but feel free to comment/respond if it's not working and I can help out. 👍

**Comment by madeleineostoja** [comment]
Oh I had no idea that you could use fetchlinks in the link resolver, thanks! This source is so solid 🙌

**Comment by madeleineostoja** [comment]
Sorry to be a pain but `fetchLinks` doesn't seem to be working for me. I've switched my setup to the `parent` document link (great idea), but in my link resolver that field is empty (just has a `link_type`). Any idea what I'm doing wrong? 

```js
linkResolver: () => ({ parent, uid }) => `/${[parent?.uid, uid].filter(Boolean).join('/')}`,
fetchLinks: ['project.parent'],
```

Console logging the doc in my link resolver gives me 

```
data: {
    parent: { link_type: 'Document' },
	...
}
```

**Comment by jodiedoubleday** [comment]
@angeloashmore this is great and works a treat. Thank you once again for your amazing help ❤️
