### ISSUE TITLE
Error "TypeError: n is not a function"

### ISSUE THREAD

**Issue by ChristoRibeiro** [angeloashmore/gatsby-source-prismic#34]
Hi,

Got this feedback:

```
error Plugin gatsby-source-prismic returned an error

  TypeError: n is not a function

  - prismic-dom.min.js:1 Object.url
    [website]/[prismic-dom]/dist/prismic-dom.min.js:1:1841

  - normalize.js:97 normalizeLinkField
    [website]/[gatsby-source-prismic]/normalize.js:97:40

  - normalize.js:388 _callee7$
    [website]/[gatsby-source-prismic]/normalize.js:388:47

  - normalize.js:438 normalizeField
    [website]/[gatsby-source-prismic]/normalize.js:438:18

  - normalize.js:461 _callee8$
    [website]/[gatsby-source-prismic]/normalize.js:461:32
```

package.json:

```
    "gatsby": "^1.9.261",
    "gatsby-source-prismic": "^1.0.1",
```

Any idea?

**Comment by angeloashmore** [comment]
Based on the stack trace, the error is coming from a Link field with an internal document. The error comes from using `prismic-dom` to provide the URL of the document.

Could you post your `gatsby-config.js` here as well? I'm wondering what your `linkResolver` function looks like.

**Comment by ChristoRibeiro** [comment]
thanks @angeloashmore, here's my `gatsby-config.js`

```
 {
      resolve: "gatsby-source-prismic",
      options: {
        repositoryName: "myRepositoryName",
        accessToken: "myAccessToken",
        linkResolver: doc => {
          return "/" + doc.uid;
        },
      },
    },
```

**Comment by angeloashmore** [comment]
Ok, I think I understand the problem. The link resolver function should actually be a function that returns another function. This was done to provide the node, key, and value to the link resolver for more granular URL resolving.

https://github.com/angeloashmore/gatsby-source-prismic/blob/master/README.md#how-to-use

```js
// README.md

      // Set a link resolver function used to process links in your content.
      // Fields with rich text formatting or links to internal content use this
      // function to generate the correct link URL.
      // The document node, field key (i.e. API ID), and field value are
      // provided to the function, as seen below. This allows you to use
      // different link resolver logic for each field if necessary.
      // See: https://prismic.io/docs/javascript/query-the-api/link-resolving
      linkResolver: ({ node, key, value }) => doc => {
        // Your link resolver
      },
```

This is different than what the Prismic docs state, so it is a bit confusing.

One way we could make this more in-line with the Prismic documentation is to add `node`, `key`, and `value` to arguments to the link resolver, so it could used like this without the extra function returning:

```js
linkResolver: (doc, node, key, value) => {
  return "/" + doc.uid
}
```

What do you think?

**Comment by ChristoRibeiro** [comment]
Actually, I edited my custom types following [this tutorial](https://user-guides.prismic.io/examples/nodejs-samples/sample-multi-page-site-with-navigation-in-nodejs) and my `linkResolver` is working now. As you pointed, it's a bit confusing.
