### ISSUE TITLE
Slice fragment GQL types not generated if not used in a document

### ISSUE THREAD

**Issue by yoadsn** [angeloashmore/gatsby-source-prismic#35]
Hi Guys,
A limitation exists with the approach this plugin has taken in generating the GQL schema.
Specifically, the Slices dynamic type generation is inferred from the existing slices used in a document. The types would not be generated if not used on any of the documents of that type.
That means that either the code would not work now or would not work when a slice is used for the first time.

For example, assume I have a custom type `Page` with a slice zone and the following three Slices: `Text` and `Quote` and `Title`.

If the `Quote` slice is not used on any of the `Page` document published in the repo - the schema would not generate the `PrismicPageBodyQuote` fragment.
This query would be invalid:
```
{
  allPrismicPage {
    edges {
      node {
        data {
          body {
            ... on PrismicPageBodyText {
              slice_type
            }
            ... on PrismicPageBodyTitle {
              slice_type
            }
            ... on PrismicPageBodyQuote {
              slice_type
            }
          }
        }
      }
    }
  }
}
```
Or in other words the union interface for the field `body___NODE` would not contain the type for the `Quote` slice.

Now, even if I were to force the existence of at least one `Page` with all slices used, this is still fragile since someone might alter that page.

Extremely related to that limitation is the fact that if only one of the slice types is ever used, say only the `Text` slice is ever used - the schema that is generated for `body` is an array of `PrismicPageBodyText` and not a union field.
This makes the schema incompatible since the `__typename` field does not exist on `body` at all. (If I were to query for it).
But this is how Gatsby works see [here](https://github.com/gatsbyjs/gatsby/blob/4ec878d7be89321f4f61035e3282eb1c96dd2b90/packages/gatsby/src/schema/infer-graphql-type.js#L238-L264).

The (logical) assumption Gatsby makes for its developers is that the schema is stable so long as the definition does not change. Data can change with no code changes.
With the behavior described above data changes (adding a slice in the editing room which was never used before) changes the schema.

Suggestions:
- Not sure if possible - but a way to retrieve metadata about types could resolve this (I don't think Prismic has some sort of an introspection API)
- Choose another approach for modeling the GQL schema - instead of making "body" an array of a union - it would be an array of a common type which has `slice_type` and a `payload` field with a JSON serialization of the actual slice data. (Yaiks!)
- If all fails - as a hackish workaround - always push with all documents with a slice zone empty slices with a special "id" that would be ignored by the plugin (I am not sure this is possible)
- And for now, I guess I would have to make sure I always have a single doc with all slices used and ignore that in my queries. (the special id approach - but with a UID).

Sorry, but with an introspection API GQL is not very compatible with Prismic API I guess..

**Comment by angeloashmore** [comment]
Hey @yoadsn, thanks for the detailed explanation. I agree with everything said.

### Slice type unavailable

Right now, Gatsby will only know slice types that are available in the data it fetches. As you found, this means Gatsby will not know about slice types that are not present in at least one document of its type. The only easy solution right now is to save a document with every slice present, as you suggest.

This is a common Gatsby issue, as seen here: [Trying out Gatsby at Work & Co](https://www.gatsbyjs.org/blog/2018-04-11-trying-out-gatsby-at-work-and-co/#schema):

> GraphQL requires all queried fields to be defined in a schema, and Gatsby generates this schema from your site’s existing data. This means, for example, that if you don’t have a Carousel content model on your site right now, but you have a GraphQL query checking for it, the site will fail to build.
>
> The are some really promising discussions on the topic on Github, including an RFC to refactor Gatsby’s schema generation, but in the meantime, most users are getting around this issue by creating placeholder content on Contentful (or whatever their data source is) to guarantee a fully built-up schema.
>
> This got the job done in our case, and we augmented the approach by creating a DummyContentIndex model on Contentful linking to all placeholder content. (In retrospect, I wish I had picked the a more PC name, like ‘PlaceholderContentIndex` 😉.) Using this approach, we could inform our Contentful scripts to make sure placeholder content was copied to the production environment during deploys, so that new models would not break the build.

Specifically for Prismic, you could tag the document with something like "Infrastructure" and mask it out in the Prismic UI.

Ideally, we could query Prismic for the schema of the content type and generate a GraphQL schema to inform Gatsby of the content model. As you mentioned, I don't think Prismic has an API for this, but we should look into that.

Luckily the schema is accessibly in the Prismic UI, so at the very least, a user could copy and paste it into a file for `gatsby-source-prismic` to parse.

I have had problems in the past generating the GraphQL schema for Gatsby using the `setFieldsOnGraphQLNodeType` export, but it's something we should definitely figure out. I know others are running into issues with fields being empty and causing Gatsby's GraphQL interface to blow up.

The fact that Prismic does not allow setting a field as required exacerbates the issue.

### Slice field not a union type

This is a good catch and is obviously pretty annoying. 😄 This related to above where proving an explicit GraphQL schema to Gatsby would help. For now, I think we could limit the schema extension to just tell Gatsby that any slice field should be a union type of its slices, even if there is only one type.

**Comment by angeloashmore** [comment]
Until we figure out the schema extensions, I think it's a good idea to mention the "placeholder document" requirement in the README since this is a common issue.

**Comment by yoadsn** [comment]
Awesome - I really appreciate your detailed response.
I am going with the placeholder approach. When we finish this integration, if it looks polished enough I might PR this into the readme with a small example. :)

**Comment by seaneking** [comment]
Agree with @angeloashmore that this limitation should be mentioned in the README. Makes sense once you think about it, but just tripped me up in prod.

**Comment by chaoky** [comment]
where's the full schema located in prismic?

**Comment by angeloashmore** [comment]
Hi @chaoky, you can find the schema in Prismic under Custom Types. Click on the custom type you need and then select JSON on the far right of the page.

**Comment by yoadsn** [comment]
@camel113 We ended up not going for the Gatsby implementation - sorry - but I have nothing to contribute on this. Next project maybe 🤷‍♂

**Comment by angeloashmore** [comment]
Closing this out as `v3` has been in open beta for a while now and solves this issue. Please give it a try if you haven't yet!
