### ISSUE TITLE
Question: how to prevent or handle GraphQL error

### ISSUE THREAD

**Issue by yvrublevskiy** [angeloashmore/gatsby-source-prismic#36]
Hi Guys,

I have gatsby project which I want to use for 2 different regions (2 different websites). So, I have 2 prismic repositories and 1 gatsby project. All pages are pretty identical. The difference between these two regions' websites is that e.g. region1 will have JoinUs page and region 2 will not. Obviously, when I make a build for region2, getting error "Unknown field `allPrismicJoinUsPage` on type `RootQueryType`" because JoinUs page doesn't exist in region2 prismic repository. How can I handle this? How to prevent this node from being created or exclude this particular page from build? Please, help.

**Comment by angeloashmore** [comment]
Hi @yvrublevskiy, interesting question!

So this is one Gatsby project with two `gatsby-source-plugin` declarations in your `gatsby-config.js`? How are you triggering a build just for region2?

If you have two source plugins in your project, and you build the whole site at once with both regions, all node types should be available. Is there some way you are turning off one source based on which region you want to build? Like using a ENV variable?

**Comment by angeloashmore** [comment]
@yvrublevskiy v3 of the plugin can potentially fix this by providing the `JoinUsPage` JSON schema to the plugin. A v3 beta will be published soon where you can test the fix.

**Comment by angeloashmore** [comment]
Closing this out as `v3` has been in open beta for a while now and solves this issue. Please give it a try if you haven't yet!
