### ISSUE TITLE
How to leverage Gatsby's createSchemaCustomization API to add custom field

### ISSUE THREAD

**Issue by kokiebisu** [angeloashmore/gatsby-source-prismic#369]
I am wanting to create a blog with the read time (example: 4 min read) displayed. I added some code snippet as the following:
```js
const readingTime = require("reading-time")

module.exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions

  if (node.data && Object.keys(node.data) && node.data.body.text) {
    const { text } = node.data.body
    createNodeField({
      node,
      name: "readingTime",
      value: readingTime(text),
    })
  }
}
```

However, the fields were not visible on graphiql and I got an error stating field 'readingTime' cannot be queried when I forcefully try to query. I checked the thread #265 mentioning how using the createSchemaCustomization API, the fields can be customized. It would be great, if either a documentation is provided or clue can be given on it. 

Thanks in advance.

**Comment by angeloashmore** [comment]
Hi @kokiebisu, good question. To add custom fields like you're describing, I would recommend using Gatsby's `createResolvers` API. See the [createResolvers documentation](https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#createresolvers-api).

While you can achieve similar results using `createNodeField` and `createSchemaCustomization`, `createResolvers` is more straightforward and is more flexible. `createNodeField` will modify the base node data within Gatsby and always add your field nested under a `fields` field. On the other hand, `createResolvers` can add fields that can be derived from the base node anywhere in the node.

For your case, you could do something like the following:

```
// gatsby-node.js

const readingTime = require('reading-time')

/**
 * Adds a `ReadingTime` GraphQL type to represent data from the `reading-time` library.
 */
exports.createSchemaCustomization = (gatsbyContext) => {
  const { actions, schema } = gatsbyContext
  const { createTypes } = actions

  const ReadingTime = schema.buildObjectType({
    name: 'ReadingTime',
    fields: {
      text: 'String!',
      minutes: 'Int!',
      time: 'Int!',
      words: 'Int!'
    }
  })

  createTypes([ReadingTime])
}

/**
 * Adds a `readingTime` field to `PrismicBlogPost`.
 *
 * NOTE: This field will only be available during build-time. During a
 * client-side Prismic preview, `readingTime` will not exist. In your
 * templates/components, be sure to handle the case where this field is
 * undefined, such as showing a default "Reading time: XX minutes".
 */
exports.createResolvers = (gatsbyContext) => {
  const { createResolvers } = gatsbyContext

  const resolvers = {
    PrismicBlogPost: {
      readingTime: {
        type: 'ReadingTime',
        resolve: (source) => {
          if (source.data?.body?.text) {
            return readingTime(source.data?.body?.text)
          } else {
            return null
          }
        }
      }
    }
  }

  createResolvers(resolvers)
}
```

This is a more elaborate example where we add a special `ReadingTime` type which includes all data from the `reading-type` package. I would recommend this approach, but if you are looking for something a little simpler in your `gatsby-node.js` file, here is how to add just the reading time string:

```

**Comment by angeloashmore** [comment]
I'm going to close this issue, but feel free to reply back here if this doesn't work as expected. Thanks!

**Comment by kokiebisu** [comment]
Thank you for the polite explanation! Learned a lot:)
