### ISSUE TITLE
GatsbyImage

### ISSUE THREAD

**Issue by RobinHerzog** [angeloashmore/gatsby-source-prismic#37]
Hi,

I do not understand how Prismic + Transformer Sharp works. 

Should the file be offline already on the assets dir ?

**Comment by angeloashmore** [comment]
Hey @RobinHerzog, `gatsby-source-prismic` will download the file from Prismic and perform transformations like resizing automatically. You do not need to download the files yourself in your assets directory.

To make this work, you will need to add the following packages to your project:

```sh
npm i gatsby-plugin-sharp gatsby-transformer-sharp gatsby-image
```

You will then need to update your `gatsby-config.js` file to include the following plugins:

```js
module.exports = {
  plugins: [
    'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: 'repositoryname',
        accessToken: 'accesstoken',
      },
    },
    'gatsby-transformer-sharp',
  ],
}
```

The plugins are in addition to what you already have in your `gatsby-config.js`.'

Once that is setup, you are ready to use image processing ([see here](https://github.com/angeloashmore/gatsby-source-prismic#image-processing)).

Please let me know if you run into issues with this. I think we should also update the README to include the steps listed above for future users.

**Comment by RobinHerzog** [comment]
Hi,
Thanks for reply.

`          imageFieldName {
            localFile {
              childImageSharp {
                ...ImageFragment
              }
            }
          }`

On Prismic my field is called : "full_image" with a url type.

I tried to replace localFile or imageFieldName but it didn't worked. The field are unknown. 
I installed everything in gatsby config.

**Comment by RobinHerzog** [comment]
I was using an old version my bad !

**Comment by angeloashmore** [comment]
Glad you were able to figure out the problem! 😄
