### ISSUE TITLE
"Content Relationship" missing data?

### ISSUE THREAD

**Issue by heart-of-code** [angeloashmore/gatsby-source-prismic#374]
**Current Version: "gatsby-source-prismic": "^3.3.6"**

**Steps taken:** 
In prismic.io, I created two repeatable types. One of them has a content relationship field for pulling in the other type, which contains key text, image, and rich text fields.

**Result:**
using localhost graphql explorer: 
When querying the parent node and digging into the content relationship data, the image fields and key text fields come through fine.  However, the rich text fields are all null.

using prismic.io's hosted graphql explorer:
Everything is present

EDIT: 
I checked the "rawData" field and the rich text fields data _is_ in the raw data on localhost (see image below)

EDIT 2:
I added slices, and they also appear in the "dataRaw" but are not available when queried for directly on localhost

side-by-side query comparison:
![image](https://user-images.githubusercontent.com/8591101/119082852-ec11f980-b9cc-11eb-8e93-9ab9e6c43a0b.png)

image of the localhost query with the parsed fields null and the rawData field that shows the data
![image](https://user-images.githubusercontent.com/8591101/119083482-026c8500-b9ce-11eb-82bd-62949c537070.png)

**Comment by heart-of-code** [comment]
sorry nevermind, I'm just a fool. I had "content-base" for the schema type instead of "content_base"

**Comment by angeloashmore** [comment]
Glad you found the issue! FYI the next version of the plugin will tell you when this kind of error occurs so it’s less of a mystery.
