### ISSUE TITLE
fetchLinks support for specified document types

### ISSUE THREAD

**Issue by simplesessions** [angeloashmore/gatsby-source-prismic#38]
There are some instances where digging deeper into a document that is linked to another document would be very useful up-front so that the linkResolver could build URLs based off of a more complex document relationship.

For instance: If I have an Article document type, and it links to a Category, building a URL based off of a data field in a Category instance that's linked from this Article involves handing Prismic an additional [fetchLinks](https://prismic.io/docs/javascript/query-the-api/fetch-linked-document-fields#0_0-the-fetchlinks-option) key that hints at what kind of data should be available.

The result should be that when in the linkResolver function, when handling the right doc type, we should be able to access the doc's data property and drill down into the content relationship / link to pull out whatever was specific in fetchLinks.

**Comment by simplesessions** [comment]
@angeloashmore Yup, that sounds about right. That is interesting about being able to use the existing data to add that information in post-fetch, but besides the caveat you mentioned, I'm not sure if it would gum up everything trying to match the right data with the right doc type and/or slow something down *shrug*

I've only ever used fetchLinks while querying for a single document, so I'm not sure, but I think you would add it in as an option here:

https://github.com/angeloashmore/gatsby-source-prismic/blob/cdd08bf916ba9c6c5d7cd41ffa8b10035b954a8e/src/fetch.js#L35-L39

I can do some more research to see how it does/doesn't work when querying everything versus just the one record.

**Comment by angeloashmore** [comment]
I'm wondering what the best way to construct the value of `fetchLinks`. A couple of options:

1. Let the user provide it in `gatsby-config.js` and pass it to `client.query` directly
1. Query all documents, get a list of the fields for all types, and query all the documents again with all fields listed in `fetchLinks`
1. Let the user provide a list of custom types and perform the above, but only for those types (less network delays, and off by default)

I think option 1 is our best bet. It's the simplest and is probably what most people would expect. Options 2 and 3 could be a little too magical and with too much complexity.
