### ISSUE TITLE
[v4] build failed on Gatsby Cloud

### ISSUE THREAD

**Issue by cometkim** [angeloashmore/gatsby-source-prismic#385]
![image](https://user-images.githubusercontent.com/9696352/120152276-3f374800-c228-11eb-9f45-db99301e4b11.png)

It seems Gatsby Cloud use pretty old version of nodejs 😅

**Comment by cometkim** [comment]
replace `import fs from 'fs/promises'` by `import { promises: fs } from 'fs'` is fine

**Comment by angeloashmore** [comment]
Oops! Thanks for sharing that.

Fixed in e120087f47a36bc24ea2d85b3fa714fcc0a23a9e, published in `v4.0.0-beta.12`.
