### ISSUE TITLE
Netlify build fails: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by emrysgraefe** [angeloashmore/gatsby-source-prismic#388]
Works locally with gatsby develop or gatsby build. Fails on Netlify.

[Link to repo.](https://github.com/emrysgraefe/gatsby-prismic-multilingual)

9:36:17 AM: Build ready to start
9:36:19 AM: build-image version: 0582042f4fc261adc7bd8333f34884959c577302
9:36:19 AM: build-image tag: v3.7.6
9:36:19 AM: buildbot version: 0e23307adb9080898b837c5147a17e2f7890cb10
9:36:19 AM: Fetching cached dependencies
9:36:20 AM: Starting to download cache of 156.8MB
9:36:24 AM: Finished downloading cache in 5.049259178s
9:36:24 AM: Starting to extract cache
9:36:30 AM: Finished extracting cache in 5.1980837s
9:36:30 AM: Finished fetching cache in 10.282386944s
9:36:30 AM: Starting to prepare the repo for build
9:36:30 AM: Preparing Git Reference refs/heads/main
9:36:31 AM: Parsing package.json dependencies
9:36:32 AM: Starting build script
9:36:32 AM: Installing dependencies
9:36:32 AM: Python version set to 2.7
9:36:32 AM: Started restoring cached node version
9:36:34 AM: Finished restoring cached node version
9:36:35 AM: v12.18.0 is already installed.
9:36:36 AM: Now using node v12.18.0 (npm v6.14.4)
9:36:36 AM: Started restoring cached build plugins
9:36:36 AM: Finished restoring cached build plugins
9:36:36 AM: Attempting ruby version 2.7.1, read from environment
9:36:37 AM: Using ruby version 2.7.1
9:36:37 AM: Using PHP version 5.6
9:36:37 AM: Started restoring cached node modules
9:36:37 AM: Finished restoring cached node modules
9:36:38 AM: Installing NPM modules using NPM version 6.14.4
9:36:52 AM: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!npm WARN eslint-config-react-app@6.0.0 requires a peer of babel-eslint@^10.0.0 but none is installed. You must install peer dependencies yourself.
9:36:52 AM: npm WARN express-graphql@0.9.0 requires a peer of graphql@^14.4.1 but none is installed. You must install peer dependencies yourself.
9:36:52 AM: npm WARN ts-node@9.1.1 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
9:36:52 AM: npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
9:36:52 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
9:36:52 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
9:36:52 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
9:36:52 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
9:36:52 AM: added 63 packages from 33 contributors, removed 14 packages, updated 1 package and audited 2225 packages in 13.796s
9:36:53 AM: 226 packages are looking for funding
9:36:53 AM:   run `npm fund` for details
9:36:53 AM: found 4 vulnerabilities (2 moderate, 2 high)
9:36:53 AM:   run `npm audit fix` to fix them, or `npm audit` for details
9:36:53 AM: NPM modules installed
9:36:54 AM: Started restoring cached go cache
9:36:54 AM: Finished restoring cached go cache
9:36:54 AM: go version go1.14.4 linux/amd64
9:36:54 AM: go version go1.14.4 linux/amd64
9:36:54 AM: Installing missing commands
9:36:54 AM: Verify run directory
9:36:54 AM: ​
9:36:54 AM: ────────────────────────────────────────────────────────────────
9:36:54 AM:   Netlify Build                                                 
9:36:54 AM: ────────────────────────────────────────────────────────────────
9:36:54 AM: ​
9:36:54 AM: ❯ Version
9:36:54 AM:   @netlify/build 11.29.2
9:36:54 AM: ​
9:36:54 AM: ❯ Flags
9:36:54 AM:   deployId: 60b637d191e94800072312f8
9:36:54 AM: ​
9:36:54 AM: ❯ Current directory
9:36:54 AM:   /opt/build/repo
9:36:54 AM: ​
9:36:54 AM: ❯ Config file
9:36:54 AM:   No config file was defined: using default values.
9:36:54 AM: ​
9:36:54 AM: ❯ Context
9:36:54 AM:   production
9:36:54 AM: ​
9:36:54 AM: ────────────────────────────────────────────────────────────────
9:36:54 AM:   1. Build command from Netlify app                             
9:36:54 AM: ────────────────────────────────────────────────────────────────
9:36:54 AM: ​
9:36:54 AM: $ npm run build
9:36:54 AM: > prismic-multilingual@1.0.0 build /opt/build/repo
9:36:54 AM: > gatsby build
9:36:57 AM: info The following flags are active:
9:36:57 AM: - PRESERVE_FILE_DOWNLOAD_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't delete the downloaded files cache when changing gatsby-node.js & gatsby-config.js files.
9:36:57 AM: - PRESERVE_WEBPACK_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Use webpack's persistent caching and don't delete webpack's cache when changing gatsby-node.js & gatsby-config.js files.
9:36:57 AM: There are 2 other flags available that you might be interested in:
9:36:57 AM: - PARALLEL_SOURCING · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/parallel-sourcing-feedback)) · Run all source plugins at the same time instead of serially. For sites with multiple source plugins, this can speedup sourcing and transforming considerably.
9:36:57 AM: - FUNCTIONS · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/functions-feedback)) · Compile Serverless functions in your Gatsby project and write them to disk, ready to deploy to Gatsby Cloud
9:36:57 AM: success open and validate gatsby-configs - 0.030s
9:36:58 AM: error Error in "/opt/build/repo/node_modules/gatsby-plugin-prismic-previews/gatsby-node.js": Cannot find module 'fs/promises'
9:36:58 AM: Require stack:
9:36:58 AM: - /opt/build/repo/node_modules/gatsby-plugin-prismic-previews/dist/gatsby-node.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby-plugin-prismic-previews/gatsby-node.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/services/initialize.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/services/index.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/bootstrap/index.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/commands/build.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby-cli/lib/create-cli.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby-cli/lib/index.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/dist/bin/gatsby.js
9:36:58 AM: - /opt/build/repo/node_modules/gatsby/cli.js
9:36:58 AM: 
9:36:58 AM: 
9:36:58 AM:   Error: Cannot find module 'fs/promises'
9:36:58 AM:   Require stack:
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby-plugin-prismic-previews/dist/gatsby-node  .js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby-plugin-prismic-previews/gatsby-node.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js  - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/dist/services/initialize.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/dist/services/index.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/dist/bootstrap/index.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/dist/commands/build.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby-cli/lib/create-cli.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby-cli/lib/index.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/dist/bin/gatsby.js
9:36:58 AM:   - /opt/build/repo/node_modules/gatsby/cli.js
9:36:58 AM:   
9:36:58 AM:   - loader.js:966 Function.Module._resolveFilename
9:36:58 AM:     internal/modules/cjs/loader.js:966:15
9:36:58 AM:   
9:36:58 AM:   - loader.js:842 Function.Module._load
9:36:58 AM:     internal/modules/cjs/loader.js:842:27
9:36:58 AM:   
9:36:58 AM:   - loader.js:1026 Module.require
9:36:58 AM:     internal/modules/cjs/loader.js:1026:19
9:36:58 AM:   
9:36:58 AM:   - v8-compile-cache.js:159 require
9:36:58 AM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
9:36:58 AM:   
9:36:58 AM:   - constants.ts:1 Object.<anonymous>
9:36:58 AM:     [repo]/[gatsby-plugin-prismic-previews]/src/constants.ts:1:1
9:36:58 AM:   
9:36:58 AM:   - v8-compile-cache.js:192 Module._compile
9:36:58 AM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:192:30
9:36:58 AM:   
9:36:58 AM:   - loader.js:1158 Object.Module._extensions..js
9:36:58 AM:     internal/modules/cjs/loader.js:1158:10
9:36:58 AM:   
9:36:58 AM:   - loader.js:986 Module.load
9:36:58 AM:     internal/modules/cjs/loader.js:986:32
9:36:58 AM:   
9:36:58 AM:   - loader.js:879 Function.Module._load
9:36:58 AM:     internal/modules/cjs/loader.js:879:14
9:36:58 AM:   
9:36:58 AM:   - loader.js:1026 Module.require
9:36:58 AM:     internal/modules/cjs/loader.js:1026:19
9:36:58 AM:   
9:36:58 AM:   - v8-compile-cache.js:159 require
9:36:58 AM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:159:20
9:36:58 AM:   
9:36:58 AM:   - gatsby-node.js:1 Object.<anonymous>
9:36:58 AM:     [repo]/[gatsby-plugin-prismic-previews]/gatsby-node.js:1:80
9:36:58 AM:   
9:36:58 AM:   - v8-compile-cache.js:192 Module._compile
9:36:58 AM:     [repo]/[v8-compile-cache]/v8-compile-cache.js:192:30
9:36:58 AM:   
9:36:58 AM:   - loader.js:1158 Object.Module._extensions..js
9:36:58 AM:     internal/modules/cjs/loader.js:1158:10
9:36:58 AM:   
9:36:58 AM:   - loader.js:986 Module.load
9:36:58 AM:     internal/modules/cjs/loader.js:986:32
9:36:58 AM:   
9:36:58 AM:   - loader.js:879 Function.Module._load
9:36:58 AM:     internal/modules/cjs/loader.js:879:14
9:36:58 AM:   
9:36:58 AM: 
9:36:58 AM: not finished load plugins - 1.115s
9:36:58 AM: npm ERR! code ELIFECYCLE
9:36:58 AM: npm ERR! errno 1
9:36:58 AM: npm ERR! prismic-multilingual@1.0.0 build: `gatsby build`
9:36:58 AM: npm ERR! Exit status 1
9:36:58 AM: npm ERR!
9:36:58 AM: npm ERR! Failed at the prismic-multilingual@1.0.0 build script.
9:36:58 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
9:36:58 AM: npm ERR! A complete log of this run can be found in:
9:36:58 AM: npm ERR!     /opt/buildhome/.npm/_logs/2021-06-01T13_36_58_632Z-debug.log
9:36:58 AM: ​
9:36:58 AM: ────────────────────────────────────────────────────────────────
9:36:58 AM:   "build.command" failed                                        
9:36:58 AM: ────────────────────────────────────────────────────────────────
9:36:58 AM: ​
9:36:58 AM:   Error message
9:36:58 AM:   Command failed with exit code 1: npm run build
9:36:58 AM: ​
9:36:58 AM:   Error location
9:36:58 AM:   In Build command from Netlify app:
9:36:58 AM:   npm run build
9:36:58 AM: ​
9:36:58 AM:   Resolved config
9:36:58 AM:   build:
9:36:58 AM:     command: npm run build
9:36:58 AM:     commandOrigin: ui
9:36:58 AM:     environment:
9:36:58 AM:       - GATSBY_PRISMIC_CONTAINER_NAME
9:36:58 AM:       - PRISMIC_ACCESS_TOKEN
9:36:58 AM:     publish: /opt/build/repo/public
9:36:58 AM:   functions:
9:36:58 AM:     '*': {}
9:36:59 AM: Caching artifacts
9:36:59 AM: Started saving node modules
9:36:59 AM: Finished saving node modules
9:36:59 AM: Started saving build plugins
9:36:59 AM: Finished saving build plugins
9:36:59 AM: Started saving pip cache
9:36:59 AM: Finished saving pip cache
9:36:59 AM: Started saving emacs cask dependencies
9:36:59 AM: Finished saving emacs cask dependencies
9:36:59 AM: Started saving maven dependencies
9:36:59 AM: Finished saving maven dependencies
9:36:59 AM: Started saving boot dependencies
9:36:59 AM: Finished saving boot dependencies
9:36:59 AM: Started saving rust rustup cache
9:36:59 AM: Finished saving rust rustup cache
9:36:59 AM: Started saving go dependencies
9:36:59 AM: Finished saving go dependencies
9:36:59 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
9:36:59 AM: Creating deploy upload records
9:36:59 AM: Failing build: Failed to build site
9:36:59 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
9:36:59 AM: Finished processing build request in 39.737851158s

**Comment by emrysgraefe** [comment]
Remedied by using specifying Node v14.15.4. Maybe add this to the documentation?

**Comment by angeloashmore** [comment]
Hey @emrysgraefe, thanks for reporting this. This issue was fixed in `v4.0.0-beta.12`. Could you upgrade to the latest version and try it again?

**Comment by emrysgraefe** [comment]
Thanks @angeloashmore, can confirm no issues building on Netlify with the latest version.
