### ISSUE TITLE
allPrismicDocument ?

### ISSUE THREAD

**Issue by RobinHerzog** [angeloashmore/gatsby-source-prismic#39]
Is there a way to get again `allPrismicDocument`? 

My project is totally dependents from that.

**Comment by RobinHerzog** [comment]
Example Node-Gatsby

`    const result = await graphql(
      `
        query route {
          allPrismicDocument {
            edges {
              node {
                id
                lang
                type
                data {
                  body {
                    primary {
                      slug
                      route
                      layout
                    }
                  }
                }
              }
            }
          }
        }
      `
    );`

I have up to 15 custom type.

**Comment by RobinHerzog** [comment]
Hi there,

Have any one a solution :) ?

**Comment by angeloashmore** [comment]
Hi @RobinHerzog, sorry it took me a while to respond here. Haven't had much free time lately.

There isn't a way to get `allPrismicDocument` since it was changed out for more specific nodes types based on the content type. You could still create a fragment like the following:

```graphql
query AllDocuments {
  allPrismicContentType1 {
    ...DocumentFragment
  }
  allPrismicContentType2 {
    ...DocumentFragment
  }
  # ...
  allPrismicContentTypeN {
    ...DocumentFragment
  }
}

fragment DocumentFragment {
  edges {
    node {
      id
      lang
      type
      data {
        body {
          primary {
            slug
            route
            layout
          }
        }
      }
    }
  }
}
```

If the fragment doesn't work in `exports.onCreatePage` (not sure if fragments are supported there), you could create the string using JavaScript string interpolation or map an array to build the query string.

```js
const documentFragment = `
  edges {
    node {
      id
      lang
      type
      data {
        body {
          primary {
            slug
            route
            layout
          }
        }
      }
    }
  }
`

const query = `
  query AllDocuments {
    allPrismicContentType1 {
      ${documentFragment}
    }
    allPrismicContentType2 {
      ${documentFragment}
    }
    # ...
    allPrismicContentTypeN {
      ${documentFragment}
    }
  }
`
```

Or...

```js
const documentFragment = `
  edges {
    node {
      id
      lang
      type
      data {
        body {
          primary {
            slug
            route
            layout
          }
        }
      }
    }
  }
`
const contentTypes = ['ContentType1', 'ContentType2', 'ContentTypeN']
const allDocumentsFragment = contentTypes.map(
  type => `allPrismic${type}{${documentFragment}}`
)

const query = `
  query AllDocuments {
    ${allDocumentsFragment}
  }
`
```

**Comment by RobinHerzog** [comment]
I was thinking about that. Thanks for the help !
