### ISSUE TITLE
Error while running the sourceNodes lifecycle when I attempt to change a field type

### ISSUE THREAD

**Issue by tjjjwxzq** [angeloashmore/gatsby-source-prismic#391]
This seems like a bug, where `gatsby-source-prismic` throws the following error on build after I changed a field on a custom type in my schema JSON file from key text to rich text. Running `gatsby clean` does not help.

The app builds fine when that field is removed, or reverted to the old type, or simply renamed but with the new type.

`gatsby-source-prismic` v3.3.6

```
"gatsby-source-prismic" threw an error while running the sourceNodes
lifecycle:

e.reduce is not a function

  61 | }
  62 |
> 63 | const buildAll = async (
     |               ^
  64 |   pluginOptions: PluginOptions,
  65 |   gatsbyContext: SourceNodesArgs,
  66 |   typePaths: TypePath[],

File: node_modules/gatsby-source-prismic/src/gatsby-node.ts:63:15



  TypeError: e.reduce is not a function

  - prismic-dom.min.js:1 Function.value
  - [project]/[prismic-dom]/dist/prismic-dom.min.js:1:9753

  - prismic-dom.min.js:1 Object.t.default

[project]/[prismic-dom]/dist/prismic-dom.min.js:1:17350

  - prismic-dom.min.js:1 Object.asHtml

[project]/[prismic-dom]/dist/prismic-dom.min.js:1:4903

  - environment.node.ts:170 env
    [project]/[gatsby-source-prismic]/src/environment.n
ode.ts:17    0:3

  - documentsToNodes.ts:89 env
    [project]/[gatsby-source-prismic]/src/documentsToNo
des.ts:89    :77

  - documentsToNodes.ts:196
    [project]/[gatsby-source-prismic]/src/documentsToNo
des.ts:19    6:65

  - utils.ts:100 key

[project]/[gatsby-source-prismic]/src/utils.ts:100:5

  - Array.map

  - utils.ts:101 normalizeObj

[project]/[gatsby-source-prismic]/src/utils.ts:101:40

  - documentsToNodes.ts:196 normalizedData
    [project]/[gatsby-source-prismic]/src/documentsToNo
des.ts:19    6:36

  - documentsToNodes.ts:211 doc
    [project]/[gatsby-source-prismic]/src/documentsToNo
des.ts:21    1:9

  - environment.node.ts:29 createContentDigest
    [project]/[gatsby-source-prismic]/src/environment.n
ode.ts:29    :3

  - Array.map

  - documentsToNodes.ts:202 L
    [project]/[gatsby-source-prismic]/src/documentsToNo
des.ts:20    2:9

  - gatsby-node.ts:63
    [project]/[gatsby-source-prismic]/src/gatsby-node.t
s:63:15

  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
  ```

This is the only change:
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/11689299/121352199-300a7580-c95f-11eb-8a17-08211909152b.png">

**Comment by angeloashmore** [comment]
Hi @tjjjwxzq,

This happens because the documents in your Prismic repository probably are still formatted as Key Text rather than Rich Text. Key Text is returned as a string while Rich Text is an array of objects.

The plugin expects the fields' values to be Rich Text according to the schema and so it converts it to HTML and text. This will throw an error when it is given a string, however.

When converting from Key Text to Rich Text (and vice versa), you will need to go into each document and resave the contents. The easiest way to do this is to type a character into a field and then remove that character. This enables you to save a new version of the document where the Rich Text field is now properly updated.

**Comment by tjjjwxzq** [comment]
Thanks for the explanation! That makes sense...though it's not a very obvious gotcha 🙃

**Comment by angeloashmore** [comment]
You're welcome! I wish the content would be converted for you automatically in Prismic, but unfortunately that is not how it works right now. That certainly can be confusing, however.
