### ISSUE TITLE
[v4] Deleted custom types trigger errors at build time

### ISSUE THREAD

**Issue by benjaminwaterlot** [angeloashmore/gatsby-source-prismic#393]
Hello @angeloashmore !

### Description

When I `disable`, then `delete` a Custom Type, the build crashes because `gatsby-source-prismic` **still expects its schema to be present**, but the `customTypesApi` doesn't return it anymore.

The result is this error : 

<img width="480" alt="Screenshot 2021-06-14 at 10 41 42" src="https://user-images.githubusercontent.com/32556322/121864758-8aa82680-ccfd-11eb-97f5-b6a3e0e0d9cb.png">

### Details
I'm on the version `4.0.0-beta.15`, with a new Prismic repository.

### Workaround
The workaround is to recreate a Custom type with the same type `id`, in my case `site_heade`, and keep it disabled.

**Comment by angeloashmore** [comment]
Hi @benjaminwaterlot, thank you for trying out the V4 beta!

Although those Custom Types have been deleted, they are still part of your repository's content from a previous point in time. This means `gatsby-source-prismic` is expecting a schema to exist, even if you are not using the custom type anymore.

The plugin allows you to provide an empty schema for these kinds of Custom Types. Taken from the [V3 to V4 migration guide](https://github.com/angeloashmore/gatsby-source-prismic/blob/beta/packages/gatsby-source-prismic/docs/migrating-from-v3-to-v4.md#provide-all-custom-type-schemas), see the `an_unused_type` schema:

```diff
// gatsby-config.js

  plugins: [
    {
      resolve: 'gatsby-source-prismic',
      options: {
        schemas: {
          page: require('./schemas/page.json'),

+         // If you are missing any custom type schemas, add them to the
+         // `schemas` plugin option.
+         blog_post: require('./schemas/page.json'),

+         // If a custom type was used at one point but has since been removed,
+         // you may pass an empty schema.
+         an_unused_type: {},
        },
      },
    },
  ]
```

Once an empty schema is provided in the config, you can remove the Custom Type from your repository.

The official documentation is being updated to include this information. You can read a little more about the decision to throw an error in this situation toward the end of this comment: https://github.com/angeloashmore/gatsby-source-prismic/issues/377#issuecomment-850644839

Thanks!
