### ISSUE TITLE
503 status code at Gatsby develop

### ISSUE THREAD

**Issue by theo-ford** [angeloashmore/gatsby-source-prismic#398]
``` 
ERROR #11321  PLUGIN

"gatsby-source-prismic" threw an error while running the sourceNodes lifecycle:

Error: Unexpected status code [503] on URL https://***.prismic.io/api/v2?access_token=****

 - prismic-javascript.min.js:1 
    [****]/[prismic-javascript]/dist/prismic-javascript.min.j
    s:1:16499
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
```

Keep getting this error when trying to setup a new gatsby / prismic project. GraphiQL is recognising the content fields but not returning any data. Can't seem to get past it when running gatsby develop, having got the configuration working on other projects. 

Does anyone have a clue about how to fix it?

**Comment by angeloashmore** [comment]
Hi @theo-ford, could you run `gatsby info` in your project and post the result here? I'm most interested in the version of `gatsby-source-prismic`.

Thanks!

**Comment by theo-ford** [comment]
Hi @angeloashmore, thanks for getting back. Please see below:  

```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 84.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.24.67 => 2.32.2
    gatsby-plugin-imgix: ^0.9.0 => 0.9.0
    gatsby-plugin-layout: ^1.3.12  => 1.10.0
    gatsby-plugin-manifest: ^2.4.33 => 2.12.0
    gatsby-plugin-react-helmet: ^3.3.12 => 3.10.0
    gatsby-plugin-styled-components: ^3.3.12 => 3.10.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-prismic: ^3.2.1 => 3.3.3
  npmGlobalPackages:
    gatsby-cli: 3.3.0
```

**Comment by angeloashmore** [comment]
Hey @theo-ford, it looks like there was a Prismic API issue yesterday and should be fixed now. Related forum thread: https://community.prismic.io/t/503-error-when-query-api/5926

Are you still experiencing this issue?

**Comment by angeloashmore** [comment]
I'm going to close this issue as it should be resolved but please let me know if this is still ongoing. Thanks!

**Comment by theo-ford** [comment]
Thanks for getting back in touch. Yes you're right the issue seems to have resolved itself.

Many thanks!
