### ISSUE TITLE
Option to maintain original image name when using createRemoteFileNode

### ISSUE THREAD

**Issue by simplesessions** [angeloashmore/gatsby-source-prismic#40]
Currently, integration with `gatsby-image`/`gatsby-plugin-sharp` creates images that are fully hashed. However, it would be great to append the original filename to the end of the filename before the `ext`.

This mainly benefits SEO, but it also helps to quickly identify them when scanning through code and looking at resources when testing loading.

This matches the way Prismic handles their images, e.g.

- filename: `i-like-to-eat-babies.jpg`
- served as: `299426612ab3f0385acd5cf114ab263b85778379_i-like-to-eat-babies.jpg`

**Comment by angeloashmore** [comment]
I have to look more into this. I'm not sure where in `gatsby-plugin-sharp` or `gatsby-transformer-sharp` transforms the filename. It might even be in `gatsby-source-filesystem` since `gatsby-source-prismic` uses `createRemoteFileNode` from that package.

That's a lot of `gatsby-`s.

**Comment by simplesessions** [comment]
Looks like we're out of luck for the short-term:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L190-L191

Where `createHash()` is https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L56-L60

An ideal situation would be to at least provide some regex to run against the original URL to pluck the original filename in cases like Prismic where a hash is already prepended, then tell `createRemoreFileNode` to prefix the result to the hash: `${hash}_${filename}.${ext}`

**Comment by angeloashmore** [comment]
Looks like there may be some hope here: https://github.com/gatsbyjs/gatsby/issues/3132

**Comment by angeloashmore** [comment]
Closing out this ancient issue. This is present in `gatsby-source-filesystem` now.
