### ISSUE TITLE
[v4] `gatsbyImageData` graphQL params are not taken into account in preview mode

### ISSUE THREAD

**Issue by benjaminwaterlot** [angeloashmore/gatsby-source-prismic#400]
Hello @angeloashmore :)

I'm trying to display simple images of authors, coming from Prismic, in a fixed 40px width/height container, but with a relevant `srcSet` for High DPI screens. Setting height/width constraints directly on Prismic does not answer this requirement (it renders blurry images on Retina screens).

When querying for my image in the GraphQL query, I can specify params for the `gatsbyImageData` field, but they seem to be fully ignored.

Notably : 

```graphql
  author_picture {
    gatsbyImageData(width: 40, height: 40)
    alt
  }
```

doesn't change anything on the resulting object, which still is:

```js
{
    "images": {
        "sources": [],
        "fallback": {
            "src": "https://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=1112&h=1112",
            "srcSet": "https://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=100&h=100 100w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=116&h=116 116w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=135&h=135 135w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=156&h=156 156w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=181&h=181 181w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=210&h=210 210w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=244&h=244 244w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=283&h=283 283w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=328&h=328 328w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=380&h=380 380w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=441&h=441 441w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=512&h=512 512w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=594&h=594 594w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=689&h=689 689w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=799&h=799 799w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=927&h=927 927w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=1075&h=1075 1075w,\nhttps://images.prismic.io/shine/a3781cac-8211-4bae-af89-75c2b9bdf1e1_photo-1_facture_sur_2_est_payee_....png?ixlib=gatsbyFP&auto=compress%2Cformat&q=80&w=1112&h=1112 1112w",
            "sizes": "(min-width: 1112px) 1112px, 100vw"
        }
    },
    "layout": "constrained",
    "width": 1112,
    "height": 1112
}
```

Note that `1112` is the original height and width of the image.
It's still in `width` and `height` fields, and in `fallback.sizes`.

I tried to set the following fields to appropriate values and saw no differences either (the below resulting object doesn't change in any way):

```
srcSetMinWidth
srcSetMaxWidth
outputPixelDensities
sizes
```

---

I'm on `gatsby-source-prismic` version `4.0.0-beta.17`.

**Comment by angeloashmore** [comment]
Hey @benjaminwaterlot,

I tested this in the `test-site` directory of this repository (in the beta branch) and could not get the same result. If I set `width: 50, height: 50` for example, the resulting data sets width to 50 and height to 50.

Could you try running `gatsby clean` to clear the cache and try again? If that does not make a difference, could you try running `npm update @imgix/gatsby` (or if you use yarn: `yarn update @imgix/gatsby`).

---

Regarding blurry images on Retina displays when setting the width/height in Prismic, I would recommend setting the dimensions at least 2x what you actually need. If you want a `40x40` image, for example, set the dimensions to `80x80` or higher.

You will still need to set the displayed output to `40x40` in your Gatsby project (via `gatsbyImageData` or CSS), but now the source image will have at least 2x DPI.

**Comment by benjaminwaterlot** [comment]
Hello @angeloashmore,

I just realised this error only happened on preview mode (I dev in preview to get realtime CMS updates), and thought about the limitations I read in the documentation.

It is [documented here](https://github.com/angeloashmore/gatsby-source-prismic/blob/beta/packages/gatsby-plugin-prismic-previews/docs/limitations.md#image-processing), and is due to the fact that arguments cannot be passed to preview queries. I'll replicate the sizing constraints in CSS.

Thanks for your answer, I'm closing the issue :)

**Comment by angeloashmore** [comment]
Ah, I see. Yes, previews will not include GraphQL parameters since there is no GraphQL server at that time.

There's a separate issue to track this here: https://github.com/angeloashmore/gatsby-source-prismic/issues/342

This isn't a priority right now since this can be resolved in projects with CSS for the most part. There are some methods we could explore in the future. Thanks!
