### ISSUE TITLE
[v4] Image urls are wrong

### ISSUE THREAD

**Issue by DevSide** [angeloashmore/gatsby-source-prismic#404]
After uploading an image named "myimage@2x", the final url from prismic api is:
"https://images.prismic.io/{REPOSITORY}/{ID}_myimage%402x.jpg?auto=compress,format"

The final url after the plugin ran should be:
"https://images.prismic.io/{REPOSITORY}/{ID}_myimage%402x.jpg?ixlib=gatsbyFP&auto=compress,format&w={WIDTH}&h={HEIGHT}"

Instead, a double encoding occurred (it looks like the url was not decoded first):
"https://images.prismic.io/{REPOSITORY}/{ID}_myimage%25402x.jpg?ixlib=gatsbyFP&auto=compress%2Cformat&w={WIDTH}&h={HEIGHT}"

Version: v4.0.0-beta.17

**Comment by angeloashmore** [comment]
Thanks @DevSide, I'll take a look at this. Until a fix is published, you should be able to use an image without a `@` character in the filename.

**Comment by DevSide** [comment]
I found the problem, i'm making a PR.

**Comment by angeloashmore** [comment]
Closing as the PR has been merged. Please comment if it's still an issue and I'll reopen. 👍
