### ISSUE TITLE
Displaying outputted HTML

### ISSUE THREAD

**Issue by MathRivest** [angeloashmore/gatsby-source-prismic#41]
I am currently trying out the new version of the plugin and it works great!

Once I retrieve the html, I would usually use `Prismic-reactjs` rich text to display HTML using the type and text but now that I have the html field I'm not sure what to use. I'm trying to avoid having to use `dangerouslySetInnerHTML={{ __html: page.title.html }}`.

Maybe I missed something?

Anyway, the latest version is everything I needed for prismic integration! Thank you

**Comment by angeloashmore** [comment]
Glad the new version is working out well for you!

`dangerouslySetInnerHTML={{ __html: page.title.html }}` is the way to go here. The HTML is sanitized by Prismic and `prismic-dom`.

If you would rather use `prismic-reactjs` or `prismic-dom` directly, you still have access to the "raw" data on the `raw` field, a sibling to `html`:

```graphq
{
  prismicPage(id: {eq: $id }) {
    data {
      title {
        raw {
          type
          text
          spans
        }
      }
    }
  }
}
```

Sorry, I can't remember off the top of my head what the subfields of `raw` is, but it should be something like that.

Again, I do recommend using the `html` key instead. This reduces the amount of processing time client-side, reduces your bundle size, and reduces the amount of code you need to write.

Let me know if there's an advantage to using `prismic-reactjs` though, as I haven't used it before. :smile:

**Comment by MathRivest** [comment]
Thank you for your answer. The only problems I see right now are that is seems very hacky to use `dangerouslySetInnerHTML` and that is adds an extra dom element. I can probably have a component to wrap it so it looks better to other devs in the code. Thank you !

**Comment by angeloashmore** [comment]
No problem, always open to suggestions if you have any!
