### ISSUE TITLE
Gatsby v2 compatibility

### ISSUE THREAD

**Issue by seaneking** [angeloashmore/gatsby-source-prismic#42]
Now that Gatsby v2 is getting closer to release, would be great to spin up a v2 branch for `gatsby-source-prismic` and publish to an `next` tag on NPM to keep in line with the rest of the ecosystem.

Not remotely familiar with how Gatsby sources work, but ran into issues straight away, source-filesystem validation complains about the data coming out of Prismic:

```
The new node didn't pass validation
ValidationError: child "internal" fails because ["description" is not allowed]
```

**Comment by angeloashmore** [comment]
Thanks for bringing this up. It looks like Gatsby v2 is coming up soon. 🎉

I updated the plugin for v2 compat and published it under the `next` tag.

Changes: https://github.com/angeloashmore/gatsby-source-prismic/commit/1c178514e1aaa9bd0e06b863679b3d1fa89127f4

**Comment by seaneking** [comment]
Awesome! Will try this out today and report back

**Comment by angeloashmore** [comment]
Something worth bringing up is the new `createNodeId` feature. The plugin currently uses `generateNodeId` from `gatsby-node-helpers` that generates a namespaced ID using the existing ID. It appears using `createNodeId` to generate a UUID is the norm going forward for Gatsby v2, so we should probably swap to that instead.

Luckily `createNodeId` will always return the same ID for a given namespace and ID, so it will work in the same manner as `generateNodeId`

**Comment by seaneking** [comment]
Just tried out the v2 alpha and it works a treat 👍 Thanks!

Not sure what the process is, but have you considered asking for this source to be made official in the Gatsby monorepo? It's super solid, especially since the v1.

**Comment by angeloashmore** [comment]
`v2.0.0` published with Gatsby v2 support!

https://www.npmjs.com/package/gatsby-source-prismic/v/2.0.0

I'd like to keep it out of the monorepo for now as I use this plugin for work. I think once I get a few more websites built with it and features stabilize, we can look at what it takes to get it into the monorepo.
