### ISSUE TITLE
Suggestions for linking parent and child nodes? 

### ISSUE THREAD

**Issue by ktbee** [angeloashmore/gatsby-source-prismic#47]
I have [a content relationship field in Prismic](https://user-guides.prismic.io/content-modeling-and-custom-types/structure-your-content/setting-up-and-retrieving-hierarchical-content) that I'm using to set what should be the parent of a page. Do you have suggestions for how to implement this relationship in Gatsby with the `gatsby-source-prismic` plugin?  I noticed that Gatsby has a built-in [createParentChildLink](https://www.gatsbyjs.org/docs/bound-action-creators/#createParentChildLink) function, but it only works for creating new children nodes, which the `gatsby-source-prismic`. Currently this is what I've attempted in `gatsby-node.js`:

```
exports.onCreateNode = async ({ node, getNode, boundActionCreators }) => {
  const { createParentChildLink } = boundActionCreators

  if (node.data && node.data.parent_page) {
    let parentNodeId = node.data.parent_page.document___NODE[0];
    let parentNode = getNode(parentNodeId);
    createParentChildLink({ parent: parentNode, child: node })
  }
}
```

This gives me the following error: `TypeError: Cannot read property 'children' of undefined`

Any suggestions greatly appreciated!

**Comment by angeloashmore** [comment]
Hi @ktbee, the parent data should be available on the `document` field under the content relationship field you set in Prismic.

What are you trying to accomplish with the parent document?

**Comment by ktbee** [comment]
Hi @angeloashmore , thank you for the quick response. My goal is to be able to choose a parent page in Prismic, and have Gatsby's routes reflect that relationship. So if I choose the "About" page to be the parent of the "Employees" page in Prismic, I would like Gatsby to display the "Employees" page at `/about/employees`. I'm likely not understanding how Gatsby creates routes, I thought that I needed to add the Prismic parent page to [the `parent` property on the node itself,](https://www.gatsbyjs.org/docs/node-interface/) which is owned/controlled by `gatsby-source-prismic`. 

Another way I thought of doing this is to just use the Prismic parent page's `url` field and add that as part of the page's `path`, though if the page is nested more than one level deep, I'd need to check for the parents of the parent page. That's a possiblity, but I wondered what you recommended or if anyone else has used Prismic to set parent pages with `gatsby-source-prismic` yet.

**Comment by angeloashmore** [comment]
This is something I've been thinking about lately for client projects, and the solution isn't pretty, but it works.

Parent-child relationships in Gatsby are designed for nodes that derive data, such as an Image URL creating an ImageSharp node to provide different image sizes. A parent-child relationship for pages doesn't fit this model, but Gatsby provides mapping functionality using `___NODE`. This is used for the `document` field so we can access a linked document's data.

To construct the full URL of a page that has a parent, grandparent, great-grandparent, etc., one must query each level like such:

```graphql
query AllPages {
  allPrismicPage {
    edges {
      node {
        uid
        ...PageParentRecursive
      }
    }
  }
}

fragment PageParentRecursive on PrismicPage {
  data {
    parent {
      document {
        ...PageParentFields
        data {
          parent {
            document {
              ...PageParentFields
              data {
                parent {
                  document {
                    ...PageParentFields
                    data {
                      parent {
                        document {
                          ...PageParentFields
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment PageParentFields on PrismicPage {
  uid
}
```

This will grab four levels of parents along with their UID. If additional or alternate fields are needed, the `PageParentFields` fragment can be updated. For deeper levels of parents, additional levels would be added to `PageParentRecursive`.

With this data, the full URL can be built by combining the UIDs from each parent document.

See here for limitations in GraphQL: https://github.com/facebook/graphql/issues/91

Hope that helps. Let me know if there's another way I can help, or if you have any suggestions.

**Comment by mgburns** [comment]
That approach works for creating pages, but I don't see any obvious way to handle hierarchical link resolution with the `linkResolver` defined in `gatsby-config.js`:
https://github.com/angeloashmore/gatsby-source-prismic/blob/master/src/normalize.js#L180

Any thoughts there?

**Comment by aronstrandberg** [comment]
@mgburns Were you able to figure this out? I'm having the same problem right now.

**Comment by mgburns** [comment]
@aronstrandberg We wound up setting up a pre-build script that pulled all page documents from Prismic, recursively builds hierarchical urls for each document, and writes the results to a JSON file. The application code then imports this file and uses it to determine document urls in the `linkResolver`.

Not ideal, but it works.

**Comment by angeloashmore** [comment]
A `fetchLinks` array can be provided to the plugin options to fetch linked document fields.

See the official docs here: https://prismic.io/docs/javascript/query-the-api/fetch-linked-document-fields

v3 of the plugin will upgrade `prismic-javascript` to `v2` that supports the new GraphQuery feature.

See the official docs here: https://prismic.io/docs/rest-api/query-the-api/graphquery

This will not supported in the initial v3 release but should be supported in a later version.

**Comment by angeloashmore** [comment]
Cleaning up old issues. Please open a new issue if this is still present. Thanks!
