### ISSUE TITLE
v2 error with more than one entry - Expected value of type \"PrismicPost\" but got: [object Object].

### ISSUE THREAD

**Issue by michaelhaessig** [angeloashmore/gatsby-source-prismic#48]
I'm using gatsby v2 with the newest version of this plugin. 

I don't know if im doing something inherently wrong or if this is indeed a bug. 

I've created a content with type "post" in prismic. 
 
I'm using the following query to access the posts: 

`allPrismicPost {
        totalCount
        edges {
          node {
            id
            uid
            first_publication_date(formatString: "DD MMMM, YYYY")
            last_publication_date(formatString: "DD MMMM, YYYY")
            data {
              title {
                text
              }
              content {
                html
              }
            }
          }
        }
}
`

The query works with a single entry but as soon as i'm adding a second post in prismic the graphql query stops working with the following error:

`{
  "errors": [
    {
      "message": "Expected value of type \"PrismicPost\" but got: [object Object].",
      "locations": [
        {
          "line": 32,
          "column": 6
        }
      ],
      "path": [
        "allPrismicPost",
        "edges",
        0,
        "node"
      ]
    },
....
}`

I don't know what todo about the error. I would appreciate any help. 

Here is the content of my package.json

`{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "next",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-source-filesystem": "^1.5.39",
    "gatsby-source-prismic": "^2.0.0-alpha.2",
    "gatsby-transformer-remark": "^1.7.44",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-helmet": "^5.2.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.12.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}
`

**Comment by angeloashmore** [comment]
Hi @michaelhaessig, I'm running into this issue now with Gatsby `v2` as well. I'll report back any findings.

**Comment by angeloashmore** [comment]
@michaelhaessig Upgrading Gatsby to `2.0.0-beta.54` fixed this issue for me. Could you try that out?

See: https://github.com/gatsbyjs/gatsby/issues/6443

**Comment by michaelhaessig** [comment]
hi @angeloashmore  , thanks for the response. 

i was just playing around with gatsby and this issue was a blocker for me to continue with prismic. 
i then found netlify cms and went this route.  im afraid i currently do not have a setup project to verify the fix, but good to know in case i consider using this plugin again in the future !

i will close the issue.
