### ISSUE TITLE
The gatsby-source-prismic plugin has generated no Gatsby nodes

### ISSUE THREAD

**Issue by skwidy** [angeloashmore/gatsby-source-prismic#51]
When building the project, it seems the nodes are not created, hence I cannot fetch anything :/

I get `The gatsby-source-prismic plugin has generated no Gatsby nodes. Do you need it ?`

What did I miss ?

**Comment by angeloashmore** [comment]
This could be a config issue. Could you share your `gatsby-config.js`? Just remember to remove your Prismic access token before posting here.

**Comment by Jayphen** [comment]
Make sure you _publish_ the content in Prismic before attempting to fetch it

**Comment by walston** [comment]
I think i may be experiencing a related issue. more than 50% of the time for my project gatsby-source-prismic will not instantiate any nodes. I've logged the data received from the Prismic.api call. and the failure seems to be in node-creation.

I'm wondering if one of the nodes is throwing an error that causes the entire process to fail silently. currently exploring a solution

**Comment by leighkendell** [comment]
I'm also having this issue on the latest 2.0.0 release. Everything seems to work fine on v2.0.0-alpha.4 though so one of the PR's merged for 2.0.0 must have broken it.

**Comment by angeloashmore** [comment]
Closing this out as it doesn't seem to be an active issue any more. Please let me know if you experience this again.
