### ISSUE TITLE
Warning There are conflicting field types in your data. GraphQL schema will omit those fields.

### ISSUE THREAD

**Issue by laradevitt** [angeloashmore/gatsby-source-prismic#53]
Great plugin - thanks so much! 

Unfortunately I've run into a roadblock where I'm unable to access some data from a `StructuredText` type field. I have three nodes, total, one of which is throwing this warning. 

```
warning There are conflicting field types in your data. GraphQL schema will omit those fields.
PrismicPage.data.content:
 - type: array<object>
   value: [ { type: 'image', url: 'https://xyz.cdn.prismic.io/xyz/bleah.jpg', alt: null, copyright: null, dimensions: [Object], label: 'align-center' }, ... ]
 - type: object
   value: { html: '<p>Stuff</p><p>More text</p>', text: 'Stuff', raw: [Array] }
```

If I examine `node.dataString` (unescaped), the structure of the field is similar between nodes; the main difference being that the node that triggers the warning begins with an 'image'-type object:

```
(no warning)

  "content": [
    {
      "type": "paragraph",
      "text": "Some text",
      "spans": []
    }, {
      "type": "paragraph",
      "text": "foo",
      "spans": []
    }, {
      "type": "paragraph",
      "text": "bar",
      "spans": []
    }
    }, {
      "type": "image",
      "url": "https://xyz.cdn.prismic.io/xyz/image.jpg",
      "alt": null,
      "copyright": null,
      "dimensions": {
        "width": 123,
        "height": 191
      },
      "label": "align-right"
    },
    ...
  ],

(warning)

  "content": [
    {
      "type": "image",
      "url": "https://xyz.cdn.prismic.io/xyz/image.jpg",
      "alt": null,
      "copyright": null,
      "dimensions": {
        "width": 450,
        "height": 338
      },
      "label": "align-center"
    }, {
      "type": "paragraph",
      "text": "Some text",
      "spans": [{
        "start": 0,
        "end": 259,
        "type": "label",
        "data": {
          "label": "caption"
        }
      }]
    }, {
      "type": "heading3",
      "text": "Violins",
      "spans": []
    },
    ...
  ]

```

I'm not sure what to make of it, or how to solve it. Is there something obvious I'm missing here? Hoping someone can help. Thanks in advance!

gatsby 1.9.277
gatsby-cli 1.1.58
node v8.11.3

**Comment by angeloashmore** [comment]
Hi @laradevitt, this is due to the field starting with an image rather than text. This is a shortcoming of the current method the plugin uses to determine a field's type. Same as #52, and similar issue as #49.

There currently isn't a quick workaround besides putting text before the image. Sorry!

I'll be taking a look at a solution soon. I'm think we just check the whole field's value for an object with a `span` property. But I'll have to experiment with that.

**Comment by laradevitt** [comment]
Thanks! I had searched on the warning message, so I hadn't seen those. I'll go ahead and close this.

**Comment by birkir** [comment]
Can you please re-open this issue so we can track it

**Comment by riencoertjens** [comment]
I made some quick changes to fix this until there's a better solution

this accepts an extra option in gatsby-config 
```
options: {
  forcedRichTextFields: {
    document_type: 'field_name',
  },
}
```

[riencoertjens/gatsby-source-prismic](https://github.com/riencoertjens/gatsby-source-prismic)
and an npm package: [gatsby-source-prismic-rich-text-fields](https://www.npmjs.com/package/gatsby-source-prismic-rich-text-fields)

#52

**Comment by CharlieDieter** [comment]
Hey @riencoertjens this is super helpful, but I had to modify it a bit to allow for `field_names` other than `content`, and to include multiple field names from a particular `document_type`.  Just a suggestion. Thanks!

**Comment by angeloashmore** [comment]
There’s an official solution to this issue in the works. Please see https://github.com/angeloashmore/gatsby-source-prismic/issues/78#issuecomment-474153523 and give the alpha a try.

This version allows you to provide your schemas from Prismic and informs Gatsby of all your fields.

Thanks!

**Comment by angeloashmore** [comment]
Closing this out as `v3` has been in open beta for a while now and solves this issue. Please give it a try if you haven't yet!
