### ISSUE TITLE
Gatsby@v2 compatibility: Calling "touchNode" with a nodeId is deprecated

### ISSUE THREAD

**Issue by walston** [angeloashmore/gatsby-source-prismic#54]
Gatsby@next is deprecating `touchNode('a-node-id')` replacing it with `touchNode({nodeId: 'a-node-id'})`

a warning is produced for every node created

**Comment by robertcoopercode** [comment]
Anyone have any idea how to resolve this issue? We're getting a ton of warnings showing up everytime we run `gatsby develop`.

**Comment by robertcoopercode** [comment]
I made a PR for this: #58
