### ISSUE TITLE
Filter on __typename

### ISSUE THREAD

**Issue by eric-personal** [angeloashmore/gatsby-source-prismic#56]
I have the following code and I understand how to filter on the top node. but I'd like to be able to filter in the nested nodes. For example I'd like to be able to filter a specific slice from Prismic. 
So keeping the uid filter but then filter out all  the slice __typename except one 

**"PrismicTemplateBodyLatest"**

```
{
  allPrismicNewsTemplate(filter: {uid: {eq: "people"}}) {
    edges {
      node {
        uid
        data {
          body {
             __typename
            ... on PrismicTemplateBodyLatest {
              slice_type
            }
          }
        }
      }
    }
  }
}
```

**Comment by angeloashmore** [comment]
Ah, good idea. I think you can filter from the root filter you have now by adding a deeply nested filter. Please correct me if I'm wrong.

It would also make sense to filter from the `body` field as well. I'll have to look into adding custom arguments to the GraphQL schema. This could potentially be rolled into a future update where we can take the Prismic JSON schema and provide the full shape of the data to Gatsby. This is semi-in-progress.

**Comment by eric-personal** [comment]
Thanks angeloashmore. What do you mean by : 

> I think you can filter from the root filter you have now by adding a deeply nested filter. Please correct me if I'm wrong.

Whats a deeply nested filter. Do you have an example ? 

Yes would be great if filtering the body was added as a feature. So far I seem to be only able to filter from the top most node (root), which I'm doing in my example using a uid from Prismic but that could be an id from anywhere.

**Comment by angeloashmore** [comment]
@eric-personal Apologies for the very late follow-up. I misunderstood your question earlier when referring to the deeply nested filter. I was thinking you needed to filter your page responses based on if it contained a slice.

Re: filtering on slice fields, this would be best done in your components via JavaScript by, for example, filtering `body` where the node has the `__typename` you're looking for. Adding filtering via GraphQL on slice fields would cause issues for the upcoming preview feature.
