### ISSUE TITLE
Make plugin compatible to Gatsby v2

### ISSUE THREAD

**Issue by LeKoArts** [angeloashmore/gatsby-source-prismic#61]
- Fix the "deprecated" warnings (see Pull Requests)
- Merge the current v2 branch and publish as `2.0.0` on npm

Especially the npm one is important as all instructions will only install the v1 as latest currently...

**Comment by angeloashmore** [comment]
Done! https://www.npmjs.com/package/gatsby-source-prismic/v/2.0.0

Thanks again for the reminder on Twitter. I have two jobs and have been working way too much lately, but I'm glad to have finally found a bit of time to publish these upgrades. 🎉
