### ISSUE TITLE
Cant access repeatable items inside a slice

### ISSUE THREAD

**Issue by dante-blitz** [angeloashmore/gatsby-source-prismic#63]
I have a content type in Prismic that contains a slice called "Test Slice" that has a title field in it'non-repeatable zone and an image field in it's repeatable zone. Here is the json:

```json
{
  "Main": {
    "uid": {
      "type": "UID",
      "config": {
        "label": "Id"
      }
    },
    "blog_title": {
      "type": "StructuredText",
      "config": {
        "single": "heading1",
        "label": "Blog Title"
      }
    },
    "main_image": {
      "type": "Image",
      "config": {
        "constraint": {},
        "thumbnails": [],
        "label": "Main Image"
      }
    },
    "body": {
      "type": "Slices",
      "fieldset": "Slice zone",
      "config": {
        "choices": {
          "test_slide": {
            "type": "Slice",
            "fieldset": "Test Slide",
            "description": "a test slide",
            "icon": "blur_linear",
            "display": "list",
            "non-repeat": {
              "gallery_title": {
                "type": "StructuredText",
                "config": {
                  "single": "heading2",
                  "label": "Gallery Title"
                }
              }
            },
            "repeat": {
              "gallery_images": {
                "type": "Image",
                "config": {
                  "constraint": {},
                  "thumbnails": [],
                  "label": "Gallery Images"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

I cannot seem to access the repeatable image field from GraphiQL. I can get other data just fine but the repeatable fields inside a slice do not show up.

I can see the data appear when I query the dataString under 'items'.

`"dataString": "{\"blog_title\":[{\"type\":\"heading1\",\"text\":\"asdasdasd\",\"spans\":[]}],\"main_image\":{\"dimensions\":{\"width\":960,\"height\":800},\"alt\":null,\"copyright\":null,\"url\":\"https://wroomdev.s3.amazonaws.com/tutoblanktemplate%2F97109f41-140e-4dc9-a2c8-96fb10f14051_star.gif\"},\"body\":[{\"slice_type\":\"test_slide\",\"slice_label\":null,\"items\":[{\"gallery_images\":{\"dimensions\":{\"width\":960,\"height\":800},\"alt\":null,\"copyright\":null,\"url\":\"https://wroomdev.s3.amazonaws.com/tutoblanktemplate%2F97109f41-140e-4dc9-a2c8-96fb10f14051_star.gif\"}}],\"primary\":{\"gallery_title\":[{\"type\":\"heading2\",\"text\":\"test gallery\",\"spans\":[]}]}},{\"slice_type\":\"test_slide\",\"slice_label\":null,\"items\":[{\"gallery_images\":{\"dimensions\":{\"width\":960,\"height\":800},\"alt\":null,\"copyright\":null,\"url\":\"https://wroomdev.s3.amazonaws.com/tutoblanktemplate%2F97109f41-140e-4dc9-a2c8-96fb10f14051_star.gif\"}}],\"primary\":{\"gallery_title\":[{\"type\":\"heading2\",\"text\":\"Test Gallery 2\",\"spans\":[]}]}}]}"`

Anyone know how I can get repeatable data?

**Comment by leolabs** [comment]
You can access repeatable items in your slice using the `items` key. This is an example of code I've used to query slice data from Prismic in GraphQL

```graphql
... on PrismicPageBodyBanner {
  id
  slice_label
  slice_type
  primary {
    banner_title
    banner_text {
      html
    }
  }
  items {
    banner_label
    banner_link {
      url
    }
  }
}
```

**Comment by angeloashmore** [comment]
Thanks @leolabs, that's exactly how the repeatable items should be queried.
