### ISSUE TITLE
Unable to query Author

### ISSUE THREAD

**Issue by iamkevingreen** [angeloashmore/gatsby-source-prismic#66]
Attempts at query author field in the graphql viewer yield no results (even when searching all available query types). Using v2.0.

example query:

```
    {
      allPrismicEditorial {
        edges {
          node {
            id
            uid
            data {
              author
            }
         }
       }
      }
```

I added author name and picture to the fetchLinks in the config but that doesn't seem to work either?

```
        fetchLinks: [
          // Your list of links
          'author.name',
          'author.picture'
        ],
```

**Comment by angeloashmore** [comment]
Hey @iamkevingreen, do you have an author field on your custom type? If you do, what type of field is it?

From what I understand, Prismic does not provide the user that created the document (i.e. the avatar you see in the Prismic back-end), but you can make an Author field on a custom type that links to an Author custom type. You would need to create the Author custom type yourself.

**Comment by iamkevingreen** [comment]
@angeloashmore Makes sense, I realized having author as a content type actually makes more sense in general regardless. I actually need to be able to associate multiple authors so the default prismic functionality wouldn't work regardless!

But interesting that this isn't apparently exposed by default though non-blocking. (I guess we can close this but if anyone else searches they'll know it's simply not available).

**Comment by angeloashmore** [comment]
Closing this since it has been addressed.
