### ISSUE TITLE
Can only select a field if it has data

### ISSUE THREAD

**Issue by jordanoverbye** [angeloashmore/gatsby-source-prismic#67]
If I set up a custom field on a custom type in Prismic, I can only query it's fields if at least 1 item has data.

For example: 
```
      query myQuery {
        allPrismicMyCustomType {
          edges {
            node {
              data {
               someField
                image {
                  alt
                  url
                  dimensions {
                    width
                    height
                  }
                }
              }
            }
          }
        }
      }
```

If I don't have at least 1 item with an image, the whole query fails and Gatsby does not build.

**Comment by angeloashmore** [comment]
Hi @jordanoverbye, this is a current limitation of Gatsby's GraphQL system (although there are some ideas on how to solve this).

Please see this issue: https://github.com/angeloashmore/gatsby-source-prismic/issues/21

One possible solution is to allow the plugin to accept your Prismic schema JSON files and create a Gatsby GraphQL schema from that, but it is currently unimplemented (see the `aa/parse-schema` branch).
