### ISSUE TITLE
Feature request: option to disable downloading of remote images (localFile)

### ISSUE THREAD

**Issue by ryanditjia** [angeloashmore/gatsby-source-prismic#68]
Hi. First of all, thanks a lot for the work done on this source plugin.

I’m currently doing a client work and ran into a little bit of a pain point. Their portfolio consists of a lot of high-resolution photos, and Gatsby needs to download these photos (hundreds of MBs) when they aren’t cached. I plan to use Prismic’s responsive images instead, thus not needing `sharp` and `localFile`.

Could the plugin perhaps expose an option to disable the creation and downloading of `localFile` node? I’d be happy to try my hand at a PR.

**Comment by angeloashmore** [comment]
Hey @ryanditjia, I had a similar thought about this recently. It definitely makes sense to allow turning off local file downloading.

Maybe rather than a simple boolean to determine if all or no files are downloaded, maybe it's a function that has the node as input and returns true or false. That way one could set one content type's files to download, but turn it off for everything else.

By default the function would just return true.

**Comment by angeloashmore** [comment]
To take this a little further, I think it might be a good idea to also download linked files locally to allow the files to be served from the Gatsby instance. The function could determine if the file should be downloaded locally.

Right now, the only option to serve a file attached to a Media Link field is to use the prismic.io URL. This could be bad for some cases where the URL of the linked media needs to match the domain (think a bank website).

**Comment by angeloashmore** [comment]
This has been implemented with the `shouldNormalizeImage` plugin option.

```js
// The document node, field key (i.e. API ID), and field value are provided to
// the function, as seen below. This allows you to use different logic for each
// field if necessary.
// This defaults to always return true.
shouldNormalizeImage: ({ node, key, value }) => {
  // Return true to normalize the image or false to skip.
},

```

@daydream05 I'm not 100% how the Contentful plugin is written, but I believe it re-implements the gatsby-source-transformer functionality. This is fairly complex and would require more time to investigate. But with that, I think it means it will only download and process an image if it is queried. Please let me know if that is incorrect.

Do you mind opening a new issue to track that feature?

**Comment by Sirk** [comment]
> To take this a little further, I think it might be a good idea to also download linked files locally to allow the files to be served from the Gatsby instance. The function could determine if the file should be downloaded locally.
> 
> Right now, the only option to serve a file attached to a Media Link field is to use the prismic.io URL. This could be bad for some cases where the URL of the linked media needs to match the domain (think a bank website).

Hi @angeloashmore. I find pretty interesting the idea of downloading also (at least get the opportunity to choose if) a Prismic Media link. As it could in this way expose those file to some transformers or other plugins (for example, transforming a .csv, getting a video file, etc).

Did you keep this idea somewhere or did you throw it away for any reason ?

If you did have an idea on how to implement it, I could try to free some time to help on this.

Thanks!

**Comment by angeloashmore** [comment]
Hi @Sirk, I didn't end up writing this functionality, but I agree, the idea is interesting and could be helpful.

This would involve adding some functionality to the `normalizeLinkField` in both `environment.node.ts` and `environment.browser.ts` (the browser environment is used when loading previews client-side).

For example, here's what the normalizer does when the link type is a Document: https://github.com/angeloashmore/gatsby-source-prismic/blob/fcd52435ad8da9764a6689b91594362252087068/src/environment.node.ts#L102-L111

Downloading files would look something like this block used to download images: https://github.com/angeloashmore/gatsby-source-prismic/blob/fcd52435ad8da9764a6689b91594362252087068/src/environment.node.ts#L38-L80

Just a heads up: the the project is now written in TypeScript starting with `3.0.0-beta.24` which should make it easier to add new functionality. I hope TS isn't a barrier to get your help!

**Comment by Sirk** [comment]
Hey @angeloashmore! 

Thanks for the detailled reply! 

Current client ultimately did not choose this solution so I will have to wait a little bit to find some time about it but I definitely keep this somewhere and will try to get back at it as soon as I get time!
