### ISSUE TITLE
lang switch

### ISSUE THREAD

**Issue by sutter** [angeloashmore/gatsby-source-prismic#69]
Someone would have an example to recover the data multilang?
I can only get the data in-us, I miss the translations fr-fr.
```
{
  "data": {
    "prismicHomepage": {
      "id": "Prismic__Homepage__W8otHRQAACwAzsTl",
      "alternate_languages": [
        {
          "id": "W8os-RQAAGWgzsRA",
          "lang": "fr-fr"
        }
      ],
      "lang": "en-us",
      "data": {
        "bigtitle": "Hello",
        "smalltitle": {
          "html": "<h1>World</h1>",
          "text": "World"
        }
      }
    }
  }
}
```

**Comment by k-sav** [comment]
I'm wondering if you managed to solve this issue?

**Comment by sutter** [comment]
@k-sav Yes, I duplicated the pages and added a parameter to my query.

<img width="926" alt="capture d ecran 2019-01-17 12 07 34" src="https://user-images.githubusercontent.com/709456/51314637-886c1000-1a50-11e9-89e6-dd6efba99d44.png">
<img width="973" alt="capture d ecran 2019-01-17 12 07 42" src="https://user-images.githubusercontent.com/709456/51314638-8904a680-1a50-11e9-9f77-73f442b20058.png">
<img width="1095" alt="capture d ecran 2019-01-17 12 10 22" src="https://user-images.githubusercontent.com/709456/51314796-f284b500-1a50-11e9-8f46-7a529e796ccc.png">

**Comment by k-sav** [comment]
Thanks for that!
