### ISSUE TITLE
repositoryName not respositoryName

### ISSUE THREAD

**Issue by MarcelWi** [angeloashmore/gatsby-source-prismic#7]
Hey,

you have a a little mistake in your README 

"repositoryName" is correct for your config.

**Comment by angeloashmore** [comment]
Thanks for spotting that. Just fixed it. 😄

**Comment by baggsie** [comment]
This is still incorrect on npm btw: https://www.npmjs.com/package/gatsby-source-prismic

**Comment by angeloashmore** [comment]
I didn't publish anything since there weren't any code changes. But seeing as people are actually looking at this plugin, I'll go ahead and push an update. Thanks 👍
