### ISSUE TITLE
Handling empty Prismic fields in Gatsby

### ISSUE THREAD

**Issue by like-vyk** [angeloashmore/gatsby-source-prismic#78]
Hello,

I ran into an issue where if a field is empty in Prismic, it doesn't pull through to Gatsby. Now this means that we can't have optional fields, however Prismic fields seem to be all optional. This is not ideal.

Anyone worked on the `aa/parse-schema` branch recently perhaps? Or found a workaround for this?

Thanks, Vykintas

**Comment by angeloashmore** [comment]
Just a heads up, I have some time to dedicate to this. Missing fields is a large pain point for many people, myself included, so I'm hoping to come up with a solution soon.

**Comment by angeloashmore** [comment]
With what I have in mind, we would put all of our Prismic custom type JSON definitions in a folder and point them in the source plugin configuration. Then the plugin can parse the custom type JSON and build a GraphQL schema.

I found an endpoint (probably unofficial) on Prismic that sends the JSON definition in a slightly different format. We could also use that if it's stable enough. This would remove the need to manually manage JSON files.

**Comment by like-vyk** [comment]
It'd be fine to have the Json files as the first version, as I'm still maintaining the local schema copy anyway.

**Comment by angeloashmore** [comment]
Good to hear! Yes, this will also help others version control their custom types.

## Progress update

I've written the transformer that takes the Prismic JSON custom type definition and creates an equal GraphQL schema. I was initially thinking we could use Gatsby's `addThirdPartySchema` to merge into into the existing Gatsby GraphQL schema, but I keep getting a `schema is invalid` error.

There also appears to be some limitations inherit with using `addThirdPartySchema`: https://github.com/gatsbyjs/gatsby/issues/10856

So with that in mind, I'm thinking we take the same approach as `gatsby-source-sanity` and generate fake nodes, add it to Gatsby, then remove it just before pages are built. This informs Gatsby of the shape of our custom types without the downsides of `addThirdPartySchema`.

Note that this is a temporary fix until Gatsby's GraphQL system gets an overhaul (which is in progress!)

**Comment by like-vyk** [comment]
This is great progress! I tried the merge schema approach too but had the same issues.

Do you plan to merge the branch in to master?

**Comment by angeloashmore** [comment]
Yes, once it's working, I imagine the following will happen:

- Keep in a branch and publish an alpha version to have other people test and report issues
- Once everything is tested, merge into master and publish a minor version

**Comment by nickreese** [comment]
Stoked to see an alpha version. 👍

**Comment by like-vyk** [comment]
Any chance to have an alpha this month?

**Comment by sirmspencer** [comment]
If I query `dataString` the empty fields show up.  

In this example, gatsby is telling me `button_url` is not available.
```{
  "data": {
    "prismicHomePage": {
      "dataString": "{\"body\":[],\"title\":[{\"type\":\"heading1\",\"text\":\"Spinnaker at Enterprise Scale\",\"spans\":[]}],\"button_text\":[{\"type\":\"heading2\",\"text\":\"Try Our Free Demo Environment\",\"spans\":[]}],\"button_url\":{\"link_type\":\"Any\"}}",
      "data": {
        "title": {
          "text": "Spinnaker at Enterprise Scale"
        },
        "button_text": {
          "text": "Try Our Free Demo Environment"
        }
      }
    }
  }
}```

**Comment by angeloashmore** [comment]
Some work came in so I had to step away from this for a bit, but I should have some time soon to work on this. Hoping to have something by then end of the month. 👍

**Comment by like-vyk** [comment]
> If I query `dataString` the empty fields show up.
> 
> In this example, gatsby is telling me `button_url` is not available.
> 
> ```
>   "data": {
>     "prismicHomePage": {
>       "dataString": "{\"body\":[],\"title\":[{\"type\":\"heading1\",\"text\":\"Spinnaker at Enterprise Scale\",\"spans\":[]}],\"button_text\":[{\"type\":\"heading2\",\"text\":\"Try Our Free Demo Environment\",\"spans\":[]}],\"button_url\":{\"link_type\":\"Any\"}}",
>       "data": {
>         "title": {
>           "text": "Spinnaker at Enterprise Scale"
>         },
>         "button_text": {
>           "text": "Try Our Free Demo Environment"
>         }
>       }
>     }
>   }
> }```
> ```

Yeah I've noticed that Prismic is actually returning the fields as "null" however the plugin doesn't create those fields.

@angeloashmore can we just remove the filter for empty fields?

**Comment by angeloashmore** [comment]
I don't think we can do that since we can't guarantee what type the field is, thus we don't know which fields to mock.

For the example above, even if some how are able to register `button_url`, only `link_type` would be available, where we should expect to be able to query `url`.

```graphql
# This will fail
prismicHomePage {
  data {
    button_url {
      url
    }
  }
}
```

**Comment by angeloashmore** [comment]
Tracking progress here: https://github.com/angeloashmore/gatsby-source-prismic/pull/82

**Comment by like-vyk** [comment]
> I don't think we can do that since we can't guarantee what type the field is, thus we don't know which fields to mock.
> 
> For the example above, even if we some how are able to register `button_url`, only `link_type` would be available, where we should expect to be able to query `url`.
> 
> ```graphql
> # This will fail
> prismicHomePage {
>   data {
>     button_url {
>       url
>     }
>   }
> }
> ```

ah yes. Very true. We're facing a lot of issues with this so was trying to think of any possible workaround.

**Comment by angeloashmore** [comment]
@like-vyk @nickreese @sirmspencer Could you try out `v2.3.0-alpha.1` (tagged as `next`) with your Prismic schemas?

Instructions are available here: https://github.com/angeloashmore/gatsby-source-prismic/tree/aa/parse-schema#providing-json-schemas

**Comment by nickreese** [comment]
Thanks @angeloashmore. I setup a new Prismic repo and cloned over all of my custom types. 

Largely it appears to be working, but slices are broken as it appears they are being named/generated differently.

<img width="876" alt="screenshot 2019-03-01 10 37 33" src="https://user-images.githubusercontent.com/3580879/53648610-55e83200-3c0e-11e9-8dea-a59473512ca6.png">

```
import React from "react"
import { graphql } from "gatsby"

export default ({ primary, items }) => (
  <>
    {items.length < 1 ? null : (
      <ul>
        {items.map(item => (
          <li>
            {item.update} - <small>{item.date}</small>
          </li>
        ))}
      </ul>
    )}
  </>
)

export const query = graphql`

... edited out other fragments.

  fragment PrismicCompanyCustomerServiceBodyUpdatesFooter on PrismicCompanyCustomerServiceBodyUpdatesFooter {
    type: slice_type
    id
    items {
      update
      date
    }
  }

... edited out other fragments.
`
```

Interacting with the slices in GraphiQL is different as well.

**Comment by angeloashmore** [comment]
@nickreese Thanks for trying it out! Could you post your JSON schema, at least the part with your slice zone field and the `customer_service_body` slice choice?

And do be sure, this exact query works in your normal production site when the content exists in Prismic?

**Comment by angeloashmore** [comment]
@nickreese I just published `v2.3.0-alpha.3` with a fix.

Slice choice node references were being set on the wrong field with the wrong IDs. This has been corrected so could you give the new version a try?

Thanks 🎉

**Comment by like-vyk** [comment]
thanks @angeloashmore . Got 2 issues now. One is a warning and theres a lot of them:
```warning There are conflicting field types in your data. GraphQL schema will omit those fields.
PrismicLegalBodyTwoImagesIntroModuleEm011.primary.em11_main_video_link.thumbnail_width:
 - type: number
   value: 640
 - type: string
   value: 'hszaqKEJqrQwkocoqOn'
PrismicLegalBodyTwoImagesIntroModuleEm011.primary.em11_main_video_link.thumbnail_height:
 - type: number
   value: 360
 - type: string
   value: 'GgvxiXmIaQ'
```

Another one is:
```⠁ Starting to fetch data from Prismic
⠈ source and transform nodesFetch Prismic data: 433.564ms
error Plugin gatsby-source-prismic returned an error


  TypeError: Cannot read property 'fantasy-land/map' of undefined
  
  - _dispatchable.js:31 
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_dispatchable.js:31:23
  
  - _curry2.js:29 Object.f2 [as map]
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_curry2.js:29:14
  
  - customTypeJsonToGraphQLSchema.js:237 
    [isko]/[gatsby-source-prismic]/customTypeJsonToGraphQLSchema.js:237:21
  
  - mapObjIndexed.js:32 XWrap.f
    [isko]/[gatsby-source-prismic]/[ramda]/src/mapObjIndexed.js:32:16
  
  - _xwrap.js:12 XWrap.@@transducer/step
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_xwrap.js:12:17
  
  - _reduce.js:11 _arrayReduce
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_reduce.js:11:34
  
  - _reduce.js:45 _reduce
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_reduce.js:45:12
  
  - mapObjIndexed.js:31 mapObjIndexed
    [isko]/[gatsby-source-prismic]/[ramda]/src/mapObjIndexed.js:31:10
  
  - _curry2.js:22 
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_curry2.js:22:18
  
  - _curry1.js:18 f1
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_curry1.js:18:17
  
  - _pipe.js:3 
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_pipe.js:3:14
  
  - _pipe.js:3 
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_pipe.js:3:27
  
  - _pipe.js:3 
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_pipe.js:3:27
  
  - _arity.js:10 
    [isko]/[gatsby-source-prismic]/[ramda]/src/internal/_arity.js:10:19
  
  - customTypeJsonToGraphQLSchema.js:252 
    [isko]/[gatsby-source-prismic]/customTypeJsonToGraphQLSchema.js:252:44
  
  - mapObjIndexed.js:32 XWrap.f
    [isko]/[gatsby-source-prismic]/[ramda]/src/mapObjIndexed.js:32:16
  

warning The gatsby-source-prismic plugin has generated no Gatsby nodes. Do you need it?```

I've enabled by adding `responsibility: require('./schemas/responsibility.json')` to the gatsby.config.
Here is the schema url: https://codeshare.io/anOjZn

**Comment by like-vyk** [comment]
I've noticed that the names don't match exactly. I end up having:
PrismicLifestyleBodyModuleIdEm003
and 
PrismicLifestyleBodyModuleIdem003

**Comment by angeloashmore** [comment]
@like-vyk Could you try out the latest `@next` tag (`v2.3.0-alpha.5`)?

- Fixed the type of embed thumbnail height and width
- Fixed the processing of slices without primary and/or items fields
- Fixed the type naming

**Comment by like-vyk** [comment]
@angeloashmore now I get this:
```error Plugin gatsby-source-prismic returned an error


  Error: Schema must contain unique named types but contains multiple types named "InternalPrismicGroupFieldId".
  
  - Array.reduce
  
  - customTypeJsonToGraphQLSchema.js:299 customTypeJsonToGraphQLSchema
    [isko]/[gatsby-source-prismic]/customTypeJsonToGraphQLSchema.js:299:10
  
  - createTemporaryMockNodes.js:35 jsonSchemaToMockNode
    [isko]/[gatsby-source-prismic]/createTemporaryMockNodes.js:35:83
  
  - createTemporaryMockNodes.js:201 R.pipe.R.map
    [isko]/[gatsby-source-prismic]/createTemporaryMockNodes.js:201:69```

**Comment by angeloashmore** [comment]
@like-vyk Could you try `v2.3.0-alpha.6`? I had the wrong string type (single-quote vs back-tick).

**Comment by like-vyk** [comment]
@angeloashmore We're close. Now i just get this:
```Cannot query field "uid" on type "unionDocumentNode". Did you mean to use an inline fragment on "PrismicHomepage", "PrismicLegal", or "PrismicProduct"?
Cannot query field "data" on type "unionDocumentNode". Did you mean to use an inline fragment on "PrismicHeader", "PrismicFooter", "PrismicHomepage", "PrismicLegal", or "PrismicLifestyle"?
---------------------------------

Issue creating pages:  TypeError: Cannot read property 'allPrismicProduct' of undefined```

**Comment by angeloashmore** [comment]
@like-vyk is that error coming from querying a content relation field? If so, could you confirm you’re using a fragment when querying the document fields?

https://github.com/angeloashmore/gatsby-source-prismic/blob/master/README.md#query-content-relation-fields

If it isn’t that, could you post your query here?

**Comment by like-vyk** [comment]
@angeloashmore what's the best way to send you the schemas we have?

**Comment by b-reklass** [comment]
@angeloashmore This is a fantastic start for this-- working awesome on my end. Only remaining flaw I see is that if you have yet to publish a member of a type the GraphQL won't populate, even if you provide a schema.

**Comment by angeloashmore** [comment]
@b-reklass Thank you for trying it out!

Which version of the plugin are you using? On the latest alpha, `2.3.0-alpha.6`, I am able to include a schema for a custom type that doesn't exist in my Prismic repository.

```js
// src/schemas/custom.json

{
  "Main": {
    "title": {
      "type": "StructuredText",
      "config": {
        "single": "heading1",
        "label": "Title"
      }
    }
  }
}
```

```js
// gatsby-config.js
// gatsby-source-prismic options:
options: {
  schemas: {
    custom: require('./src/schemas/custom.js'),
  },
},
```

```graphql
# In a query

{
  allPrismicCustom {
    edges {
      node {
        id
        data {
          title {
            text
          }
        }
      }
    }
  }
}
```

**Comment by Sirk** [comment]
@angeloashmore congrats for the progress, this is very promising !!!

Just to notice you, it seems like on `2.3.0-alpha.6`  you can't anymore query data of a content field under `document`.

In stable, you can for example : 
```graphql
{
    prismicCustom {
        data {
            mycontentrelationship {
                document {
                    data {
                         # get data from mycontentrelationship
                    }
                }
            }
        }
    }
}
```
but in  `2.3.0-alpha.6`  there is only `__typename` available under `document`. 

Got this error when I try to reach data : 
`Unknown field 'data' on type '[Prismic....Union]'.`

**Comment by angeloashmore** [comment]
@Sirk I also query documents directly. It’s nice to be able to grab exactly what you need right where it’s defined.

You will need to use the fragment syntax when querying for document data now. This was optional before as document fields generally only contained one type of custom type. Now, however, Gatsby knows it could be any of your custom types since that is how Prismic works.

https://github.com/angeloashmore/gatsby-source-prismic/blob/aa/parse-schema/README.md#query-content-relation-fields

Notice the `... on PrismicCustomTypeName` under document.

Thank you for trying out the alpha release. I hope to publish it soon once we have reports of successful uses.

**Comment by Sirk** [comment]
@angeloashmore Thanks for the answer. Didn't notice the difference in the new Readme !
Seems to work perfectly. Going to use alpha for a production project, so I will keep you in touch for the report :)

**Comment by PolGuixe** [comment]
How is this issue related with https://github.com/gatsbyjs/gatsby/pull/11480?

**Comment by angeloashmore** [comment]
@PolGuixe The initial implementation was written using a different approach since it was before schema customization, but the upcoming `v3` release uses it.

**Comment by Ehesp** [comment]
FYI I raised the schemas with the Prismic team and they're going to look into adding the ability to get them directly from the API.

**Comment by angeloashmore** [comment]
Going to close this issue as `v3` has been in open beta for a while now. Please give it a try if you haven't yet!
