### ISSUE TITLE
No options to set proxy agent 

### ISSUE THREAD

**Issue by SugarDarius** [angeloashmore/gatsby-source-prismic#79]
Hi !
Is it possible to add the "proxyAgent" option of prismic-javascript in the plugin's options ? 
I'm working in a company who is using a a corporate proxy. 
It will be very helpful to add this option :) 

Thanks a lot,
Aurélien

**Comment by henrickyau** [comment]
I have the same issue

**Comment by nahiyankhan** [comment]
Bumping this question.. I am having this issue as well!

**Comment by johanleroch** [comment]
Same :)

**Comment by nahiyankhan** [comment]
Update: I managed to make it work behind my company's network. Had to make a private fork and then add a proxy agent in two different spots with our proxy details. 

I used [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent). The first addition is in fetch.js, line 32 where prismicJavascript is called with the apiEndpoint to source Prismic data. Add the proxy agent after the access token. Example,

```
const client = yield _prismicJavascript.default.api(apiEndpoint, {
    accessToken,
    proxyAgent: new require('https-proxy-agent')({
    host: 'your host',
    port: your port,
    rejectUnauthorized: false
  })
});
```

The second one is in gatsby-source-filesystem, create-remote-file-node.js, line 149 where the remote node is requested. This is the call where the images are sourced. Example,

```
const requestRemoteNode = (url, headers, tmpFilename, httpOpts) => new Promise((resolve, reject) => {
  const opts = Object.assign({}, {
    timeout: 30000,
    retries: 5,
    agent: new require('https-proxy-agent')({
      host: 'your host',
      port: your port,
      rejectUnauthorized: false
    })
  }, httpOpts);
```

**Comment by angeloashmore** [comment]
Hi everyone, and thank you @nahiyankhan for the workaround.

Before adding this as a plugin option, do you know the reasoning behind requiring proxy options at the library level rather than the network/system? I am not too familiar with proxying networks, but it seems like this should be happening via network or computer settings, not within the JS fetching library.

**Comment by nahiyankhan** [comment]
Hi @angeloashmore ! Welcome! And I agree 100% with you. I also am not very knowledgeable about network proxies but based on what I could find and understand, it seems like node-fetch that prismic-javascript uses has the proxy agent option but prismic-javascript doesn't by default pass any arguments to it. Hence the first addition to pass it on. Similarly for gatsby-source-filesystem that uses [got](https://www.npmjs.com/package/got). Has an option but gatsby-source-filesystem doesn't pass anything to it. If both could default to settings saved in the network or computer, that would be super. Hope that makes sense!

**Comment by nahiyankhan** [comment]
Update! Wanted to capture this here for others. Been trying to learn more about proxies and find a better option. Found an option that also worked for me. 

If you are using node < 10, you can use **global-tunnel-ng**, and then add to gatsby-config.js:

```
var globalTunnel = require('global-tunnel-ng');

globalTunnel.initialize({
  host: 'your host',
  port: your port
});
```

And if you are using node > 10, you can use **global-tunnel**, and instead add:

```
const { bootstrap } = require("global-agent")

bootstrap()
```

**Comment by angeloashmore** [comment]
Cleaning up old issues. Please open a new issue if this is still present. Thanks!
