### ISSUE TITLE
How to sort documents by data

### ISSUE THREAD

**Issue by chinds185a** [angeloashmore/gatsby-source-prismic#88]
Ho does one sort documents returned by date? Prismic has a `sortBy` attribute on their graphql endpoint but that does not work with this plugin.

**Comment by angeloashmore** [comment]
Hi @chinds185a, you can perform sorting within GraphQL by providing `sort` a list of fields:

```graphql
{
  allPrismicPage(sort: {fields: [first_publication_date], order: ASC}) {
    nodes {
      uid
    }
  }
}
```
