### ISSUE TITLE
How do I render RichText ?

### ISSUE THREAD

**Issue by ClearedFram3** [angeloashmore/gatsby-source-prismic#90]
First off, I would like to thank you for you work! It's much appreciated 😄 

I'm trying to render a single RichText field. My query is:
```
{
   allPrismicHome {
      edges {
        node {
          data {
            intro_text {
              text
              html
            }
          }
        }
      }
    }
  }
}
```
I want to use `RichText.render(...intro_text.html)` but I get `t.reduce is not a function`
The query works because I can insert `...intro_text.text` on to the page great! So what is the deal with `RichText.render()`?

I tried making a function replica of my link resolver from `gatsby-config.js` and passing it to my `RichText.render()`, but that didn't work.

**Comment by angeloashmore** [comment]
You're welcome! Glad you're finding use in this plugin!

`intro_text.text` and `intro_text.text` are the output from `PrismicDOM.RichText.asText` and `asHtml`, so there is no need to use `RichText.render` directly in your components.

You can see it happening in the plugin here: https://github.com/angeloashmore/gatsby-source-prismic/blob/master/src/normalize.js#L45-L49

In my projects, I have an `HTMLContent` component that runs the HTML through [`html-react-parser`](https://github.com/remarkablemark/html-react-parser#readme). This allows modifying the HTML components that get rendered:

```jsx
const MyPage = ({ data }) => (
  <div>
    <HTMLContent
      html={data.prismicPage.data.intro_text.html}
      components={{ h1: props => <h1 className="myHeading" {...props} /> }}
    />
  </div>
)
```

It's a bit heavy handed, so the more direct way to use the `html` value is to use `dangerouslySetInnerHTML`:

```jsx
const MyPage = ({ data }) => (
  <div dangerouslySetInnerHTML={{ __html: data.prismicHome.data.intro_text.html }} />
)
```

**Comment by ClearedFram3** [comment]
Thanks for your quick response!

I'm guessing the HTML serializer setup in `gatsby-config.js` is run before the data is put on my query, but can it change it to React components? 

After reading your reply I made this component
```
const RichText = ({ classes: { content }, children }) => {
  return (
    <div className={content} dangerouslySetInnerHTML={{ __html: children }} />
  );
};
```
The `content` class has a bunch of CSS rules on it that turn the HTML into something I want. I based it off Bulma's `content` class and reshaped it with the Material-UI styles. It works great for now, so THANKS!

Is there a way to serialize incoming HTML in react components, such as turning `a` into a Gatsby `Link`?

**Comment by angeloashmore** [comment]
@ClearedFram3 Sorry for the late response! Yes, you can transform the components that get rendered using the [`html-react-parser`](https://github.com/remarkablemark/html-react-parser#readme) library I linked above.

I don't see any pre-made component published to NPM that does it but I'll publish the one I regularly use in a bit.

Note: If you're just looking to make sure `<a>` elements get handled by Gatsby's local router, you can use [`gatsby-plugin-catch-links`](https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/).

**Comment by angeloashmore** [comment]
@ClearedFram3 Just published [`react-html-renderer`](https://github.com/angeloashmore/react-html-renderer) that does exactly that.

```jsx
import React from 'react'
import { HTMLRenderer } from 'react-html-renderer'

// Components to which elements are mapped
import Heading from './Heading'
import Subheading from './Subheading'
import Link from './Link'

// HTML to render as React components
const html = `
  <h1>React</h1>
  <h2>A JavaScript library for building user interfaces</h2>
  <p>
    <a href="#">Get Started</a>
  </p>
`

// Note that default props can be set using the following pattern:
//
//   `props => <Comp foo="bar" {...props} />`
//
const App = () => (
  <HTMLRenderer
    html={html}
    components={{
      h1: props => <Heading color="red" {...props} />,
      h2: Subheading,
      a: Link,
    }}
  />
)
```

**Comment by good-idea** [comment]
+1 for using `react-html-renderer` here. I was pulling my hair out trying to figure out how to use `htmlSerializer` to use my own <Heading /> tag. 👍👍👍
I'd suggest adding a note about this in the docs!!

**Comment by rubas** [comment]
If you don't want to parse the HTML (again), you can use [`prismic-reactjs`](https://github.com/prismicio/prismic-reactjs), render the `raw` and use the `htmlSerializer` to use your own React components.

[More...](https://github.com/prismicio/prismic-reactjs#passing-your-own-serializer).

**Comment by angeloashmore** [comment]
@rubas It’s important to note the HTML from this source plugin is generated at build time, not run time, so there is no overhead if you use the HTML directly using `dangerouslySetInnerHTML`. The HTML (and text version) is generated using prismic-dom. This is the basically the non-React version of prismic-react as they both use the same underlying Prismic libraries. Prismic-react will do the transformation at run time.

If you need to use custom React components at run time, I recommend the HTML parser over the Prismic-specific component as it is more portable. For example, if you decide to change your data source from Prismic to Markdown, or vice versa, your components can stay the same.

**Comment by rubas** [comment]
> If you need to use custom React components at run time, I recommend the HTML parser over the Prismic-specific component as it is more portable. 

After looking at the involved package sizes, I do strongly agree not to use `prisimc-reactjs`.

**Comment by jrhager84** [comment]
Is there a Nextjs equivalent of doing this somewhere? Do the same principles apply?

**Comment by angeloashmore** [comment]
Hey @jrhager84, if you are using `getStaticProps` or `getServerSideProps`, you can use `prismic-dom` to convert your Rich Text fields into HTML on the server. This means you are passing an HTML string as a prop to your page component rather than using `prismic-reactjs`. `prismic-dom` and `prismic-reactjs` won't be part of your bundle in that case.

You'll still need a way to display the HTML, whether through `dangerouslySetInnerHTML` or a React component like `react-html-renderer`.
