### ISSUE TITLE
Slices with repeater image fields not loading image correctly

### ISSUE THREAD

**Issue by wrux** [angeloashmore/gatsby-source-prismic#91]
So I have a slice type for image gallery which just has a repeated image field. It works great when I have a single image gallery in my post. When I add a second image gallery then there is missing data for the image; only the first image gallery slice will have images with `localFile` data. 

[Here's my project](https://github.com/wrux/bloke/blob/master/src/templates/post.jsx) The graphQL looks correct to me and it works just fine with one image gallery slice. 

Any ideas why this does not work?

**Comment by angeloashmore** [comment]
I've had similar slices on other projects and have not run into that issue. Do you mind posting the result of the query (at least the body section) when it breaks?

**Comment by angeloashmore** [comment]
Actually I just saw your repo is runnable locally so I started it up. This is what I see on my end:

![localhost_8001_sakura-japan-osaka-kyoto-nara](https://user-images.githubusercontent.com/8601064/55652972-ce4f8f00-5788-11e9-825f-e875bafca431.png)

It looks like the image gallery is rendering correctly.

Could you try `gatsby clean` to clear your cache and assets and try again. I've noticed `gatsby-transformer-sharp` sometimes gets hung up on old cached results if you don't clear it periodically.

**Comment by wrux** [comment]
Ahh yea that worked great, I should have thought to try that.

**Comment by angeloashmore** [comment]
Good to hear! There's an umbrella issue regarding caching here: https://github.com/gatsbyjs/gatsby/issues/11747.
