### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by RobinHerzog** [angeloashmore/gatsby-source-prismic#92]
Hi,

Official Prsmic-Gatsby plugins has been released with preview feature.

Could we have it on this plugin too?

**Comment by angeloashmore** [comment]
@RobinHerzog This is in the works. An initial version with some limitations is being used in production now. A fully featured version is next on the roadmap.

**Comment by RobinHerzog** [comment]
Love it

**Comment by PolGuixe** [comment]
Is there any documentation for the current functionality?

**Comment by angeloashmore** [comment]
@PolGuixe Slightly outdated documentation is here: https://github.com/angeloashmore/gatsby-source-prismic/tree/ay/prismic-previews#prismic-previews

Full documentation will be available with the beta release soon, but it should give a brief overview of what the system does. All preview development is in the `ay/prismic-preview` branch.

**Comment by RobinHerzog** [comment]
Hope it will works with template and not the uid as slug

**Comment by angeloashmore** [comment]
@RobinHerzog Could you explain what you mean?

We are using it with templates and static pages with many slices, images, fields, etc. As long as your link resolver resolves to the same URL as pages on your site, there should be no issue.

**Comment by angeloashmore** [comment]
Reopening this for now since it has not been published yet.

**Comment by RobinHerzog** [comment]
I don't use the link resolver. 

I create my own routes.json files for each build.

`{
  "en-us": {
    "legal/mobile": "/legal/mobile/",
    "faq-exhibitors-mobile": "/faq/exhibitors/mobile/",
    "faq-attendees": "/faq/attendees/",
    "faq-attendees-mobile": "/faq/attendees/mobile/",
    "legal/gdpr": "/gdpr/",
    "help-center": "/help-center/",
    "legal/cookie": "/cookie-policy/",
    "legal/organizer": "/legal/organizer/",
    "legal/privacy_policy": "/privacy-policy/",
    "legal/terms_of_use": "/terms-of-use/",
    "pricing": "/pricing/",
    "gdpr": "/gdpr/",
    "trash": "/trash/",
    "partenaire": "/partner/",
    "widgets": "/widgets/",
    "integrations": "/integrations/",
    "products": "/products/",
    "products/networking/attendees-list": "/products/networking/attendees-list/",
    "exhibitors": "/exhibitors/",
    "artificial-intelligence": "/artificial-intelligence/",
    "/products/networking": "/products/networking/",
    "solutions/congress": "/solutions/congress/",
    "love": "/love/",
    "solutions/salons": "/solutions/exhibitions/",
    "emb_march": "/EMB/",
    "solutions/conventions": "/solutions/corporate/",
    "solutions/conferences": "/solutions/conferences/",
    "exposants": "/exhibitors/",
    "attendees": "/attendees/",
    "services": "/services/",
    "video-slider": "/video-slider/",
    "wsn-exhibitors": "/whos-next/lead-retrieval/",
    "exhibitor-lead-retrieval": "/exhibitor-lead-retrieval/",
    "event-matchmaking-platform": "/event-matchmaking-platform/",
    "event-mobile-web-apps": "/event-mobile-web-apps/",
    "customers": "/customers/",
    "homepage": "/",
    "confex": "/confex/",
    "success-story/witness": "/success-story/witness/",
    "success-story/salon-des-entrepreneurs": "/success-story/salon-des-entrepreneurs/",
    "success-story/step-conference": "/success-story/step-conference/",
    "success-story/jour-j": "/success-story/jour-j/",
    "success-story/vivatechhhh": "/success-story/vivatechhh/",
    "success-story/vivatechnology-2018": "/success-story/vivatechnology-2018/",
    "success-story/trustech": "/success-story/trustech/",
    "success-story/hello-tomorrow": "/success-story/hello-tomorrow/",
    "success-story/aiesec": "/success-story/aiesec/",
    "success-story/startup-safari": "/success-story/startup-safari/",
    "success-story/leaders": "/success-story/leaders/",
    "lengowday": "/success-story/lengow/",
    "success-story/oecd-forum": "/success-story/oecd-forum/",
    "WhosNext": "/success-story/whos-next-2018/",
    "success-story/apidays": "/success-story/apidays/",
    "/success-story/fic": "/success-story/fic/",
    "careers/account-executive": "/careers/account-executive/",
    "/careers/product-owner-internship": "/careers/product-owner-internship/",
    "careers/sales-executive": "/careers/sales-executive/",
    "careers/Inbound-Specialist": "/careers/inbound-specialist/",
    "careers/customer-success-internship": "/careers/customer-success-internship/",
    "careers/office-manager": "/careers/office-manager/",
    "careers/full-stack-developer": "/careers/full-stack-developer/",
    "careers/nodejs-developer": "/careers/nodejs-developer/",
    "careers/android-developer-internship": "/careers/android-developer-internship/",
    "careers/react-developer-internship": "/careers/react-developer-internship/",
    "/careers/digital-acquisition-marketer": "/careers/digital-acquisition-marketer-internship/",
    "careers/event-evangelist": "/careers/event-evangelist/",
    "careers/event-evangelist-internship": "/careers/event-evangelist-internship/",
    "careers/data-scientist-internship": "/careers/data-scientist-internship/",
    "careers/Business-Developer": "/careers/Business-Developer/",
    "features_overview": "/features/",
    "app/fic": "/app/fic/",
    "app/cgf-events": "/app/cgf-events/",
    "world-football-summit-asia": "/app/world-football-summit-asia-2/",
    "app/wsn-community": "/app/wsn-community/",
    "/app/laval-virtual": "/app/laval-virtual/",
    "app/salon-des-entrepreneurs-paris": "/app/salon-des-entrepreneurs-paris/",
    "app/imcas": "/app/imcas/",
    "app/OECDForum": "/app/OECDForum/",
    "app/whosnext": "/app/whosnext/",
    "app/swapcard": "/app/swapcard/",
    "/app/edge-european-premiere": "/app/edge-european-premiere/",
    "app/oecd-forum-2019-world-in-emotion": "/app/oecd-forum-2019-world-in-emotion/",
    "app/step-conference": "/app/step-conference/",
    "/app/hub-berlin-big-data-ai-summit": "/app/hub-berlin-big-data-ai-summit/",
    "app/16th-emn-annual-conference": "/app/16th-emn-annual-conference/",
    "/app/affiliates-2019-1": "/app/affiliates-2019-1/",
    "app/sdenantes": "/app/sde-nantes/",
    "app/sdelyon": "/app/sdelyon/",
    "/app/locworld39-kuala-lumpur": "/app/locworld39-kuala-lumpur/",
    "about/contact": "/contact/",
    "about/careers": "/careers/",
    "demo": "/demo/",
    "signup": "/signup/"
  },
  "fr-fr": {
    "faq-exhibitors": "/fr/faq/exposants/",
    "faq-attendees": "/fr/faq/participants/",
    "faq-exhibitors-mobile": "/fr/faq/exposants/mobile/",
    "faq-attendees-mobile": "/fr/faq/participants/mobile/",
    "legal/terms_of_use_mobile": "/fr/legal/mobile/",
    "legal/gdpr": "/fr/rgpd/",
    "legal/cookie": "/fr/politique-cookie/",
    "legal/organizer": "/fr/legal/organizer/",
    "legal/terms_of_use": "/fr/conditions-generales-utilisations/",
    "legal/privacy_policy": "/fr/politique-confidentialite/",
    "pricing": "/fr/prix/",
    "gdpr": "/fr/rgpd/",
    "widgets": "/fr/widgets/",
    "integrations": "/fr/integrations/",
    "partenaire": "/fr/partenaire/",
    "artificial-intelligence": "/fr/intelligence-artificielle/",
    "solutions/congress": "/fr/solutions/congres/",
    "love": "/fr/love/",
    "solutions/salons": "/fr/solutions/salons/",
    "solutions/conventions": "/fr/solutions/conventions/",
    "solutions/conferences": "/fr/solutions/conferences/",
    "exposants": "/fr/exposants/",
    "services": "/fr/services/",
    "attendees": "/fr/participants/",
    "wsn-exhibitors": "/fr/whos-next/lecteur-de-badge/",
    "exhibitor-lead-retrieval": "/fr/plateforme/capture-prospects/",
    "event-matchmaking-platform": "/fr/plateforme/matchmaking-rendez-vous/",
    "event-mobile-web-apps": "/fr/plateforme/app-mobile-web/",
    "customers": "/fr/clients/",
    "example": "/fr/example/",
    "homepage": "/fr/",
    "success-story/hello-tomorrow": "/fr/success-story/hello-tomorrow/",
    "success-story/jour-j": "/fr/success-story/jour-j/",
    "success-story/salon-des-entrepreneurs": "/fr/success-story/salon-des-entrepreneurs/",
    "success-story/step-conference": "/fr/success-story/step-conference/",
    "success-story/aiesec": "/fr/success-story/aiesec/",
    "success-story/vivatechnology-2018": "/frsuccess-story/vivatechnology-2018/",
    "success-story/startup-safari": "/fr/success-story/startup-safari/",
    "success-story/leaders": "/fr/success-story/leaders/",
    "WhosNext": "/fr/success-story/whos-next-2018/",
    "success-story/oecd-forum": "/fr/success-story/oecd-forum/",
    "success-story/trustech": "/fr/success-story/trustech/",
    "lengowday": "/fr/success-story/lengow/",
    "success-story/apidays": "/fr/success-story/apidays/",
    "/success-story/fic": "/fr/success-story/fic/",
    "success-story/witness": "/fr/success-story/witness/",
    "app/st-aero-business-club": "/fr/app/st-aero-business-club/",
    "/app/salon-handicap-emploi-and-achats-responsables-2019": "/fr/app/salon-handicap-emploi-and-achats-responsables-2019/",
    "/app/salon-des-entrepreneurs-lyon-2019": "/fr/app/salon-des-entrepreneurs-lyon-2019/",
    "app/french-fab-tour": "/fr/app/french-fab-tour/",
    "app/blend-web-mix": "/fr/app/blendwebmix-2018/",
    "/app/ebg": "/fr/app/ebg/",
    "app/africa-investment-forum": "/fr/app/africa-investment-forum-2018/",
    "app/trustech": "/fr/app/trustech-2018/",
    "app/salon-international-sante-et-innovation-de-la-federation-hospitaliere-de-france": "/fr/app/salon-international-sante-et-innovation-de-la-federation-hospitaliere-de-france/",
    "/app/les-etats-majors-du-vo": "/fr/app/les-etats-majors-du-vo/",
    "app/sde-paca": "/fr/app/sde-paca/",
    "/app/speeddatingimmobilier2019": "/fr/app/speeddatingimmobilier2019/",
    "/app/8eme-salon-de-l-immobilier-et-du-tourisme-portugais-invest-portugal": "/fr/app/8eme-salon-de-l-immobilier-et-du-tourisme-portugais-invest-portugal/",
    "about/contact": "/fr/contact/",
    "about/careers": "/fr/carriere/",
    "demo": "/fr/demo/",
    "signup": "/fr/inscription/"
  }
}
`

**Comment by angeloashmore** [comment]
Ok, makes sense. You’ll just need to supply a function that maps your custom type UID/type/lang to a URL using your routes.json file. We can revisit later if you are interested in implementing previews when it’s available to install.

**Comment by RobinHerzog** [comment]
I am, thanksç

**Comment by chrisbujok** [comment]
Is there any way I could help with development of this feature? I'd love to use it in my project and also I think that Preview could bring a lot of value to this Gatsby plugin.

**Comment by angeloashmore** [comment]
Try out the `v3.0.0-beta.0` release. It includes the `usePrismicPreview` hook and the surrounding infrastructure to make it happen.

You can browse the docs in the `v3-beta` branch.

Re: development, we’re actively working on getting the final 3.0 version ready for prod. Since it’s in beta, the most helpful thing would be reporting any bugs you encounter.

**Comment by chrisbujok** [comment]
Thanks @angeloashmore.
Is previewing unpublished pages also included, or not implemented yet? Documentation says _TODO_ but I'm not sure if it means documentation or the feature.

**Comment by RobinHerzog** [comment]
My template 1 is coded this way. Do you think it works with the beta?

```
import React from "react";
import { graphql } from "gatsby";
import Hero from "../components/section/hero";
import Article from "../components/section/article";
import GetInTouch2 from "../components/section/get_in_touch_v2";
import FAQ from "../components/section/faq";
import Statement from "../components/section/statement";
import Space from "../components/space";
import Iframe from "../components/section/iframe";
import HtmlField from "../components/section/html_field";
import Testimonials from "../components/section/testimonials";
import ButtonSlice from "../components/section/button_slice";
import PrevNextButtons from "../components/section/prev_next_buttons";
import CustomersLogo from "../components/section/customers_logo";
import Integrations from "../components/section/integrations";
import Policy from "../components/templates/policy";
import ListCustomersVideo from "../components/section/list_customers_video";
import TitleSubTitle from "../components/section/title_subtitle";
import Paragraph from "../components/section/paragraph";
import TextVerticalImage from "../components/section/text_vertical_image";
import Discovery from "../components/section/discovery";
import NavigationScroll from "../components/section/navigation_scroll";
import FeaturesOverviewScreenshots from "../components/section/features_overview_picto";
import TabsVerticalBigTexts from "../components/section/tabs_vertical_big_texts";
import TabsHorizontal2 from "../components/section/tabs_horizontal_2";
import FeaturesListShort from "../components/section/features_list_short";
import QuoteSlider from "../components/section/quote_slider";
import QuoteV3 from "../components/section/quote_v3";
import LogoLanding from "../components/section/landing_logo";
import LandingForm from "../components/section/landing_form";
import LandingPricing from "../components/section/landing_pricing";
import Twitter from "../components/section/twitter";
import RedBull from "../components/section/red_bull";
import Youtube from "../components/section/youtube";
import BenefitsGeneric from "../components/section/benefits";
import BreadCrumbs from "../components/section/breadcrumbs";
import Image from "../components/section/image_center";
import PricingNewPackages from "../components/section/pricing_new/packages";

import Divider from "../components/section/divider";
import Help from "../components/section/help";
import FaqAttendify from "../components/section/faq_attendify";
import KPICustomers from "../components/section/kpi_customers";
import BannerText from "../components/section/banner_text";
import Card from "../components/section/card_features";
import VideoSlider from "../components/section/video_slider";

import Layout from "../components/layout";

export default ({ ...props }) => {
  return (
    <Layout
      dataNavigation={props.data.translation}
      pageContext={props.pageContext}
    >
      <div style={{ backgroundColor: props.pageContext.background_color }}>
        {props.data.prismicTemplate1.data.bodyMain.map((slice, index) => (
          <React.Fragment key={index}>
            {slice.slice_type === "hero" && (
              <Hero lang={props.pageContext.lang} data={slice} />
            )}
            {slice.slice_type === "statement" && (
              <Statement
                title={slice.primary.statement_title[0].text}
                body={slice.primary.statement_body}
              />
            )}

            {slice.slice_type === "pricing_new_packages" && (
              <PricingNewPackages
                allData={props.data.prismicTemplate1.data.bodyMain}
                lang={props.pageContext.lang}
              />
            )}
            {slice.slice_type === "youtube" && <Youtube data={slice} />}
            {slice.slice_type === "integrations" && (
              <Integrations data={slice} />
            )}
            {slice.slice_type === "features_overview_screenshots" && (
              <FeaturesOverviewScreenshots data={slice} />
            )}
            {slice.slice_type === "red_bull_block" && <RedBull data={slice} />}
            {slice.slice_type === "customers_logo" && (
              <CustomersLogo data={slice} />
            )}
            {slice.slice_type === "help" && <Help data={slice} />}
            {slice.slice_type === "kpi_customers" && (
              <KPICustomers data={slice} />
            )}
            {slice.slice_type === "banner_title" && <BannerText data={slice} />}
            {slice.slice_type === "divider" && <Divider data={slice} />}
            {slice.slice_type === "html_field" && <HtmlField data={slice} />}
            {slice.slice_type === "quote" && <QuoteV3 data={slice} />}
            {slice.slice_type === "fils_d_ariane" && (
              <BreadCrumbs data={slice} />
            )}
            {slice.slice_type === "benefits_global" && (
              <BenefitsGeneric data={slice} />
            )}
            {slice.slice_type === "navigation_scroll" && (
              <NavigationScroll data={slice} />
            )}
            {slice.slice_type === "buttons" && <ButtonSlice data={slice} />}
            {slice.slice_type === "image_center" && <Image data={slice} />}
            {slice.slice_type === "quote_solution" && (
              <Testimonials data={slice} />
            )}

            {slice.slice_type === "space" && <Space data={slice} />}
            {slice.slice_type === "logo" && <LogoLanding data={slice} />}

            {slice.slice_type === "landing_pricing" && (
              <LandingPricing data={slice} lang={props.pageContext.lang} />
            )}
            {slice.slice_type === "form_quote_exhibitors" && (
              <LandingForm data={slice} lang={props.pageContext.lang} />
            )}
            {slice.slice_type === "vertical_tabs_big_texts" && (
              <TabsVerticalBigTexts data={slice} />
            )}
            {slice.slice_type === "quote_v2" && <QuoteSlider data={slice} />}
            {slice.slice_type === "list_customers_video" && (
              <ListCustomersVideo data={slice} />
            )}
            {slice.slice_type === "twitter" && <Twitter data={slice} />}
            {slice.slice_type === "v2_left_text___images" && (
              <TextVerticalImage data={slice} />
            )}
            {slice.slice_type === "title_and_subtitle" && (
              <TitleSubTitle data={slice} lang={props.pageContext.lang} />
            )}
            {slice.slice_type === "discovery" && (
              <Discovery data={slice} lang={props.pageContext.lang} />
            )}

            {slice.slice_type === "prev_and_next_buttons" && (
              <PrevNextButtons data={slice} lang={props.pageContext.lang} />
            )}

            {slice.slice_type === "faq_attendify" && (
              <FaqAttendify data={slice} lang={props.pageContext.lang} />
            )}
            {slice.slice_type === "tabs_horizontal_2" && (
              <TabsHorizontal2 data={slice} />
            )}

            {slice.slice_type === "iframe" && <Iframe data={slice} />}
            {slice.slice_type === "features_list_short" && (
              <FeaturesListShort data={slice} />
            )}
            {slice.slice_type === "paragraph" && <Paragraph data={slice} />}
            {slice.slice_type === "policy" && <Policy data={slice} />}
            {slice.slice_type === "article" && (
              <Article
                layout={slice.primary.layout}
                maxWidth={slice.primary.max_width_picture}
                odd={slice.primary.odd}
                title={slice.primary.article_title.text}
                body={slice.primary.article_content}
                img={slice.primary.article_image.url}
                data={slice}
              />
            )}
            {slice.slice_type === "article_two_column" && (
              <Article
                items={slice.items}
                title={slice.primary.article_title[0].text}
                body={slice.primary.article_sub_title}
                layout="two-col"
              />
            )}
            {slice.slice_type === "get_in_touch_v2" && (
              <GetInTouch2 data={slice} lang={props.pageContext.lang} />
            )}
            {slice.slice_type === "faq" && <FAQ data={slice} />}
            {slice.slice_type === "funcionalities_card" && (
              <Card data={slice} />
            )}
            {slice.slice_type === "video_slider" && (
              <VideoSlider data={slice} />
            )}
          </React.Fragment>
        ))}
      </div>
    </Layout>
  );
};

export const query = graphql`
  query getDocumentTemplate($id: String!, $lang: String!) {
    prismicTemplate1(id: { eq: $id }) {
      ...heroFragment
      ...featureShortFragment
      ...listCustomersVideoFragment
      ...space
      ...textVertical
      ...benefitsFragment
      ...titleAndSubtitle
      ...redBull
      ...policyFragment
      ...featuresOverviewPicto
      ...dividerFragment
      ...getInTouch2Fragment
      ...discoveryFragment
      ...testimonailsSolutionFragment
      ...faqFragment
      ...article

      ...pricingNewFragment

      ...youtubeFragment
      ...landingFormFragment
      ...tabsVerticalFragment
      ...kpiCustomersFragment
      ...quoteFragment
      ...faqAttendifyFragment
      ...quote2Fragment
      ...twitterFragment
      ...prevNextButtonsFragment
      ...htmlFragment
      ...customersLogoFragment
      ...imageFragment
      ...logoLandingsFragment
      ...paragraphFragment
      ...buttonsFragment
      ...bannerTextsFragment
      ...landingPricingFragment
      ...iframeFragment
      ...integrations2Fragment
      ...navigationScrollFragment
      ...filsArianeFragment
      ...functionalitiesCardFragment
      ...videoSliderFragment
    }

    translation: prismicTranslate(lang: { eq: $lang }) {
      ...genericData
    }
  }
`;
```

**Comment by RobinHerzog** [comment]
I don't understand how this page should get data.
Once I get on /preview, I get redirect on my page but without any new data.

**Comment by angeloashmore** [comment]
@chrisbujok TODO refers to the documentation. At a high level, you would need the following to fully support previews:

## Previously published previews

- Preview page (e.g. `src/pages/preview.js`) that uses the [`usePrismicPreview`](https://github.com/angeloashmore/gatsby-source-prismic/blob/da34014135d3c0ecfd25d66260e6261b78b0afbd/docs/previews.md#useprismicpreview-1) hook to pull preview data from Prismic.
- On the Preview page, data is saved to `window` or some global store. The example in the docs uses location state but we've found it fails when on circular data structures, which is most pages.
- Preview page navigates to real page where it needs to read the data from `window` or the global store and merge with your page's existing data using [`mergePrismicPreviewData`](https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/docs/previews.md#mergeprismicpreviewdata-1). This merged data is what your page/template should use.

## Unpublished previews

- Unpublished previews still go to the Preview page, but gets navigated to the unpublished page.
- Unpublished preview page (e.g `src/pages/unpublishedPreview.js`) reads data from `window` or global store and uses your existing templates/pages to render the document.

Unpublished previews take advantage of the fact that pages and templates are still just React components. You will need to import them and use them like regular components, passing the preview data on the `data` prop.

@RobinHerzog The above should explain how to setup reading the data. Basically the preview data needs to be saved to some global, such as `window`, then read on the destination page, and finally merged with the existing old data.

We're in the middle of changing a small bit of the API but updated docs should be available soon. In the mean time, feel free to post questions here and I'll do my best to answer.

**Comment by angeloashmore** [comment]
@RobinHerzog As an aside, I recommend checking out [`react-map-to-components`](https://github.com/angeloashmore/react-map-to-components) for rendering your slices. It could reduce a lot of the `slice.slice_type === "get_in_touch_v2" &&` checks in your template.

**Comment by RobinHerzog** [comment]
I've able to get the data from the API but there is a little difference.

As you can see there is an array added that come from the preview data
 
<img width="535" alt="Capture d'écran 2019-07-10 10 15 47" src="https://user-images.githubusercontent.com/4397570/60952578-ce1cdd80-a2fb-11e9-898a-71e370d9a9e4.png">

<img width="600" alt="Capture d'écran 2019-07-10 10 15 38" src="https://user-images.githubusercontent.com/4397570/60952582-d117ce00-a2fb-11e9-8a04-4b97b8d771a3.png">
